-- HIC.1: strengthen universal_facts_checklist entry 4 (IPC staffing benchmark citation).
-- Internal review field only; not rendered into the DOCX. No document output changes.
update public.shco_policy_masters
   set universal_facts_checklist = 'Universal (non-NABH) facts included in this draft, and where each was verified. Check these first.

1. WHO eight core components of an IPC programme — used as the structural spine of the programme and reproduced as the eight scored components in step 12. Components: IPC programmes; guidelines; education and training; HAI surveillance; multimodal strategies; monitoring/audit/feedback; workload, staffing and bed occupancy; built environment, materials and equipment. Components 1-6 apply at both national and facility level; 7-8 are facility level. Verified via WHO Guidelines on Core Components of IPC Programmes (2016), NCBI Bookshelf NBK401761 / NBK401773.

2. WHO IPCAF scoring — eight sections, maximum 100 points each, 800 total; bands Inadequate 0-200, Basic 201-400, Intermediate 401-600, Advanced 601-800. Used in step 12. Verified via WHO IPCAF (WHO/HIS/SDS/2018.9) and published facility studies applying it.

3. WHO multimodal improvement strategy, five elements — system change; training and education; monitoring and feedback; reminders and communications; culture of safety. Used verbatim as the five bullets in step 10 (in my own wording). Verified via WHO IPC core components multimodal strategy document.

4. IPC staffing benchmark — a minimum of one full-time equivalent trained infection prevention professional (nurse or doctor) per 250 beds, described in the source as a floor with a richer ratio argued for in higher-acuity settings. Used in step 16. Verified via WHO, Minimum requirements for infection prevention and control programmes, Geneva: World Health Organization, 2019 — re-verified 2026-08-13 against the source PDF itself rather than a secondary summary.
   EXACT WORDING RELIED ON. Secondary care (p.23, p.32): "Trained IPC focal point (one full-time trained IPC officer [nurse or doctor]) as per the recommended ratio of 1:250 beds with dedicated time to carry out IPC activities in all facilities", with the worked example that a 120-bed facility requires one 50% full-time equivalent dedicated officer — which is the arithmetic step 16 asks the hospital to perform for its own bed count. Tertiary care (p.23, p.32): "At least one full-time trained IPC focal point (nurse or doctor) with dedicated time per 250 beds."
   THE "FLOOR, NOT A TARGET" CHARACTERISATION IS WHO''S OWN, at p.35: "A minimum ratio of one full-time or equivalent IPC professional (nurse or doctor) per 250 beds or a higher ratio (one IPC professional per 100 beds) due to increased patient acuity and complexity, as well as the multiple roles and increasing responsibilities of the IPC professional." This single sentence carries both halves of step 16 — the 1:250 floor and the richer ratio for higher acuity — so step 16 does not depend on any source outside WHO. WHO itself names 1:100 as the higher ratio.
   LINEAGE OF THE TWO NUMBERS, recorded so it need not be re-derived. The 1:250 figure originates in the CDC Study on the Efficacy of Nosocomial Infection Control (SENIC), 1985, which associated one infection control professional per 250 occupied acute care beds with a 32% reduction in nosocomial infection. The 1:100 comparator originates in the APIC Delphi study — O''Boyle C, Jackson M, Henly SJ, "Staffing requirements for infection control programs in US health care facilities: Delphi project", American Journal of Infection Control, October 2002 — which recommended 0.8 to 1.0 infection control professionals per 100 occupied acute care beds, roughly 2.5 to 3 times the SENIC figure, on the ground that the scope of the role had expanded well beyond what SENIC measured.
   REVIEWER TO NOTE: the professional-society literature treats 1:250 as outdated on its own, and published ratios in current practice run richer still. Step 16 is nonetheless correct as written and correctly sourced: it presents 1:250 as a floor, not as adequate staffing, and requires {{HOSPITAL_NAME}} to state and justify its own establishment rather than adopt the benchmark as its target. No change to step 16 is required.

5. Airborne infection isolation room engineering specification — negative pressure differential of at least 2.5 Pa (0.01 inches water gauge); at least 12 air changes per hour for new construction and renovation, not fewer than 6 ACH for existing rooms; exhaust to outside away from intakes, or HEPA filtration if recirculated. Used in step 19. Verified via CDC guidance and ASHRAE Standard 170 as reported in current AIIR references.

6. Droplet precautions spatial separation — at least 3 feet (approximately 1 metre) between an infected patient and others where a single room is unavailable, with the bed curtain drawn; single-patient room preferred, cohorting only after consulting IPC personnel. Used in step 20. Verified via CDC Guideline for Isolation Precautions.

7. India national IPC reference — National Guidelines for Infection Prevention and Control in Healthcare Facilities, NCDC / Ministry of Health and Family Welfare, published January 2020 (first reprint March 2020), developed with the WHO Country Office. Cited in references and underpins the India-specific framing.

8. India outbreak and notifiable disease reporting route — hospitals in both public and private sector report to the district surveillance unit under the Integrated Disease Surveillance Programme, now largely through the Integrated Health Information Platform, the cloud-based system rolled out nationally in 2021 that replaced paper-based IDSP reporting; State governments additionally specify their own notifiable disease lists. Used in step 25. Verified via MoHFW/IDSP sources and the WHO India announcement of the IHIP rollout.

DELIBERATELY NOT INCLUDED — these were checked and judged to belong to other standards:
- Spaulding classification, high-level disinfection, sterilisation agents and contact times, CSSD reprocessing, laundry wash parameters, and the environmental cleaning schedule. These sit with HIC.3 / HIC.6 and remain open in scripts/master-policy-todos.md. Step 4 requires the manual to contain policies on them; it does not attempt to write those policies.
- HAI surveillance methodology (case definitions, device-day counting, rate calculation, benchmarking). Step 8 carries a pointer only and names the four infection types; the method belongs to CQI, matching the treatment already agreed for the HIC.2 draft.
- Environmental surveillance method (OT air sampling, HEPA integrity, temperature and humidity limits). Step 9 fixes ownership and the requirement that results reach the IPCC, but defers method to the environment/facility standards. Note: NABH''s own HIC checklist tags this "HIC 1 c", but that checklist uses an older Entry-Level edition''s numbering — under SHCO 3rd Edition, HIC.1.c is the infection control committee, so the tag was not followed as an OE map.

HOSPITAL-SPECIFIC VALUES LEFT AS [Hospital to define] — 20 occurrences: IPCC chair, meeting frequency and quorum; ICN committed hours; manual review interval; numeric programme targets; training interval; assessment tool identity and review interval; IPC staffing establishment; consumable stock/reorder levels; number of isolation rooms; isolation equipment check interval; AIIR pressure verification interval; barrier nursing drill interval; community outreach frequency; district health authority contact; outbreak plan test interval; State notifiable disease list; notification officer and deputy; management reporting interval; record retention period; intranet/folder location.'
 where standard_code = 'HIC.1';
