-- IMS Chapter: Information Management System
-- 30 OEs × 4 tips each

update public.shco_full_oes set achieve_tips = '["Conduct a stakeholder mapping exercise to list all information users — patients, visitors, nursing staff, management, lab, and external agencies — and document what specific information each group requires from the hospital system.","Display key information such as service timings, visiting hours, rights and responsibilities, and emergency contacts on notice boards in all patient-facing areas, and maintain a record of updates made each quarter.","During assessor visits, staff must be able to explain verbally which information channels are used for different stakeholder groups and demonstrate at least one recent example of information dissemination to the community.","Review the information needs register at least twice a year, update it based on feedback from patients and staff, and keep signed records of each review meeting to show assessors during audit."]'::jsonb where oe_code = 'IMS.1.a';

update public.shco_full_oes set achieve_tips = '["Prepare a written Information Management and Technology Plan that maps each identified stakeholder information need to a specific tool, software module, or manual process used to fulfil it, and get it approved by management.","Include IT hardware and software procurement decisions in the annual planning cycle and document how each acquisition addresses a documented information gap identified in the stakeholder needs assessment.","Maintain a maintenance log for all IT systems and medical equipment used for data capture, recording dates of servicing, software updates, and any downtime incidents to demonstrate proactive upkeep.","Train the IT in-charge and department heads on the technology plan annually, document attendance, and ensure staff can explain to assessors how the plan aligns with operational information needs."]'::jsonb where oe_code = 'IMS.1.b';

update public.shco_full_oes set achieve_tips = '["Establish a written SOP for data storage covering physical records (MRD filing system) and digital records (HIS or EMR), specifying folder structures, naming conventions, backup frequency, and authorized access levels.","Implement a retrieval turnaround time standard — for example, any requested medical record must be available within 30 minutes during working hours — and log every retrieval request with time-in and time-out to measure compliance.","Conduct quarterly drills where MRD staff retrieve a sample of 10 records and document retrieval times, flagging and correcting delays to demonstrate continuous improvement to assessors.","Train all MRD staff on the storage and retrieval SOP, maintain signed training attendance sheets, and ensure staff can demonstrate the retrieval process step by step when asked during assessment."]'::jsonb where oe_code = 'IMS.1.c';

update public.shco_full_oes set achieve_tips = '["Identify all external databases and regulatory reporting obligations applicable to your hospital — such as birth and death reporting, notifiable disease registers, and PCPNDT records — and create a compliance calendar with monthly submission deadlines.","Designate a responsible officer for each external reporting requirement, document their name and role in the compliance calendar, and ensure they are aware of the legal timelines and formats required.","Maintain copies of all submissions made to external agencies, including acknowledgement receipts or submission confirmation, filed chronologically to show assessors a complete trail of regulatory compliance.","Conduct an internal audit every six months to verify that all mandatory external submissions were made on time, document findings, and take corrective action for any missed or delayed submission."]'::jsonb where oe_code = 'IMS.1.d';

update public.shco_full_oes set achieve_tips = '["Standardize all data collection forms — OPD registers, IPD admission forms, discharge summaries, and lab request slips — using pre-approved templates with clear field definitions, and withdraw all outdated formats from use.","Implement a monthly data analysis routine where the MRD team compiles key indicators such as bed occupancy, average length of stay, readmission rates, and infection counts and shares a summary report with department heads.","Create a standard data dictionary that defines each data element collected across departments, ensuring consistent interpretation, and make it accessible to all data entry staff and MRD personnel.","Retain monthly data analysis reports with evidence of distribution to management, and ensure the person responsible can explain the analysis methodology and findings clearly during an assessor interview."]'::jsonb where oe_code = 'IMS.1.e';

update public.shco_full_oes set achieve_tips = '["Implement a Hospital Registration Number (HRN) or UHID system that assigns a single unique identifier to every patient at first registration, ensuring no duplicate numbers exist across OPD, IPD, emergency, and diagnostic records.","Display the unique identifier prominently on every medical record folder, wristband, prescription, lab report, and discharge summary so staff can cross-reference documents quickly and accurately.","Train registration staff and ward clerks on the importance of searching for an existing UHID before assigning a new one, and maintain a register of any duplicate detections and how they were merged and resolved.","During assessor observation, staff should be able to demonstrate the registration process live, show how the UHID is assigned, and produce any patient''s complete record using only the unique identifier as the search key."]'::jsonb where oe_code = 'IMS.2.a';

update public.shco_full_oes set achieve_tips = '["Define and document the minimum required contents of a medical record in your hospital''s medical records policy, including patient demographics, consent forms, clinical notes, investigation reports, nursing records, and discharge summary.","Conduct a monthly completeness audit of at least 20 randomly selected medical records using a checklist, score each record, and display the compliance percentage on the quality dashboard for all departments to review.","Ensure all entries in the medical record are made in chronological order with clear dates and times, and train clinical staff to complete missing entries within 24 hours of the care event, not retrospectively during discharge.","During assessor review, selected medical records must demonstrate a complete, logical, and time-sequenced account of care — staff must be able to narrate the patient journey using only the record without additional verbal explanation."]'::jsonb where oe_code = 'IMS.2.b';

update public.shco_full_oes set achieve_tips = '["Maintain a current list of all authorized medical record entry personnel — doctors, nurses, physiotherapists, and dieticians — with their designations and specimen signatures filed in the MRD and updated whenever staff join or leave.","Implement a policy that only credentialed and privileged staff may write orders or clinical notes in the medical record; ward supervisors must verify this during every shift handover and document any violations.","Spot-check 10 records monthly to confirm that every entry can be traced to an identified author through a legible name stamp, signature, or unique digital login identifier, and record audit findings with follow-up actions.","Assessors will interview nursing and medical staff to verify they understand who is authorized to make entries; ensure all staff can answer this question correctly and point to the authorization list without hesitation."]'::jsonb where oe_code = 'IMS.2.c';

update public.shco_full_oes set achieve_tips = '["Issue personalized rubber name stamps to all doctors and ensure every clinical note, prescription, and order in the medical record includes the author''s name stamp, signature, date, and time of entry as a non-negotiable standard.","Train all clinical staff during induction that incomplete entries — missing date, time, or signature — are non-compliant, and include this requirement in the annual clinical competency refresher with a post-training checklist sign-off.","Include name-date-time completeness as a specific parameter in monthly medical record audits; any record with more than two incomplete entries should trigger a corrective action memo to the concerned department head.","Display a one-page reminder poster at each nursing station and doctors'' writing desk showing the mandatory entry format: Name | Designation | Signature | Date (DD/MM/YYYY) | Time (HH:MM), so staff have a constant visual reference."]'::jsonb where oe_code = 'IMS.2.d';

update public.shco_full_oes set achieve_tips = '["Prepare and circulate a hospital-approved abbreviation list, ensuring it is available at every nursing station, doctors'' area, and the MRD; remove all unapproved abbreviations from templates and forms immediately.","Incorporate a section in staff orientation and annual refresher training that specifically covers approved versus prohibited abbreviations, with examples of dangerous abbreviations (such as U for units or IU for international units) that must never be used.","During monthly medical record audits, flag any entry containing an unapproved abbreviation, report it to the concerned department head, and track whether the same abbreviation recurs the following month as a trend indicator.","Post the approved abbreviation list prominently in clinical areas and ensure assessors can find it easily; staff must be able to locate the list immediately and explain how they were trained on its use."]'::jsonb where oe_code = 'IMS.2.e';

update public.shco_full_oes set achieve_tips = '["Ensure the medical record''s admission sheet is completed within two hours of patient arrival, documenting the reason for admission, provisional or confirmed diagnosis, and an initial plan of care signed by the admitting doctor.","Create a structured admission note template that prompts clinicians to fill in chief complaint, history of present illness, provisional diagnosis, and immediate management plan, leaving no field blank before the patient is shifted to the ward.","Conduct weekly spot-checks on five recently admitted patients'' records to verify that reason for admission, diagnosis, and care plan are documented before any investigations or treatments are initiated, and record audit findings.","Train junior doctors and residents during departmental orientation that incomplete admission notes are a patient safety and compliance risk; demonstrate a correctly completed admission note as the benchmark during training sessions."]'::jsonb where oe_code = 'IMS.3.a';

update public.shco_full_oes set achieve_tips = '["Develop department-specific medical record templates that include dedicated sections for initial assessment, daily re-assessments, specialist consultation notes, investigation results, and procedure notes so no element is inadvertently omitted.","Establish a policy that investigation reports — lab, radiology, ECG — must be pasted or attached to the medical record within four hours of receipt, with the treating doctor''s acknowledgement signature on each report.","Ensure nursing staff document re-assessments at each shift using structured SOAP or narrative notes, and include vital signs, pain scores, and any change in patient condition with exact time of observation recorded.","During assessor review, pull three active patient records at random and verify they contain all required elements; department heads should rehearse this exercise monthly so clinical staff are always audit-ready."]'::jsonb where oe_code = 'IMS.3.b';

update public.shco_full_oes set achieve_tips = '["Create a standardized inter-hospital transfer form that captures the reason for transfer, patient''s condition at time of transfer, treatment given, pending investigations, and the receiving facility''s name, and attach it to every transferred patient''s record.","Obtain the patient''s or family''s written consent for transfer, attach the signed consent to the medical record, and ensure the transfer note is co-signed by the attending doctor and a nurse who was present at the time of transfer.","Train charge nurses and on-call doctors on the transfer documentation protocol during departmental meetings, covering what must be documented before the patient leaves the premises, and conduct a mock drill twice a year.","Maintain a transfer register in the ward and emergency department that logs all transfers out, cross-referenced with the medical record number so assessors can quickly trace any transfer case and verify documentation completeness."]'::jsonb where oe_code = 'IMS.3.c';

update public.shco_full_oes set achieve_tips = '["Implement a policy that the discharge summary must be completed and signed by the treating doctor within 24 hours of patient discharge, with a copy placed inside the medical record and another given to the patient.","Use a structured discharge summary template that covers diagnosis, procedures performed, treatment given, condition at discharge, follow-up instructions, and medications prescribed so no key element is missed.","Conduct a monthly completeness audit of all discharge summaries filed in the previous month, scoring completeness against the template, and share results with treating doctors and department heads for improvement.","Ensure staff in the MRD can quickly retrieve any discharge summary by patient UHID and that assessors are shown a sample of discharge summaries during audit that demonstrate legibility, completeness, and timely filing."]'::jsonb where oe_code = 'IMS.3.d';

update public.shco_full_oes set achieve_tips = '["Establish a policy that in every case of in-hospital death, the cause of death certificate must be issued by the treating or on-call doctor and a copy filed in the medical record before the body is handed over.","Create a dedicated section in the medical record folder labelled ''Death Documentation'' where the cause of death certificate, time of death note, and information given to relatives are all filed together for easy retrieval.","Train all doctors and ward staff on the death documentation process during induction, including the legal requirement to issue a cause of death certificate and the hospital''s responsibility to maintain a copy in the record.","Maintain a death register in the MRD cross-referenced with medical record numbers, and ensure assessors can retrieve any death case file and find the cause of death certificate filed accurately within two minutes."]'::jsonb where oe_code = 'IMS.3.e';

update public.shco_full_oes set achieve_tips = '["Implement a role-based access control policy in your HIS or manual record system that allows treating doctors, nurses, and allied health staff to access only the records of patients currently under their care, and document the access matrix.","Ensure that past medical records of returning patients are available to the treating team within 30 minutes of a new admission or OPD visit; log retrieval requests and response times to demonstrate consistent access to historical data.","Establish a process for emergency access to records outside working hours, designating an on-call MRD contact or HIS administrator who can retrieve previous records when needed, and document this process in a written SOP.","During assessor interviews, clinical staff must be able to explain how they access a past record for a readmitted patient and demonstrate the retrieval process; conduct mock access drills quarterly to keep all staff familiar with the procedure."]'::jsonb where oe_code = 'IMS.3.f';

update public.shco_full_oes set achieve_tips = '["Implement a written confidentiality policy signed by every staff member at joining, making explicit that patient information — verbal, written, or digital — must not be disclosed to unauthorized persons under any circumstances.","Restrict access to patient files in the MRD to authorized personnel only; keep the MRD door locked when unattended and maintain a visitor entry log to record every person who accesses the record storage area.","Conduct quarterly confidentiality awareness sessions for all clinical and non-clinical staff covering real-world scenarios — such as family members asking for diagnosis details — and document attendance to show assessors during audit.","During assessor interviews, staff must demonstrate knowledge of the confidentiality policy, explain what they would do if asked for patient information by an unauthorized person, and locate the signed confidentiality agreement in their personnel file."]'::jsonb where oe_code = 'IMS.4.a';

update public.shco_full_oes set achieve_tips = '["Establish a policy that no entry in the medical record may be erased, overwritten with correction fluid, or obscured; errors must be crossed out with a single line, marked ''error,'' and initialled with the date so the original entry remains readable.","For digital records, configure the HIS to maintain a complete audit trail of all entries, modifications, and deletions with user ID, timestamp, and reason for change — ensure this audit log is reviewed monthly by the IT or quality team.","Train all clinical staff that altering a medical record entry improperly is a serious violation with legal implications; include a case-based scenario on record integrity in the annual medical ethics and compliance training.","During assessor review of records, demonstrate that correction entries are made correctly with visible original text, initials, and date — pull sample records from the past quarter to show consistent compliance across departments."]'::jsonb where oe_code = 'IMS.4.b';

update public.shco_full_oes set achieve_tips = '["Implement password-protected user accounts for all HIS or digital data systems with a policy requiring password changes every 90 days; disable accounts of staff who have left within 24 hours of their departure.","Secure physical medical record storage by fitting MRD shelving with locked bays for sensitive records, installing CCTV coverage of the MRD area, and maintaining a movement register for every record taken out of storage.","Back up all digital data automatically every day to a secure off-site or cloud location, maintain a backup log with dates and verification status, and test data restoration from backup at least once every six months.","Assessors will look for evidence of physical and digital security controls; ensure the MRD in-charge can demonstrate the locking system, access log, and HIS user management screen without prior preparation during an unannounced visit."]'::jsonb where oe_code = 'IMS.4.c';

update public.shco_full_oes set achieve_tips = '["Develop a written SOP on disclosure of health information covering the three permissible scenarios: patient''s own written request, authorized representative''s request, and mandatory legal or regulatory disclosure, with a separate form for each.","Maintain a Disclosure Register that records every instance of information release — date, requestor name, nature of information disclosed, legal basis for disclosure, and the authorizing officer''s signature — and file it in the MRD.","Train front desk staff, MRD personnel, and nursing staff on how to handle requests for patient information, emphasizing that verbal disclosure over the phone is never permitted without written authorization and documented identity verification.","During assessor interviews, MRD and reception staff must be able to walk through the disclosure process step by step; demonstrate a completed disclosure request form and its corresponding register entry as a concrete example."]'::jsonb where oe_code = 'IMS.4.d';

update public.shco_full_oes set achieve_tips = '["Create a Record Access Request Form that patients, doctors, and external agencies must complete when requesting copies of or access to medical records, specifying the purpose, records required, and identity proof provided.","Establish a turnaround time standard for access requests — for example, patient requests fulfilled within 48 hours and medico-legal requests within 72 hours — and log every request with receipt date, due date, and date fulfilled.","Designate the MRD in-charge as the single point of contact for all access requests and ensure they are trained on patient rights, medico-legal obligations, and data protection, with a documented annual training record.","Conduct a quarterly review of the access request log to identify any requests that exceeded the turnaround time, document root cause analysis for delays, and implement corrective actions before the next NABH assessment cycle."]'::jsonb where oe_code = 'IMS.4.e';

update public.shco_full_oes set achieve_tips = '["Establish a document control system with a Document Master List that records the document name, version number, effective date, review date, and document owner for every policy, SOP, and form in use across the hospital.","Ensure all documents in circulation bear the current version number and review date on the header or footer; collect and destroy or archive all superseded versions immediately upon release of an updated document.","Assign a Document Controller role — typically the Quality Manager — who is responsible for approving, distributing, and withdrawing documents; no document should be issued or updated without this person''s sign-off.","During assessor observation, pick any clinical area at random and verify that all displayed SOPs and forms match the current version in the Document Master List; staff must be able to explain who updates documents and how old versions are removed."]'::jsonb where oe_code = 'IMS.5.a';

update public.shco_full_oes set achieve_tips = '["Document the hospital''s medical record retention policy specifying minimum retention periods — for example, adult records for five years post-discharge, paediatric records until the patient turns 21, and medico-legal records for longer as required by applicable law.","Maintain a retention schedule table in the MRD that lists all record types (OPD, IPD, ICU, emergency, lab, radiology, pharmacy) alongside their mandated retention period and the date after which each batch may be considered for archiving or disposal.","Physically label archived record boxes with the date range, retention deadline, and disposal authorization date, and store them in a dry, pest-free space with a location index so any record can be retrieved quickly even years after discharge.","During assessor review, demonstrate the retention schedule, pull a record from five or more years ago to show it is intact and retrievable, and confirm that no record within its retention period has been disposed of without authorization."]'::jsonb where oe_code = 'IMS.5.b';

update public.shco_full_oes set achieve_tips = '["Develop an SOP for record retention that includes physical security measures: locked storage rooms, climate and humidity controls where feasible, restricted access lists, and periodic inspection records for the storage area.","Ensure that all archived patient records are stored in sealed, labelled boxes with no patient identifiers visible on the outside, and that the storage area is accessible only to authorized MRD personnel with a key register maintained.","For digital archives, ensure that backups are encrypted, stored on secure servers, and access-protected so that retained data cannot be read, altered, or deleted by unauthorized users, with access logs reviewed quarterly.","Train MRD staff and the IT team on the confidentiality obligations that extend to retained records — the fact that a record is archived does not reduce the obligation to protect it — and document this training in staff records."]'::jsonb where oe_code = 'IMS.5.c';

update public.shco_full_oes set achieve_tips = '["Write a Medical Record Destruction Policy that defines who may authorize destruction, which records are eligible (past their retention period), the approved destruction method (shredding for paper, certified wiping for digital), and how destruction is documented.","Maintain a Destruction Register that records the UHID range or document batch, retention period end date, date of destruction, method used, quantity, and the signature of the authorizing officer and the person who carried out the destruction.","Use a third-party certified shredding service for bulk destruction of paper records and obtain a destruction certificate from the vendor to file alongside the Destruction Register as dual evidence of compliant disposal.","Conduct a pre-destruction review with the Medical Superintendent or Quality Head to confirm no record in the batch is subject to pending litigation, insurance query, or regulatory hold before authorizing destruction, and document this clearance check."]'::jsonb where oe_code = 'IMS.5.d';

update public.shco_full_oes set achieve_tips = '["Establish a Medical Records Committee or designate the Quality Team to conduct formal medical record audits at a defined frequency — at minimum monthly — using a standardized checklist covering completeness, legibility, timeliness, and correct filing.","Maintain a Medical Record Review Register that logs each review cycle: date conducted, number of records reviewed, audit scores, deficiencies identified, and the corrective actions raised with responsible departments.","During assessor visits, present the last three months of review registers and demonstrate the trend of completeness scores improving over time; assessors specifically look for evidence that reviews happen regularly and are not just conducted before accreditation.","Use the findings from periodic reviews to update staff training content — if a recurring deficiency is found in a specific documentation element, add a focused module on that element in the next departmental CME or in-service training session."]'::jsonb where oe_code = 'IMS.6.a';

update public.shco_full_oes set achieve_tips = '["Apply a statistically valid sampling method for record reviews — for example, using a random number table or HIS-generated random UHID list — to select records from both currently admitted patients and those discharged in the review period.","Document the sample selection methodology in the Medical Records Committee minutes, specifying the total patient population, sample size formula used, and how active and discharged records are proportionally represented in each review cycle.","Ensure the sample includes records from different departments, age groups, and lengths of stay to get a representative cross-section of documentation quality across the hospital, not just from the best-performing wards.","Train the Quality or MRD team on basic statistical sampling concepts so they can explain the selection rationale to assessors; keep a sampling log showing how many active versus discharged records were reviewed in each monthly cycle."]'::jsonb where oe_code = 'IMS.6.b';

update public.shco_full_oes set achieve_tips = '["Formally designate the members of the Medical Records Review Committee by name and designation in a written order signed by the Medical Superintendent, including at least one clinician, one nursing representative, and the MRD in-charge.","Maintain attendance records for every review session to demonstrate that the designated individuals are consistently conducting the reviews and that the process is not delegated informally to junior staff without committee oversight.","Rotate the clinical reviewer role across departments periodically — for example, have the Surgery department lead one month and Medicine the next — so that different specialties gain ownership of documentation quality across the hospital.","Assessors will ask who conducts the medical record review; ensure the designated committee members can describe their role, the review frequency, and the most recent findings without needing to consult documents during the interview."]'::jsonb where oe_code = 'IMS.6.c';

update public.shco_full_oes set achieve_tips = '["Define a set of measurable review parameters in the Medical Records Committee charter — such as completeness of discharge summary, timeliness of operation notes, presence of consent forms, legibility of entries, and use of only approved abbreviations.","Create a scoring checklist with one row per parameter, a yes/no or percentage score column, and a comments column; use the same checklist every month so trend data is comparable across review cycles.","Share the parameter-wise scores with department heads after each review, highlighting the top three deficiencies, and require each head to submit a written corrective action plan within one week of receiving the report.","Display a monthly dashboard in the MRD and quality board showing the trend of each review parameter over the last six months; this visual evidence demonstrates ongoing monitoring and is highly effective during assessor walkthroughs."]'::jsonb where oe_code = 'IMS.6.d';

update public.shco_full_oes set achieve_tips = '["Log every deficiency identified during medical record reviews in a Corrective Action Tracker with columns for deficiency description, responsible department, action to be taken, target date, and closure status reviewed at the next committee meeting.","For recurring deficiencies, escalate from individual feedback to systemic correction — for example, if missing consent forms are found repeatedly, revise the admission checklist so consent is obtained before the patient enters the ward.","Follow up on each corrective action within 30 days by re-auditing the same parameter in the concerned department to verify whether the action was implemented and effective, and document the follow-up findings in the tracker.","Present the Corrective Action Tracker to assessors as primary evidence of a closed-loop improvement process; assessors specifically look for proof that identified gaps are not just noted but actually resolved with measurable impact on documentation quality."]'::jsonb where oe_code = 'IMS.6.e';
