-- PRE: Patient Rights and Education — achieve_tips UPDATE statements
-- 39 OEs total | Generated for SHCO Full Accreditation

-- PRE.1.a | Commitment | Rights & responsibilities documented, displayed, made aware
update public.shco_full_oes set achieve_tips = '["Draft a written Patient Rights and Responsibilities charter in simple language, get it approved by management, and display laminated copies at OPD reception, admission counter, and all ward entrances.","Create an SOP requiring admission staff to verbally walk every patient through their rights and hand over a printed rights card; document this briefing in the admission register with patient signature.","Train all front-desk, nursing, and ward-boy staff annually on the content of the rights charter using a structured module; maintain attendance records and a post-training quiz score sheet for assessor review.","Conduct quarterly internal audits verifying that rights displays are present, legible, and current at all mandated locations; record findings and corrective actions in the audit register."]'::jsonb where oe_code = 'PRE.1.a';

-- PRE.1.b | Achievement | Rights actively promoted
update public.shco_full_oes set achieve_tips = '["Run a monthly patient-facing awareness activity such as a display board update, pamphlet distribution, or a short video in the waiting area; record each activity with date, topic, and number of patients reached.","Measure promotion effectiveness by including a ''Were you informed of your rights?'' question in the patient satisfaction survey; track monthly scores and document improvement trends as before/after evidence.","Post rights information in multiple local languages across clinical areas and photograph each display with a date stamp; maintain a photo log showing progressive improvements in visibility and multilingual coverage.","Compile a quarterly report summarising promotion activities, patient feedback on rights awareness, and any gap-closure actions taken; present this at the patient safety committee meeting and file the minutes."]'::jsonb where oe_code = 'PRE.1.b';

-- PRE.1.c | Core | Organisation protects patient & family rights
update public.shco_full_oes set achieve_tips = '["Maintain a patient rights protection log where any reported concern (e.g., denied privacy, coercive treatment) is recorded, investigated, and closed within a defined timeline; keep this register available for assessor inspection.","During ward rounds, staff should actively observe whether curtains are drawn during examinations, confidentiality is maintained at nurses'' stations, and patients are spoken to respectfully; supervisors should document these observations on a monthly checklist.","Assessors will interview nursing and ward staff — prepare staff to articulate at least three specific rights they are responsible for upholding and give a real example of how they applied one in the past month.","Review patient records each month for evidence that rights-related obligations (e.g., consent, confidentiality agreements) are consistently documented; flag and correct missing entries before the next assessment cycle."]'::jsonb where oe_code = 'PRE.1.c';

-- PRE.1.d | Core | Mechanism to report violation of rights
update public.shco_full_oes set achieve_tips = '["Install a clearly labelled complaint/rights-violation reporting box at a visible, accessible location and appoint a designated staff member to review submissions daily; document each submission and its resolution in a register.","Create an SOP outlining the step-by-step process for a patient or family to report a rights violation, including whom to contact, expected response time, and escalation path; display this process prominently near the complaint box.","Train staff on how to receive, record, and escalate a rights violation report without retaliating against the patient; include scenario-based practice in the training and retain attendance and assessment records.","Assessors will ask staff to explain the complaint mechanism — conduct mock drills quarterly where a staff member role-plays receiving a violation report, documents it correctly, and escalates it; record drill outcomes."]'::jsonb where oe_code = 'PRE.1.d';

-- PRE.1.e | Core | Violations monitored, analysed, CAPA by top leadership
update public.shco_full_oes set achieve_tips = '["Compile a monthly rights-violation summary report showing number of complaints received, nature of violations, resolution timelines, and pending cases; present this report to top leadership and file signed minutes as evidence.","Perform root-cause analysis for recurring or serious violations and document a formal corrective/preventive action plan with responsible owners and target dates; track completion of each action item.","Assessors will review records of leadership involvement — ensure that meeting minutes, email approvals, or signed CAPA forms clearly show that the medical superintendent or equivalent has personally reviewed and acted on violation data.","Set a measurable target (e.g., zero unresolved complaints beyond 7 days) and track monthly performance against it; display a trend chart in the quality office showing month-on-month improvement for the past year."]'::jsonb where oe_code = 'PRE.1.e';

-- PRE.2.a | Commitment | Rights include respecting values, beliefs, cultural & spiritual needs
update public.shco_full_oes set achieve_tips = '["Develop a written SOP that requires staff to ask each patient at admission about any religious, cultural, or dietary preferences and document responses in the patient file; include a standardised ''special preferences'' field in the admission form.","Create a referral pathway in the SOP for spiritual care requests (e.g., access to a priest, maulvi, or pandit), define the turnaround time, and maintain a log of requests made and fulfilled for assessor review.","Train nursing and front-office staff through a dedicated session on cultural sensitivity and religious diversity using real case scenarios; maintain attendance sheets, training materials, and post-session acknowledgment forms.","Conduct quarterly audits of a sample of patient files to verify that cultural/spiritual preference fields are consistently filled; record audit findings and share corrective action plans with the nursing in-charge."]'::jsonb where oe_code = 'PRE.2.a';

-- PRE.2.b | Commitment | Rights include personal dignity and privacy during examination
update public.shco_full_oes set achieve_tips = '["Create an SOP mandating the use of screens or curtains during all physical examinations, dressing changes, and procedures; include a checklist item for this in the daily ward nursing round form and retain completed forms.","Train all clinical and paramedical staff to knock before entering, address patients by name, and avoid discussing patient conditions in public corridors; conduct an observed scenario exercise annually and record outcomes.","Assessors will walk through clinical areas and observe privacy practices — perform unannounced internal checks at least bi-monthly to confirm curtains are functional, screens are available, and staff follow dignity protocols; document findings.","Include a patient satisfaction question specifically about privacy and dignity; review scores monthly and present trend data at the quality committee meeting as evidence of a sustained improvement effort."]'::jsonb where oe_code = 'PRE.2.b';

-- PRE.2.c | Commitment | Rights include protection from neglect or abuse
update public.shco_full_oes set achieve_tips = '["Develop and display an anti-abuse and anti-neglect policy that defines what constitutes neglect or abuse in a healthcare setting; include a clear reporting mechanism and consequences for staff violation, and obtain staff acknowledgment signatures annually.","Create an SOP for mandatory reporting of suspected patient abuse or neglect — including who is responsible to report, to whom, and within what timeframe; maintain a log of all reports and their resolution as audit-ready records.","Train all staff — including housekeeping and security — to identify signs of patient neglect or abuse and report immediately without fear of retaliation; document training attendance and use a competency checklist for verification.","Conduct quarterly case reviews to confirm no patient has experienced delays in care or inadequate attention; identify cases flagged by nursing staff as ''at risk'' and document follow-up actions taken to prevent neglect."]'::jsonb where oe_code = 'PRE.2.c';

-- PRE.2.d | Core | Rights include confidentiality of patient information
update public.shco_full_oes set achieve_tips = '["Implement a written confidentiality policy covering physical records, verbal discussions, and digital data; require all staff to sign a confidentiality agreement at joining and annually thereafter, keeping signed copies in their personnel files.","Ensure patient records, files, and lab reports are never left open at unattended desks, corridors, or nurses'' stations; conduct monthly spot-checks and log any breach observed along with corrective action taken.","Assessors will interview staff to test confidentiality awareness — train staff to articulate the hospital''s confidentiality rules and demonstrate correct behaviour, such as lowering their voice when discussing patient details and locking file cabinets.","Review all cases where records were shared externally (e.g., with insurance companies, legal bodies) against a documented authorisation log; ensure written patient consent or legal authorisation exists for each disclosure and is filed in the patient record."]'::jsonb where oe_code = 'PRE.2.d';

-- PRE.2.e | Commitment | Rights include refusal of treatment
update public.shco_full_oes set achieve_tips = '["Develop an SOP that outlines the step-by-step process when a patient refuses treatment: inform the treating doctor, document the refusal with patient/family signature, explain consequences, and offer alternatives; keep the signed form in the patient file.","Create a standardised ''Refusal of Treatment'' form in the local language that captures the patient''s understanding of risks and the alternatives offered; ensure the form is signed by both the patient (or legal guardian) and the treating clinician.","Train clinical staff through a role-play scenario where a patient refuses a recommended procedure, so staff practise how to counsel respectfully without coercing, then document the outcome; retain training records and scenario assessment forms.","Conduct a monthly audit of inpatient files to check whether any refusal-of-treatment events occurred and were correctly documented with signed forms; report audit findings to the nursing supervisor and file corrective actions for gaps found."]'::jsonb where oe_code = 'PRE.2.e';

-- PRE.2.f | Commitment | Rights include seeking additional clinical opinion
update public.shco_full_oes set achieve_tips = '["Incorporate a clause in the Patient Rights charter explicitly stating the patient''s right to a second opinion; brief every admitted patient on this right at admission and document in the admission checklist that this briefing occurred.","Develop an SOP for facilitating a second opinion — including internal referral to a senior specialist or guidance on seeking external consultation — and maintain a log of all second-opinion requests and outcomes.","Train admitting doctors and nurses to respond positively when a patient or family requests a second opinion; use a staff training module that includes do''s and don''ts, and retain signed acknowledgment of training.","Quarterly, review a sample of patient files where second-opinion requests were noted; verify that each was facilitated without delay or objection and document the audit finding for quality committee review."]'::jsonb where oe_code = 'PRE.2.f';

-- PRE.2.g | Core | Rights include informed consent for blood, anaesthesia, surgery, research, high-risk procedures
update public.shco_full_oes set achieve_tips = '["Maintain a hospital-wide list of all procedures requiring mandatory informed consent (blood transfusion, anaesthesia, surgery, research, high-risk interventions); post this list in operation theatres, procedure rooms, and the nursing station and update it annually.","Assessors will review patient records — ensure that every surgical, anaesthesia, and blood transfusion file contains a completed and signed consent form before the procedure date; implement a pre-procedure checklist that blocks proceeding without signed consent.","Train all doctors and nurses involved in high-risk procedures on the legal and ethical requirement for prior informed consent; use case studies of consent failures as training examples and document attendance and competency assessment.","Conduct a monthly random audit of 10 files from each high-risk category to verify consent documentation is complete, signed, dated, and obtained before the procedure; record audit results and corrective actions in the quality register."]'::jsonb where oe_code = 'PRE.2.g';

-- PRE.2.h | Commitment | Rights include right to complain and how to voice a complaint
update public.shco_full_oes set achieve_tips = '["Display a clear, step-by-step complaints process poster at the OPD, reception, and each ward — including the complaint box location, Grievance Officer contact, and expected response timeline; update displays when the process changes.","Create an SOP for complaint management specifying receipt, acknowledgement within 24 hours, investigation, resolution, and communication of outcome to the complainant; maintain a complaints register with all these fields completed for each complaint.","Train admission and nursing staff to proactively inform patients at the time of admission about the complaint mechanism and to hand over a written guide; document this briefing in the admission checklist with patient signature.","Conduct quarterly reviews of the complaints register to verify every complaint was acknowledged and resolved within the defined timeframe; present summary statistics (volume, resolution rate, repeat complaints) to management and file the review report."]'::jsonb where oe_code = 'PRE.2.h';

-- PRE.2.i | Commitment | Rights include information on expected cost of treatment
update public.shco_full_oes set achieve_tips = '["Develop an SOP requiring the billing/admissions desk to provide every patient with a written cost estimate at the time of admission; include an acknowledgement column in the admission form where the patient signs to confirm they received the estimate.","Create standardised cost-estimate templates for the 10 most common procedures and diagnoses; keep these templates updated quarterly and make them readily available to admission staff for quick patient briefing.","Train admission and billing staff to explain cost estimates clearly, including items likely to vary (e.g., medicines, investigations); conduct a competency assessment annually and retain training records showing staff can handle common patient cost queries.","Review a monthly sample of patient admission files to confirm cost estimates were provided and signed; track the compliance rate as a quality indicator and present trend data to the finance and quality committee."]'::jsonb where oe_code = 'PRE.2.i';

-- PRE.2.j | Commitment | Rights include access to clinical records
update public.shco_full_oes set achieve_tips = '["Draft an SOP specifying the process for a patient or authorised family member to request access to or a copy of their clinical records, including the designated contact person, required identification, turnaround time, and applicable fees if any.","Inform every patient at admission of their right to access their records; include this in the patient rights briefing script and document the briefing in the admission checklist with patient/family signature.","Train medical records and nursing staff on how to handle record access requests in accordance with the SOP and applicable legal requirements; maintain a request log showing date received, date fulfilled, and any reasons for delay.","Conduct a quarterly audit of the record access request log to verify all requests were fulfilled within the defined timeline; present non-compliance cases to the quality committee with root-cause analysis and corrective actions."]'::jsonb where oe_code = 'PRE.2.j';

-- PRE.2.k | Commitment | Rights include info on treating doctor, care plan, progress, health needs
update public.shco_full_oes set achieve_tips = '["Introduce a daily ''patient information round'' where the assigned nurse verbally updates each inpatient on the name of their treating doctor, today''s care plan activities, and any significant changes; document this update on the nursing notes with time and signature.","Place a whiteboard or name card at each patient bedside showing the attending doctor''s name, ward nurse''s name, and today''s planned investigations or procedures; update it every shift and check for accuracy during supervisor rounds.","Train nursing staff using a structured communication checklist that covers what minimum information must be shared with patients every 24 hours; retain training records and verify compliance through spot audits of bedside information boards.","Conduct monthly audits of a sample of nursing notes to confirm daily patient information updates are documented; track the documentation compliance rate as a nursing quality indicator and share results at the monthly departmental meeting."]'::jsonb where oe_code = 'PRE.2.k';

-- PRE.2.l | Commitment | Patient determines what info shared with self and family
update public.shco_full_oes set achieve_tips = '["Add a structured ''Information Sharing Preference'' section to the admission form where the patient specifies who may receive clinical information about them (e.g., spouse, parent, no one other than self); file the completed form in the patient record.","Train nursing and clinical staff to check the patient''s information-sharing preference at the start of every shift before discussing health updates with visiting family members; include this check in the shift handover checklist.","Develop an SOP covering scenarios where the patient is unconscious or a minor, defining the default authorised information recipient and documentation requirements; train staff through role-play exercises on applying this SOP correctly.","Conduct quarterly audits of inpatient files to verify the information-sharing preference section is filled for all admissions; track completion rates and address gaps through targeted retraining of admission staff."]'::jsonb where oe_code = 'PRE.2.l';

-- PRE.2.m | Commitment | Patient/family explained proposed care including risks, alternatives, benefits
update public.shco_full_oes set achieve_tips = '["Develop a structured pre-procedure explanation checklist that the treating doctor completes and signs before any significant intervention, covering the procedure''s purpose, risks, alternatives, and benefits; attach the signed checklist to the patient file.","Train doctors and nurses to use simple, jargon-free language when explaining proposed care and to confirm patient understanding using the teach-back method (''Can you tell me in your own words what we discussed?''); document that teach-back was performed.","Create disease-specific or procedure-specific patient education leaflets in the local language describing the proposed treatment, common risks, and available alternatives; hand these to the patient and note delivery in the clinical record.","Quarterly, audit a sample of inpatient files to confirm that documentation of care explanation (including risks and alternatives) is present and complete before the procedure date; report findings and gaps to the clinical quality team."]'::jsonb where oe_code = 'PRE.2.m';

-- PRE.2.n | Commitment | Patient/family explained expected results and complications
update public.shco_full_oes set achieve_tips = '["Develop a post-procedure or post-treatment counselling SOP requiring the treating clinician to explain expected outcomes and potential complications within 24 hours of a procedure; document this discussion in the patient''s progress notes with clinician signature.","Create complication-awareness fact sheets for the 10 most frequently performed procedures; give these to patients after the procedure is explained and note in the clinical record that the handout was provided and discussed.","Train all doctors to document a structured ''expected outcome'' note in the patient file that captures what results were communicated, what complications were mentioned, and whether the patient''s questions were addressed; audit this note monthly.","Include a patient satisfaction survey question: ''Were you informed about what to expect and possible complications?'' Track monthly scores as a quality indicator and use low scores to trigger targeted retraining of the relevant clinical team."]'::jsonb where oe_code = 'PRE.2.n';

-- PRE.2.o | Achievement | Care plan prepared and modified in consultation with patient/family
update public.shco_full_oes set achieve_tips = '["Implement a policy requiring the treating doctor to discuss the initial care plan with the patient and/or family within 12 hours of admission; record this discussion in the clinical notes with the patient''s agreement or concerns documented.","Collect data monthly on how often care plan modifications are documented as occurring ''in consultation with the patient/family''; set a target (e.g., 90% of plan changes documented as discussed) and display trend data as before/after evidence.","Introduce a ''shared care plan'' section in the patient record where the patient or family can sign to confirm they were involved in planning decisions; track the proportion of files where this signature is present and report monthly to the medical committee.","Conduct patient interviews post-discharge (via phone or exit survey) specifically asking whether they felt involved in their care plan; compile responses quarterly to demonstrate measurable improvement in participatory care over successive assessment periods."]'::jsonb where oe_code = 'PRE.2.o';

-- PRE.2.p | Achievement | Multidisciplinary counselling provided when appropriate
update public.shco_full_oes set achieve_tips = '["Define in a written policy the clinical criteria that trigger a multidisciplinary counselling session (e.g., chronic disease, terminal diagnosis, major surgery, mental health concern); track how many eligible patients received MDT counselling each month versus how many were eligible.","Maintain a multidisciplinary counselling register recording patient name, date, disciplines represented (doctor, dietitian, physiotherapist, social worker, etc.), topics discussed, and patient response; present this register as outcome evidence during assessments.","Set a measurable target for MDT counselling uptake (e.g., 100% of cancer patients receive at least one session before discharge) and track actual achievement monthly; display a trend chart showing improvement from the baseline before this process was formalised.","Collect patient feedback specifically on MDT counselling sessions using a brief structured form; analyse responses quarterly to identify gaps in information provided or disciplines missing from sessions, and adjust staffing or scheduling accordingly."]'::jsonb where oe_code = 'PRE.2.p';

-- PRE.3.a | Core | Informed consent obtained as per statutory norms
update public.shco_full_oes set achieve_tips = '["Create a master list of all procedures, treatments, and situations that legally and ethically require informed consent under applicable Indian laws and NABH standards; circulate this list to all clinical departments and review it annually for updates.","Implement a hard-stop in the pre-procedure checklist — no procedure begins unless the consent form is present, completed, signed, and counter-signed by the clinician; train theatre and procedure room staff to enforce this checkpoint every time.","Assessors will cross-check patient files against the mandatory consent list — conduct monthly internal file audits verifying 100% consent form compliance for all applicable procedures; log audit results and escalate any gaps to the chief medical officer immediately.","Train all clinical staff on statutory consent requirements (e.g., MTP Act, Transplantation of Human Organs Act, requirements for minor patients) using a yearly competency session; retain attendance records, test scores, and copy of the training content."]'::jsonb where oe_code = 'PRE.3.a';

-- PRE.3.b | Core | Informed consent includes procedure info, risks, benefits, alternatives, performer identity, in understandable language
update public.shco_full_oes set achieve_tips = '["Redesign consent forms to include dedicated fields for: procedure name, specific risks, expected benefits, available alternatives, and name/designation of the person performing the procedure; have the hospital''s legal or quality team review the form annually.","Train all doctors to explain each consent form element to the patient verbally in the patient''s preferred language before requesting a signature; document in the form that verbal explanation was given and that the patient had the opportunity to ask questions.","Assessors will review consent forms and may interview patients to verify understanding — use the teach-back technique after consent counselling and record the patient''s verbatim confirmation in the clinical notes as evidence of comprehension.","Conduct monthly audits of 10 randomly selected consent forms to check that all mandatory fields are completed, the language is clear, and the performing clinician''s name is present; track compliance rate and address deficiencies through immediate departmental feedback."]'::jsonb where oe_code = 'PRE.3.b';

-- PRE.3.c | Commitment | Policy for who can give consent when patient cannot decide independently
update public.shco_full_oes set achieve_tips = '["Develop a written SOP defining the hierarchy of authorised consent givers when a patient lacks decision-making capacity (e.g., unconscious, minor, mentally incapacitated): specify spouse, parent, adult child, legal guardian in order of priority; get it approved by the medical committee.","Create a surrogate consent form that captures the relationship of the substitute decision-maker to the patient, the basis for acting as surrogate, and the specific consent being given; file this form in the patient record and train admission staff to initiate it immediately when needed.","Train all nurses and doctors to identify when a patient lacks capacity and to activate the surrogate consent pathway without delay; conduct an annual scenario-based training session and maintain attendance records and competency assessment results.","Audit a quarterly sample of files where surrogate consent was used; verify that the authority of the surrogate is documented, the correct form was used, and the clinician''s assessment of the patient''s incapacity is recorded; present findings to the quality committee."]'::jsonb where oe_code = 'PRE.3.c';

-- PRE.3.d | Core | Informed consent taken by the person performing the procedure
update public.shco_full_oes set achieve_tips = '["Update all consent forms to include a mandatory field for the signature and printed name of the performing clinician, distinct from a witness signature; make this a non-negotiable pre-procedure checklist item in theatres and procedure rooms.","Circulate a written directive from the medical superintendent clearly prohibiting delegation of the informed consent explanation and signature to a non-performing staff member (e.g., a nurse or junior doctor collecting blanket signatures); attach this directive to the SOP.","Assessors will interview patients about who explained the consent and ask staff to demonstrate their understanding of this requirement — train all doctors through an orientation module to reinforce that they personally must explain and sign; keep training records.","Conduct monthly random audits of completed consent forms to verify the performer''s name is present and matches the actual operating or performing clinician documented in the procedure notes; record discrepancies and take immediate corrective action."]'::jsonb where oe_code = 'PRE.3.d';

-- PRE.4.a | Core | Patient/family educated in language and format they can understand
update public.shco_full_oes set achieve_tips = '["Identify the top five languages spoken by your patient population and ensure key patient education materials (rights charter, consent forms, discharge instructions) are available in each; document the translation and approval process for each language version.","Train nurses to assess literacy and language preference at admission using a standardised two-question screen and record the preferred communication mode (verbal, written, pictorial) in the patient file; tailor all education interactions accordingly.","Assessors will observe patient education interactions and may interview patients — have nurses demonstrate using pictorial leaflets or models when patients are illiterate, and document in the nursing notes that education was delivered in the patient''s preferred format.","Audit monthly a sample of patient education records to verify that the language used and format chosen are documented; track the proportion of files where this field is completed and present the compliance rate at the monthly quality meeting."]'::jsonb where oe_code = 'PRE.4.a';

-- PRE.4.b | Commitment | Patient/family educated on safe medication use and side effects
update public.shco_full_oes set achieve_tips = '["Develop a structured medication counselling SOP requiring the dispensing pharmacist or nurse to counsel every patient on each new medication''s purpose, correct dose, frequency, and key side effects; create a medication counselling checklist to be signed by the counsellor and filed in the record.","Prepare medication information cards for the 20 most commonly prescribed drugs in the hospital listing the drug name, key side effects, storage conditions, and what to do in an emergency; give these cards to patients alongside their medicines.","Train pharmacists and nurses on medication counselling using a competency-based programme; conduct annual observed structured assessments where the trainer watches a live counselling session and scores it against a checklist; retain score sheets.","Monthly, audit a sample of discharge files for evidence of medication counselling documentation; track the percentage of files with completed counselling checklists and present trend data at the clinical quality committee meeting."]'::jsonb where oe_code = 'PRE.4.b';

-- PRE.4.c | Commitment | Patient/family educated on food-drug interaction, diet, nutrition, immunisations
update public.shco_full_oes set achieve_tips = '["Develop disease-specific diet and food-drug interaction education sheets for common conditions managed in the hospital (e.g., diabetes, hypertension, TB, anaemia); have these reviewed by the dietitian and approved by the medical committee before use.","Create an SOP requiring the dietitian or nurse to provide food-drug interaction counselling for all patients on anticoagulants, antiepileptics, antihypertensives, or antibiotics; document the counselling session in the patient file with the counsellor''s signature.","Train nursing staff and pharmacists on the most clinically significant food-drug interactions relevant to the hospital''s case mix; conduct annual training with a competency checklist and retain attendance and assessment records for assessor review.","Include immunisation status review in the admission checklist for paediatric and postnatal patients; document that immunisation advice was provided, with the date and responsible staff member recorded in the clinical notes."]'::jsonb where oe_code = 'PRE.4.c';

-- PRE.4.d | Commitment | Patient/family educated on disease process, complications, prevention strategies
update public.shco_full_oes set achieve_tips = '["Create disease-specific patient education modules for the top 10 diagnoses in the hospital, covering what the disease is, how it progresses, potential complications, and practical prevention steps; approve these through the medical committee and update them annually.","Implement an SOP requiring the treating doctor or nurse to provide structured disease education at least once during every inpatient stay and to document the session — topic covered, patient''s understanding, and questions raised — in the clinical notes.","Train nursing staff to deliver disease education using a teach-back approach; conduct annual competency assessments with a structured observation tool and retain the completed assessment forms as evidence of staff capability.","Develop a disease education checklist for discharge; ensure every patient leaves with a written summary of their diagnosis, key warning signs of complications, and when to seek emergency care; document in the discharge summary that the checklist was completed and handed over."]'::jsonb where oe_code = 'PRE.4.d';

-- PRE.4.e | Commitment | Patient/family educated on preventing healthcare associated infections
update public.shco_full_oes set achieve_tips = '["Develop a patient-facing hand hygiene education card with illustrations showing the 6-step hand wash technique; distribute it to every admitted patient within 2 hours of admission and ask nursing staff to demonstrate the technique at the bedside; document delivery in the nursing notes.","Create an SOP requiring nurses to educate patients and visitors about cough etiquette, correct mask use, and not touching wound dressings; include this education in the admission nursing checklist and retain completed checklists in patient files.","Display HAI prevention posters (hand hygiene, respiratory hygiene, safe disposal of sharps) in all patient wards and OPD waiting areas in local languages; photograph displays with date stamps and include them in the infection control audit records.","Conduct quarterly patient feedback surveys asking whether they were educated about infection prevention during their stay; track the ''yes'' response rate as an HAI education indicator and present trend data at the infection control committee meeting."]'::jsonb where oe_code = 'PRE.4.e';

-- PRE.4.f | Excellence | Communication with patients/families done effectively
update public.shco_full_oes set achieve_tips = '["Introduce a structured SBAR (Situation-Background-Assessment-Recommendation) or equivalent communication framework for all clinician-to-patient handovers and family briefings; train staff on its use and verify application through monthly supervisor observations documented on a checklist.","Conduct an annual patient communication satisfaction survey with questions specifically targeting clarity, compassion, and responsiveness; analyse results by department and share findings with department heads to drive targeted communication improvement plans.","Set up a designated ''Family Communication Area'' — a private, quiet space where doctors can speak with families without interruption; track utilisation monthly as an indicator of structured family communication practice, and include it in the quality dashboard.","Establish a daily scheduled time (e.g., 5–6 PM) for ward doctors to meet with families of inpatients; record attendance and topics discussed in the ward communication log; review compliance monthly and address wards where this practice is inconsistent."]'::jsonb where oe_code = 'PRE.4.f';

-- PRE.5.a | Core | Patients made aware of pricing policy in OPD, emergency, ICU, inpatient settings
update public.shco_full_oes set achieve_tips = '["Display the hospital''s pricing policy notice (covering OPD, emergency, ICU, and inpatient charges) prominently at each of these four entry points; ensure the display is in the local language and at eye level; document display locations in the facility audit checklist.","Train admission and billing staff to verbally explain the pricing structure applicable to each care setting at the point of patient registration; include a pricing policy briefing script in the staff induction manual and retain training records.","Assessors will interview patients about cost awareness — brief every patient and family at admission about applicable charges for their setting; have them sign an acknowledgement in the admission form confirming they received this information.","Conduct monthly audits of admission records to verify that the pricing-awareness acknowledgement field is completed for every admission; track compliance rates and share results at the billing department''s monthly review meeting with corrective actions documented."]'::jsonb where oe_code = 'PRE.5.a';

-- PRE.5.b | Commitment | Tariff list available to patients
update public.shco_full_oes set achieve_tips = '["Place a current, dated tariff list at the OPD reception, billing counter, and ward nursing station in a clearly visible format; designate one staff member per shift as responsible for ensuring the tariff list is available and up to date at all times.","Develop an SOP requiring the tariff list to be reviewed and reprinted every time prices change, with the revision date printed on every copy; maintain a tariff list revision log showing old and new price, date of change, and approving authority.","Train billing and front-desk staff to proactively offer the tariff list to patients who ask about costs and to explain items if needed; include this expectation in the customer service training module and verify through quarterly mystery-patient exercises.","Conduct monthly checks to confirm the tariff list is physically present at all three mandatory locations; record the check result and any corrective action in the facility inspection register, and escalate repeated non-compliance to hospital management."]'::jsonb where oe_code = 'PRE.5.b';

-- PRE.5.c | Commitment | Patient/family explained expected costs
update public.shco_full_oes set achieve_tips = '["Develop a cost-estimate SOP requiring the billing team to generate and share a written estimated cost breakdown with every patient at or before admission; include an acknowledgement signature block in the billing form for the patient to confirm they received and understood the estimate.","Create standardised cost-estimate templates for the 20 most common DRGs or procedures in the hospital; update these templates quarterly to reflect current prices and make them immediately accessible to billing staff on the intranet or physical folder.","Train billing counsellors to walk patients through the estimate line by line, highlighting which items are fixed versus variable; include role-play practice in annual training and retain competency assessment records showing staff can handle cost queries confidently.","Monthly, audit a sample of billing records to verify cost-estimate forms are present, signed, and provided before the procedure or admission; track the compliance rate and present findings at the finance committee''s monthly meeting."]'::jsonb where oe_code = 'PRE.5.c';

-- PRE.5.d | Achievement | Patient/family informed of financial implications when care plan changes
update public.shco_full_oes set achieve_tips = '["Implement a policy requiring the treating doctor to notify the billing team within 2 hours whenever the care plan changes significantly (e.g., escalation to ICU, addition of surgery, change in drug regimen); the billing team then provides a revised cost estimate to the family within the next hour.","Maintain a ''care plan change'' log that records the date of change, nature of change, date the family was informed of financial implications, and family signature of acknowledgement; track the proportion of care plan changes where family was informed within the defined time frame.","Measure monthly the percentage of care plan changes where financial impact was communicated to the family before the change was implemented; set a target (e.g., 90%) and display before/after trend data showing improvement since the policy was introduced as evidence of achievement.","Collect discharge patient feedback specifically asking: ''Were you informed of cost changes when your treatment plan changed?'' Compile responses quarterly, track the approval rate as an outcome metric, and present improvement data to the billing and clinical quality committees."]'::jsonb where oe_code = 'PRE.5.d';

-- PRE.6.a | Commitment | Mechanism to capture patient feedback including satisfaction
update public.shco_full_oes set achieve_tips = '["Design a validated patient satisfaction survey with at least 10 questions covering clinical care, nursing, food, billing, and cleanliness; administer it to every inpatient at discharge and to a sample of OPD patients monthly; maintain completed survey forms as records.","Develop an SOP for the feedback collection process specifying: who administers the survey, in which language, by which method (paper/digital/verbal for illiterate patients), and where forms are stored; train designated staff and retain their training records.","Establish a monthly feedback analysis meeting where the quality team reviews satisfaction scores by department, identifies outlier departments, and assigns corrective actions with owners and deadlines; file meeting minutes as evidence of systematic use of patient feedback.","Display monthly patient satisfaction results on a notice board or digital screen in a public area of the hospital; include the current score, last month''s score, and a brief note on what action was taken based on feedback; update this display every month without fail."]'::jsonb where oe_code = 'PRE.6.a';

-- PRE.6.b | Excellence | Mechanism to capture patient experience
update public.shco_full_oes set achieve_tips = '["Go beyond satisfaction scores by capturing qualitative patient experience using structured patient narrative interviews or open-ended written feedback forms; aim to conduct at least 5 narrative interviews per month and record verbatim quotes for quality improvement use.","Implement a real-time experience capture tool such as a bedside feedback terminal, QR-code-linked form, or daily nurse-led brief structured conversation; document each interaction in a patient experience log with date, ward, and any issue flagged.","Analyse patient experience data monthly using thematic categorisation (e.g., communication, empathy, environment, wait times); prepare a quarterly patient experience report highlighting recurring themes and improvement actions taken; file reports for assessor review.","Benchmark patient experience scores against your own previous quarters to demonstrate a progressive improvement trend; display a multi-quarter trend chart in the quality office and present it at the hospital''s quality committee meeting as evidence of sustained excellence."]'::jsonb where oe_code = 'PRE.6.b';

-- PRE.6.c | Core | Organisation redresses complaints per defined mechanism; patients made aware of complaint process
update public.shco_full_oes set achieve_tips = '["Appoint a designated Grievance Redressal Officer (GRO) by name and display their name, photograph, and contact number prominently at OPD, reception, and all wards; ensure every patient is told the GRO''s name at admission and document this in the admission checklist.","Maintain a complaints register with columns for: complaint date, complainant name, nature of complaint, date acknowledged, date resolved, resolution details, and complainant''s satisfaction with resolution; keep this register updated daily and available for immediate assessor review.","Assessors will interview patients and staff about the complaints process — train all patient-facing staff to explain in two minutes exactly how a patient can lodge a complaint, who handles it, and how long resolution takes; validate this through annual role-play assessments.","Conduct quarterly reviews of the complaints register to verify every complaint was acknowledged within 24 hours and resolved within the defined timeframe; calculate the resolution compliance rate and escalate overdue complaints to hospital management with a written explanation."]'::jsonb where oe_code = 'PRE.6.c';

-- PRE.6.d | Achievement | Feedback and complaints reviewed/analysed within defined timeframe; CAPA taken
update public.shco_full_oes set achieve_tips = '["Define in the complaints SOP specific analysis timeframes: individual complaints reviewed within 48 hours, aggregate analysis monthly, trend analysis quarterly; document each analysis in the quality register with the date completed and the analyst''s name.","Perform root-cause analysis for all repeat complaints and any serious complaint; document a formal CAPA plan with corrective action, preventive measure, responsible person, and target closure date; track open CAPA items on a live register updated weekly.","Measure monthly the percentage of complaints resolved within the defined timeframe and the percentage of CAPA actions closed on time; display a trend chart showing both metrics over the past 12 months as before/after evidence of a functioning quality improvement cycle.","Present the quarterly complaint analysis report to the hospital''s quality or management committee meeting; include a summary of root causes identified, actions taken, and impact measured; retain signed meeting minutes as documentary evidence of leadership engagement with patient feedback outcomes."]'::jsonb where oe_code = 'PRE.6.d';
