-- FMS Chapter: Facility Management and Safety
-- 29 OEs | Generated tips for SHCO Full Accreditation

update public.shco_full_oes set achieve_tips = '["Conduct a physical walkthrough of all departments to verify that available space matches the services being delivered, and document any gaps for management review.","Develop a space utilisation checklist covering OPD, IPD, procedure rooms, and support areas, and update it whenever new services are added or reorganised.","Prepare a written SOP that defines minimum space requirements for each service category, and train the facility manager to apply it during any expansion planning.","Maintain a file of approved layout plans alongside current usage maps so assessors can instantly verify that facilities remain appropriate to declared services."]'::jsonb where oe_code = 'FMS.1.a';

update public.shco_full_oes set achieve_tips = '["Retrieve the original architectural drawings from the builder or architect and store verified copies in a dedicated statutory-compliance folder accessible to facility management.","Appoint a responsible staff member to update drawings within 30 days of any structural change, renovation, or addition of utility lines, and record the date of each revision.","Create an SOP for maintaining as-built drawings that outlines who initiates updates, who approves them, and where the master copies are stored.","Keep a log of all drawing revisions with dates and the nature of the change so assessors can confirm that records are current and traceable."]'::jsonb where oe_code = 'FMS.1.b';

update public.shco_full_oes set achieve_tips = '["Walk every entry point, corridor, and ward and place clear directional signs at each decision point; use pictograms alongside text to serve patients who cannot read.","Conduct a monthly signage audit using a checklist that covers both internal department signs and external facility identification boards, and record findings in a register.","Ensure all signs are in at least the local language and English, and that sign heights and font sizes meet accessibility standards for visually impaired visitors.","Train housekeeping and security staff to immediately report any damaged, faded, or missing signs so replacements are made within 48 hours; keep replacement records as evidence for assessors."]'::jsonb where oe_code = 'FMS.1.c';

update public.shco_full_oes set achieve_tips = '["Install a 24-hour flow meter or pressure gauge log for the main water supply and designate a staff member to record readings at the start of each shift.","Keep an electricity supply log that captures any interruptions, their duration, and the immediate corrective action taken, and review it weekly with the facility manager.","Test all water taps, RO systems, and overhead tank levels daily, and document results in a utility checklist signed by the duty engineer.","Train ward nurses and housekeeping staff to report water or power failures immediately through a defined escalation channel, and ensure assessors can observe the functioning supply and review the daily logs."]'::jsonb where oe_code = 'FMS.1.d';

update public.shco_full_oes set achieve_tips = '["Install a diesel generator with automatic changeover and a water storage tank of sufficient capacity, and document their specifications in the facility infrastructure register.","Write a formal SOP specifying the testing schedule for backup electricity (at least monthly load test) and backup water (quarterly tank flush and fill test), and record every test in a dated log.","Assign a named technician responsible for each backup system, train them on startup and shutdown procedures, and maintain training records as evidence.","Display the backup system testing schedule on the engineering notice board and keep test result records for at least two years so assessors can verify consistent functioning."]'::jsonb where oe_code = 'FMS.1.e';

update public.shco_full_oes set achieve_tips = '["Audit current energy consumption by reviewing electricity bills for the past 12 months and identify the top three areas of high usage for targeted improvement.","Install energy-saving LED lighting in at least one high-traffic area and document the initiative with before-and-after consumption data to demonstrate measurable impact.","Start a simple waste-segregation initiative — paper, plastic, and general waste bins with clear labels — and brief all staff during morning meetings to build participation.","Create a green initiatives register where each new energy or environment-friendly measure is recorded with the date started, responsible person, and outcome observed."]'::jsonb where oe_code = 'FMS.1.f';

update public.shco_full_oes set achieve_tips = '["Prepare a comprehensive inventory of all patient-safety devices — bed rails, call bells, anti-slip mats, grab rails, restraints — and map their locations across every ward and procedure area.","Establish a monthly inspection checklist for each safety device, sign off each check with the inspector''s name and date, and retain the completed checklists in a safety register for assessor review.","Set up a reported-defect log so any staff member who finds a faulty safety device can record it; require the facility team to resolve and close each entry within 24 hours with documented corrective action.","Conduct periodic unannounced spot-checks of patient areas so assessors can observe safety devices in place; brief staff during ward rounds to explain the purpose and correct use of each device."]'::jsonb where oe_code = 'FMS.2.a';

update public.shco_full_oes set achieve_tips = '["Map every patient-access route in the facility and identify locations where ramps, handrails, wider doorways, or accessible toilets are required, then prioritise installation based on patient footfall.","Write an SOP for receiving and assisting differently-abled patients that covers wheelchair allocation, escort procedures, and accessible parking, and train front-desk and security staff to follow it consistently.","Display the international symbol of access at all adapted entrances, parking bays, and accessible washrooms, and verify signage is visible and unobstructed during monthly facility rounds.","Maintain a register of all differently-abled facilities — ramps, tactile floors, hearing loops, Braille signage — with their installation dates and last inspection dates so records are audit-ready."]'::jsonb where oe_code = 'FMS.2.b';

update public.shco_full_oes set achieve_tips = '["Prepare a written security plan that identifies high-risk zones — ICU, labour room, pharmacy, cash counter, server room — and defines who is authorised to enter each zone with what form of identification.","Install access-control measures such as key-coded doors, visitor passes, or security guard posts at each restricted area, and maintain a daily access log for each high-security zone.","Create a measurable outcome register that tracks the number of unauthorised access incidents per month, reviews trends quarterly, and records corrective actions taken to reduce recurrence.","Conduct quarterly security briefings with all staff covering their responsibilities for controlling access, and keep attendance records and briefing notes so assessors can verify staff awareness."]'::jsonb where oe_code = 'FMS.2.c';

update public.shco_full_oes set achieve_tips = '["Schedule a formal facility safety inspection round on the first Monday of every month and document the route, findings, and actions in a signed inspection register.","Use a standardised inspection checklist covering flooring conditions, lighting adequacy, sharps disposal bins, fire extinguisher positions, and emergency exit clearance to ensure nothing is missed each round.","Assign a cross-functional team — nursing, housekeeping, engineering — to participate in each monthly round so safety issues are identified from multiple perspectives and recorded collectively.","Ensure that deficiencies noted during rounds have corrective action entries with a deadline and responsible person; close each entry with a dated sign-off so assessors can trace compliance to the inspection findings."]'::jsonb where oe_code = 'FMS.2.d';

update public.shco_full_oes set achieve_tips = '["Engage a licensed electrical engineer or authorised agency to conduct a formal electrical safety audit at least once a year and retain the written audit report with findings and recommendations.","Maintain a corrective action tracker that lists each electrical deficiency identified during the audit alongside the target closure date, responsible engineer, and actual date of resolution.","Track measurable outcomes such as number of electrical faults reported per quarter and reduction in tripping events, and review the trend with management to demonstrate improvement over time.","Keep all electrical test certificates — earthing tests, insulation resistance tests, load tests — in a dedicated file with dates so assessors can verify that audits are current and deficiencies resolved."]'::jsonb where oe_code = 'FMS.2.e';

update public.shco_full_oes set achieve_tips = '["Develop an SOP for identifying items no longer in use — expired consumables, broken furniture, obsolete equipment — and specify how each category should be labelled, stored temporarily, and disposed of.","Create a disposal request form that any department can raise when surplus or condemned material is identified; route it through the purchase or biomedical team for authorisation before removal.","Train housekeeping supervisors and department in-charges on the identification procedure during a dedicated session, and maintain a training attendance register as evidence.","Keep a disposal log recording the item description, quantity, date removed, disposal method, and approving authority so the complete audit trail is available for assessors."]'::jsonb where oe_code = 'FMS.2.f';

update public.shco_full_oes set achieve_tips = '["Prepare a labelled hazardous materials inventory covering disinfectants, flammable cleaning agents, cytotoxic drugs, laboratory chemicals, and medical gases, and post it in each area where these materials are stored or used.","Write handling and storage SOPs for each category of hazardous material specifying personal protective equipment required, storage conditions, spill response steps, and disposal method; make these accessible at the point of use.","Train relevant staff — housekeeping, laboratory, pharmacy, nursing — on hazardous material handling during induction and annually thereafter, and maintain signed training records for assessor review.","Conduct periodic observations of staff handling hazardous materials and record findings; assessors will observe actual practice, so ensure staff can demonstrate correct PPE use and spill-kit location during any unannounced check."]'::jsonb where oe_code = 'FMS.2.g';

update public.shco_full_oes set achieve_tips = '["Develop a written equipment procurement policy aligned with the clinical services offered, specifying criteria for selection such as safety features, serviceability, and vendor support before any purchase is approved.","Prepare a five-year equipment plan linked to the strategic growth plan, reviewed annually by management, and keep signed review minutes as evidence of systematic planning.","Write an SOP for the equipment acquisition process covering needs assessment, technical specification preparation, vendor evaluation, and final approval authority, and train the biomedical team to follow it consistently.","Maintain a procurement file for each major equipment purchase containing the justification, specification, vendor comparison, and approval sign-off so the full planning trail is audit-ready."]'::jsonb where oe_code = 'FMS.3.a';

update public.shco_full_oes set achieve_tips = '["Create a master equipment inventory register covering all medical and support service equipment with each item''s unique asset code, department location, purchase date, make, model, and current status.","Establish equipment-specific logbooks — either physical or digital — for each asset where every use, cleaning, breakdown, and service event is entered with date and staff name.","Write an SOP defining who is responsible for updating the inventory when new equipment arrives, when items are condemned, or when assets are relocated between departments.","Conduct a quarterly inventory verification where the physical count is matched against the register; document discrepancies and resolution steps so assessors can confirm that logs are accurate and current."]'::jsonb where oe_code = 'FMS.3.b';

update public.shco_full_oes set achieve_tips = '["Develop a written preventive maintenance (PM) schedule for every piece of medical and support service equipment, specifying the frequency, tasks to be performed, and responsible technician.","Implement a breakdown maintenance log where any equipment failure is recorded immediately with the date, nature of fault, downtime start time, and service team notified, and closed with the repair date and action taken.","Train biomedical technicians and department operators on daily pre-use checks for their equipment, and ensure signed daily check sheets are retained in the equipment logbook for assessor review.","Monitor PM compliance monthly — track how many scheduled PMs were completed on time versus deferred — and review the rate with management so the plan is demonstrably implemented."]'::jsonb where oe_code = 'FMS.3.c';

update public.shco_full_oes set achieve_tips = '["Prepare a calibration schedule listing every medical device requiring periodic calibration, the calibration frequency, the responsible agency, and the due date for the next calibration.","After each calibration or inspection, affix a sticker on the equipment showing the calibration date and next due date, and file the calibration certificate in the equipment folder.","Write an SOP for managing equipment found to be out of calibration — immediate removal from service, tagging, investigation, recalibration, and reintroduction — and train the biomedical team to follow it.","Maintain a calibration compliance tracker showing percentage of devices calibrated on schedule each quarter; review with management and keep records so assessors can verify systematic inspection."]'::jsonb where oe_code = 'FMS.3.d';

update public.shco_full_oes set achieve_tips = '["Prepare job descriptions for all biomedical and engineering staff that specify required qualifications and training for operating and maintaining equipment assigned to their role.","Maintain individual training records for each technician and operator documenting equipment-specific competency training, on-the-job assessments, and refresher sessions with dates.","Write an SOP requiring that only trained and authorised personnel operate designated equipment, and implement a visible authorisation system — signed competency card or logbook entry — for each equipment-operator combination.","Schedule annual refresher training for all equipment operators, especially when new models are procured or after any near-miss event, and keep signed attendance sheets so assessors can confirm ongoing competence."]'::jsonb where oe_code = 'FMS.3.e';

update public.shco_full_oes set achieve_tips = '["Subscribe to the manufacturer''s and regulatory authority''s hazard alert and recall notification channels, and designate a responsible officer to review all incoming notices and initiate action within a defined timeframe.","Maintain an adverse event register specifically for medical equipment incidents — near-misses, patient injuries, device malfunctions — with investigation findings and corrective actions closed out with dates.","When a recall notice is received, immediately check the inventory register to determine if the affected device is in use, quarantine it if required, and document the action taken in the recall tracking log.","Review the adverse event and recall register monthly with the biomedical committee, track trends in equipment-related incidents, and retain review minutes so assessors can confirm that monitoring is active and systematic."]'::jsonb where oe_code = 'FMS.3.f';

update public.shco_full_oes set achieve_tips = '["Define critical equipment for your facility — ventilators, anaesthesia machines, ECG monitors, infusion pumps — and set acceptable maximum downtime targets for each category in a written policy.","Implement a downtime tracking log for every breakdown of critical equipment recording the exact time of failure report, time of technician response, time of repair completion, and total downtime in hours.","Review downtime data monthly to calculate average response and resolution times; compare against targets and implement corrective action — such as spare parts stocking or vendor SLA revision — when targets are missed.","Keep cumulative downtime reports for each critical equipment item accessible in the biomedical office so assessors can verify that monitoring is continuous and that corrective actions are data-driven."]'::jsonb where oe_code = 'FMS.3.g';

update public.shco_full_oes set achieve_tips = '["Draft a comprehensive medical gas SOP covering approved suppliers, purchase order procedures, receipt inspection, cylinder storage rules, distribution records, and reorder trigger levels; get it approved by management.","Develop a cylinder tracking log that records each cylinder''s unique number, gas type, date received, location assigned, date emptied, and date returned to supplier to maintain a complete audit trail.","Train all staff involved in handling medical gases — store, ward nurses, technicians — on the SOP during induction and annually thereafter, and keep signed training records readily available for assessors.","Conduct quarterly internal audits of medical gas storage areas against the SOP checklist, record findings and corrective actions, and file audit reports so compliance history is visible."]'::jsonb where oe_code = 'FMS.4.a';

update public.shco_full_oes set achieve_tips = '["Label every medical gas cylinder and pipeline outlet clearly with the gas name and colour code, and train staff never to use an unlabelled or unclear cylinder under any circumstances.","Ensure cylinders are stored upright, secured with chains or brackets, and segregated by gas type and status — full versus empty — with clear zone markings on the floor of the storage area.","Display the SOP for safe medical gas handling at every storage point and near every bedside terminal, and ensure staff can demonstrate correct connection and leak-check procedures during assessor observations.","Conduct monthly checks of all cylinder valves, connections, and pressure gauges; document results in a safety inspection register and take immediate corrective action for any leaks or pressure anomalies found."]'::jsonb where oe_code = 'FMS.4.b';

update public.shco_full_oes set achieve_tips = '["Identify the alternate or backup source for each medical gas, vacuum line, and compressed air system — spare cylinders, portable compressors, backup manifold — and document their specifications and locations.","Write a formal testing protocol specifying how often each backup system is tested, who conducts the test, what parameters are verified, and how results are recorded; schedule tests at least quarterly.","Train the engineering team to perform failover tests safely, including simulation of main supply failure and confirmation that the backup source activates within the required timeframe; keep signed test records.","Maintain a backup-system test log with each test date, tester name, result, and any corrective action taken so assessors can verify regular testing and readiness."]'::jsonb where oe_code = 'FMS.4.c';

update public.shco_full_oes set achieve_tips = '["Prepare a written operations and maintenance plan for the piped medical gas, compressed air, and vacuum installation covering daily checks, monthly inspections, annual service, and pressure testing schedules.","Implement a daily line-pressure monitoring log where the duty engineer records pipeline pressures for each gas at the manifold and at key terminal points, signing off each shift entry.","Engage a qualified piped medical gas engineer for annual inspection and testing, retain the technical report with findings, and track all identified deficiencies to closure with dated records.","Write an SOP for responding to pipeline pressure failures — isolation steps, backup activation, patient safety actions, and notification chain — and ensure all relevant staff are trained and can demonstrate the steps."]'::jsonb where oe_code = 'FMS.4.d';

update public.shco_full_oes set achieve_tips = '["Install fire detection devices — smoke detectors, heat sensors, manual call points — in all departments, corridors, and utility areas, and verify their positions meet the fire safety layout plan for the building.","Maintain a fire emergency response plan document that defines the R-A-C-E procedure (Rescue, Alarm, Contain, Extinguish or Evacuate) and post laminated quick-reference cards at each nursing station and exit.","Ensure first-aid firefighting equipment — extinguishers and hose reels — is placed at all designated points, inspected monthly, and tagged with the last inspection date so staff and assessors can see compliance at a glance.","Train all staff — including housekeeping and security — in fire response during induction and annually; assessors will observe and interview staff, so every team member should be able to explain their role in an emergency."]'::jsonb where oe_code = 'FMS.5.a';

update public.shco_full_oes set achieve_tips = '["Draw a clear floor plan for each floor showing all emergency exits, evacuation assembly points, fire extinguisher locations, and escape routes; laminate and display the plan at the entrance of every ward and corridor.","Write an SOP detailing the evacuation sequence for each zone, the staff responsible for leading patients, the assembly point for each ward, and the roll-call procedure to account for all occupants after evacuation.","Conduct a staff briefing when new employees join, using the displayed exit plan as a visual aid, and document attendance; ensure all staff can locate the nearest exit and assembly point from their usual work area.","Audit the visibility and accuracy of all posted exit plans monthly; replace damaged or outdated plans immediately and record the audit date and auditor name in the facility safety register."]'::jsonb where oe_code = 'FMS.5.b';

update public.shco_full_oes set achieve_tips = '["Schedule two mock drills per year — one announced and one unannounced — covering fire and at least one non-fire emergency scenario such as a medical gas leak or structural damage, and record dates in the annual safety calendar.","Prepare a mock drill report template that captures time of alarm, staff response time, evacuation completion time, headcount result, and debrief findings; complete a report for every drill conducted.","Conduct a structured debrief within 24 hours of each drill involving all participating staff to identify gaps in response and update the emergency plan accordingly, documenting changes made as a result.","Maintain a mock drill register with dates, scenarios used, participants, drill duration, debrief summary, and improvement actions so assessors can confirm that drills are conducted, evaluated, and acted upon."]'::jsonb where oe_code = 'FMS.5.c';

update public.shco_full_oes set achieve_tips = '["Prepare an inventory of all fire-related equipment — extinguishers, hose reels, sprinkler heads, smoke detectors, manual call points, fire doors — and map each item''s location in the facility.","Write a maintenance schedule specifying monthly visual checks, six-monthly servicing, and annual pressure testing for each equipment type, and assign responsibility to a named engineer or contracted vendor.","After every maintenance or service event, update the equipment tag with the service date and next due date, and file the service certificate in the fire safety maintenance folder.","Conduct an annual fire equipment compliance review comparing the inventory against the maintenance log to confirm all items are serviced on schedule; document the review outcome and any gaps addressed for assessor verification."]'::jsonb where oe_code = 'FMS.5.d';

update public.shco_full_oes set achieve_tips = '["Develop a written service continuity plan that identifies the minimum services the facility must maintain during and after an emergency — critical care, emergency surgery, essential medications — and assigns responsible staff for each.","Define escalation contacts, backup service providers, and mutual aid agreements with nearby hospitals in the continuity plan, and test contact lists every six months to confirm they are current.","Map critical utilities — electricity, water, oxygen, data systems — against the continuity plan and specify the backup arrangements and maximum acceptable downtime for each, recording the plan in a retrievable document.","Review and update the service continuity plan annually or after any actual emergency, document the review with management sign-off, and keep previous versions archived so assessors can trace the improvement history."]'::jsonb where oe_code = 'FMS.5.e';
