-- COP Chapter: Care of Patients
-- 82 OEs with 4 actionable "How to Achieve" tips each

update public.shco_full_oes set achieve_tips = '["Implement a two-identifier wristband system (name + date of birth or MR number) and verify both identifiers before every procedure, medication administration, and sample collection.","Train all nursing and clinical staff to verbally confirm two patient identifiers at each care handover point and document the verification in the patient record at every shift.","Conduct unannounced spot-checks by the nursing supervisor to observe whether staff consistently use two identifiers before performing any clinical task, and record observations in the audit log.","During assessor visits, demonstrate identification records in patient files, walk assessors through the wristband verification workflow, and allow staff interviews to confirm daily practice."]'::jsonb where oe_code = 'COP.1.a';

update public.shco_full_oes set achieve_tips = '["Compile a master list of all applicable laws and regulations governing patient care (PCPNDT, MTP Act, Bio-Medical Waste Rules, etc.) and assign a compliance officer to track amendments and update SOPs accordingly.","Create an SOP for each regulatory requirement and display a compliance calendar in the nursing station that flags upcoming renewal deadlines for licenses and registrations.","Train all department heads in relevant statutory obligations during induction and annually thereafter, maintaining signed attendance records as audit-ready evidence.","Conduct a quarterly internal compliance audit comparing actual practice against regulatory requirements, document findings, and record corrective actions taken within defined timelines."]'::jsonb where oe_code = 'COP.1.b';

update public.shco_full_oes set achieve_tips = '["Identify the top 10 clinical conditions treated in the hospital, adopt national or international evidence-based guidelines for each (e.g., WHO, IAP, MoHFW), and keep printed or digital copies accessible in relevant departments.","Form a clinical protocol committee that meets quarterly to review, update, and formally approve protocols, documenting meeting minutes and version-controlled protocol registers.","Measure adherence to each protocol monthly using clinical audit tools, display compliance rates on departmental dashboards, and link findings to clinical improvement plans.","Before assessor visits, prepare a protocol adherence report showing before-and-after outcomes data (e.g., antibiotic compliance rates, mortality rates) to demonstrate evidence-based impact."]'::jsonb where oe_code = 'COP.1.c';

update public.shco_full_oes set achieve_tips = '["Map all care settings where the same clinical condition is treated (OPD, ward, day-care) and develop a single standardised care pathway or protocol applicable across all those settings.","Create SOPs that specify the same clinical steps, monitoring parameters, and documentation templates regardless of care setting, and distribute them to all relevant departments.","Train staff in every care setting on the unified pathway through monthly in-service sessions and retain attendance sheets and competency assessment records as evidence.","Conduct monthly cross-departmental audits comparing patient records from different settings for the same condition to confirm uniform care delivery and document audit findings."]'::jsonb where oe_code = 'COP.1.d';

update public.shco_full_oes set achieve_tips = '["Draft a written telemedicine policy aligned with the Telemedicine Practice Guidelines 2020 that specifies eligible services, technology platforms, consent requirements, and data security standards.","Set up a secure, encrypted telemedicine platform, train consulting doctors in its use, and maintain a session log for every telemedicine consultation conducted.","Obtain written or electronic consent from patients before each telemedicine encounter, store consent records in the patient file, and document clinical advice given during the session.","Review telemedicine session records quarterly for quality, check that documentation is complete, and report any technical or clinical concerns to the medical committee for corrective action."]'::jsonb where oe_code = 'COP.1.e';

update public.shco_full_oes set achieve_tips = '["Designate a clearly marked emergency reception area at the main entrance with unobstructed ambulance access, and equip it with a resuscitation trolley, defibrillator, oxygen, suction, and essential emergency drugs at all times.","Develop and display a written SOP defining the layout, staff deployment, and equipment checklist for the emergency area, and conduct daily equipment checks with a signed log.","Train all emergency staff in basic life support (BLS) and Advanced Cardiac Life Support (ACLS) protocols, and maintain training certificates with next due-date tracking in personnel files.","Conduct a monthly unannounced drill to test response times and resource availability in the emergency area, document outcomes, and implement corrective actions before the next drill."]'::jsonb where oe_code = 'COP.2.a';

update public.shco_full_oes set achieve_tips = '["Develop a written SOP for managing medico-legal cases (MLCs) that covers mandatory reporting to police, documentation of injuries, evidence preservation, and liaison with legal authorities as required by law.","Ensure that every MLC patient receives emergency stabilisation before any paperwork is initiated — document the time of arrival, first intervention, and MLC registration number in the patient record.","Train all emergency doctors and nurses on MLC procedures during induction and annually, maintaining attendance and competency records; display a quick-reference MLC flowchart at the nursing station.","Conduct quarterly record audits of MLC case files to verify that all statutory fields are completed, police intimation letters are on file, and clinical documentation is accurate and timely."]'::jsonb where oe_code = 'COP.2.b';

update public.shco_full_oes set achieve_tips = '["Implement a validated triage tool (e.g., Modified Early Warning Score or colour-coded triage categories) and display the triage criteria at the emergency reception desk for all incoming staff to reference.","Train all emergency nurses and doctors in triage protocols and document their competency assessment scores; conduct quarterly triage simulation exercises and record outcomes.","Record every patient''s triage category, triage time, and name of the triaging staff member in the emergency register or electronic system immediately upon patient arrival.","Audit triage documentation monthly to check that response times for each triage category meet defined targets, report non-compliances to the emergency department in-charge, and track improvement over three months."]'::jsonb where oe_code = 'COP.2.c';

update public.shco_full_oes set achieve_tips = '["Define in the emergency SOP the maximum acceptable intervals between reassessments for each triage category (e.g., every 15 minutes for high-acuity patients) and make it a mandatory documentation requirement.","Set up a structured reassessment form or EMR field that nursing staff complete at each defined interval, capturing vital signs, pain score, and any change in clinical status.","Brief all emergency nursing staff at the start of each shift on current waiting patients and their reassessment due times, and assign a dedicated nurse to track and flag overdue reassessments.","Review ten random emergency patient files each month to verify that reassessment entries are present at the required intervals and escalate missing entries to the nursing supervisor for follow-up."]'::jsonb where oe_code = 'COP.2.d';

update public.shco_full_oes set achieve_tips = '["Create a standardised admission-discharge-transfer (ADT) form for the emergency department that captures reason for admission or discharge, clinical status at the time of decision, follow-up instructions, and responsible doctor''s signature.","Establish a policy that no patient leaves the emergency without a written discharge note containing diagnosis, treatment given, warning signs to watch for, and next-appointment details, signed by the treating doctor.","Train all emergency doctors and nurses to complete ADT documentation before the patient physically leaves the area, and verify compliance through daily charge-nurse checklist sign-offs.","Conduct a monthly review of ten emergency discharge records to confirm that all mandatory fields including the patient-copy discharge note are complete, and report compliance rates to the emergency committee."]'::jsonb where oe_code = 'COP.2.e';

update public.shco_full_oes set achieve_tips = '["Identify at least five measurable quality indicators for the emergency department (e.g., triage-to-doctor time, LAMA rate, re-visit within 48 hours, cardiac arrest survival rate) and begin collecting baseline data immediately.","Display monthly indicator dashboards in the emergency department and review them in a multidisciplinary quality meeting, documenting meeting minutes and agreed action points.","Set improvement targets for each indicator based on baseline data, implement corrective actions (e.g., staffing changes, protocol revisions), and track progress over three consecutive months.","Compile a before-and-after evidence file showing indicator trends, corrective actions taken, and measurable outcomes to present to assessors as proof of a functioning quality assurance programme."]'::jsonb where oe_code = 'COP.2.f';

update public.shco_full_oes set achieve_tips = '["Develop a written SOP for managing Brought Dead (BD) and patients who die within minutes of arrival, covering documentation requirements, police intimation, MLC registration, body handling, and family notification steps.","Display the BD management flowchart at the emergency nursing station and brief all incoming shift staff on the procedure during daily handovers.","Train emergency doctors and nurses in the BD protocol during induction and conduct a mock exercise annually; retain attendance records and exercise debrief notes.","Audit all BD cases monthly to verify that all documentation requirements were met within specified timeframes, and report any gaps to the emergency in-charge for immediate corrective action."]'::jsonb where oe_code = 'COP.2.g';

update public.shco_full_oes set achieve_tips = '["Document a formal ambulance services agreement or in-house ambulance operational policy that specifies response time commitments, vehicle specifications, equipment list, and communication protocols.","Maintain a daily ambulance readiness log signed by the in-charge that confirms the vehicle is functional, fuel levels are adequate, and emergency equipment is in place before each shift.","Establish a memorandum of understanding (MoU) with at least one external ambulance provider if the hospital does not own an ambulance, and keep the MoU current and accessible during assessments.","Record all ambulance call-outs including dispatch time, arrival time, and patient handover time; review these records monthly to identify delays and implement corrective measures."]'::jsonb where oe_code = 'COP.2.h';

update public.shco_full_oes set achieve_tips = '["Prepare a written ambulance equipment checklist aligned with the ALS or BLS standard appropriate to the hospital''s scope, verify it daily, and have the ambulance in-charge sign the checklist log every shift.","Ensure ambulance personnel hold a valid BLS or ACLS certificate and a valid driving licence; maintain photocopies of all certificates in the personnel file and track renewal dates.","Conduct an unannounced monthly check of the ambulance to confirm that emergency medications (adrenaline, IV fluids, etc.) are within expiry, quantities are adequate, and the cold chain is maintained for temperature-sensitive drugs.","Run a quarterly ambulance response drill, measuring the time from call to vehicle departure; document results and use findings to address gaps in readiness or crew training."]'::jsonb where oe_code = 'COP.2.i';

update public.shco_full_oes set achieve_tips = '["Establish a pre-hospital coordination protocol that allows the ambulance crew to radio or call ahead with patient vitals, suspected diagnosis, and ETA so that the emergency team can prepare the resuscitation bay in advance.","Train ambulance staff to initiate basic interventions (IV access, oxygen, ECG, first-dose medications) per written standing orders while in transit, and document all actions on a pre-hospital care record.","Equip the ambulance with a telemedicine-capable device or direct phone link to the on-call emergency doctor so that treatment can be guided remotely during transport.","Review all pre-hospital care records monthly for completeness and quality of interventions; benchmark door-to-treatment times for cases where pre-hospital care was initiated against those where it was not."]'::jsonb where oe_code = 'COP.2.j';

update public.shco_full_oes set achieve_tips = '["Develop a formal Disaster Management Plan (DMP) covering mass casualty incidents, fire, epidemic outbreaks, and chemical exposures; define roles for each staff category and maintain the plan in a binder accessible to all emergency staff.","Conduct at least two mock disaster drills per year — one announced and one unannounced — covering different scenarios, and document participant roles, response times, and debrief findings.","Establish communication protocols with local government health authorities, nearby hospitals, and the police for coordinated disaster response; keep contact directories updated and test communication links quarterly.","Maintain a surge-capacity plan that specifies how the hospital will expand beds, procure additional supplies, and redeploy staff during a community emergency, and review the plan after each drill or real event."]'::jsonb where oe_code = 'COP.2.k';

update public.shco_full_oes set achieve_tips = '["Create a written resuscitation policy that mandates an assigned resuscitation team on every shift with defined roles (team leader, airway, compressions, medications, recorder) and post the team roster visibly in each ward and critical area.","Ensure crash carts are stocked, sealed, and strategically located in all patient care areas; have the nursing in-charge inspect and sign the crash cart checklist daily and after every use.","Train all clinical staff in BLS at induction and refresher ACLS/PALS for relevant staff annually; maintain valid certification copies in personnel files and track expiry dates on a shared calendar.","Conduct quarterly unannounced Code Blue drills in different locations of the hospital, time the team''s response from activation to first shock or drug administration, and document results with follow-up action plans."]'::jsonb where oe_code = 'COP.3.a';

update public.shco_full_oes set achieve_tips = '["Design a standardised CPR event record form that captures exact timings of each intervention, drug doses given, defibrillation attempts, and team members present; make this form mandatory for every resuscitation event.","Assign a dedicated recorder role during every CPR event whose sole responsibility is to document real-time entries on the event record form, ensuring no intervention goes unlogged.","Conduct a post-resuscitation debrief within 24 hours of every CPR event, using the event record to review team performance; document debrief findings and share them with the multidisciplinary committee.","During assessor visits, produce the CPR event register showing all resuscitation events, corresponding documentation forms, and evidence of role compliance during each event to demonstrate systematic recording practices."]'::jsonb where oe_code = 'COP.3.b';

update public.shco_full_oes set achieve_tips = '["Create a crash cart placement map for the hospital that identifies the location, content list, and responsible department for every cart; display this map in each nursing station and the security office.","Implement a daily crash cart checklist system: the nursing in-charge verifies contents, checks drug expiry dates, tests the defibrillator, and signs the logbook before the first patient contact of the day.","After any use of the crash cart (or any seal break), replenish and re-seal it within one hour and document the replenishment time, names of drugs replaced, and staff responsible in the crash cart log.","Perform a quarterly inventory audit of all crash carts across the hospital and present the compiled audit records to the quality committee, highlighting any gaps and corrective actions taken."]'::jsonb where oe_code = 'COP.3.c';

update public.shco_full_oes set achieve_tips = '["Constitute a multidisciplinary CPR review committee (including the medical director, nursing head, and anaesthesiologist) with a written terms of reference, and schedule meetings within 72 hours of any resuscitation event.","Use a standardised post-event analysis template (covering patient factors, system factors, team response, and outcome) during committee review meetings, and archive completed templates for each event.","Translate committee findings into specific corrective actions (e.g., equipment upgrades, retraining, protocol revisions), assign owners with deadlines, and track completion status at the next meeting.","Compile quarterly CPR outcome data (survival to discharge rate, response time, documentation completeness) and present trends to hospital leadership to demonstrate a culture of continuous improvement."]'::jsonb where oe_code = 'COP.3.d';

update public.shco_full_oes set achieve_tips = '["Ensure every nursing shift begins with a structured patient handover that includes current clinical status, active nursing care plan, pending investigations, and patient-specific alerts documented in a standardised handover record.","Use a unified nursing care plan template in the patient record that links nursing assessments, interventions, and outcomes directly to the treating physician''s management plan, updated at least once per shift.","Conduct monthly nursing record audits selecting ten random in-patient files to verify that nursing entries are timely, legible, complete, and aligned with medical orders, reporting compliance rates to the nursing head.","Allow assessors to observe actual nursing handovers and interview bedside nurses about care planning steps; maintain a nursing procedure log that documents all nursing interventions with time, nurse signature, and patient response."]'::jsonb where oe_code = 'COP.4.a';

update public.shco_full_oes set achieve_tips = '["Develop a written nursing assignment policy based on nurse-to-patient ratios recommended by current guidelines (e.g., NMC norms) and adjust ratios for high-dependency areas such as ICU, OT, and labour room.","Maintain daily nursing deployment sheets that record the nurse-to-patient ratio achieved on each shift in each ward; retain these sheets for at least one year as compliance evidence.","Train charge nurses on competency-based assignment principles and document their training; ensure that nurses with specialised skills (e.g., IV therapy, wound care) are preferentially assigned to patients needing those skills.","Review nursing assignment records monthly to identify recurrent ratio shortfalls and escalate staffing gaps to HR and hospital management with documented recommendations for resolution."]'::jsonb where oe_code = 'COP.4.b';

update public.shco_full_oes set achieve_tips = '["Conduct a biannual nursing equipment needs assessment for each department; maintain an equipment inventory register that tracks item name, quantity, condition, calibration due date, and last maintenance date.","Establish a process for nurses to report non-functioning equipment using a written equipment fault report; set a defined turnaround time for repair or replacement and track resolution times in the maintenance log.","Ensure consumables (syringes, IV lines, dressings, gloves) are stocked to a minimum par level in each ward and replenished daily; assign a named nurse to verify and document stock levels each morning.","During mock assessments or peer audits, verify that nursing staff can readily access and demonstrate proficiency on all critical equipment in their area, and document the outcome of these observations."]'::jsonb where oe_code = 'COP.4.c';

update public.shco_full_oes set achieve_tips = '["Form a nursing practice committee responsible for identifying, adopting, and periodically revising nursing clinical practice guidelines aligned with standards from professional bodies such as the Indian Nursing Council.","Document adopted nursing guidelines in a numbered, version-controlled format with effective and review dates, and store them in an accessible guideline binder or digital repository in each nursing unit.","Conduct nursing staff training on each new or revised guideline within 30 days of adoption, assess comprehension with a written or practical test, and retain training and assessment records in staff files.","Measure guideline adherence through quarterly nursing audits and report compliance rates to the nursing committee; show trend data to assessors as evidence that guidelines are implemented and continuously improved."]'::jsonb where oe_code = 'COP.4.d';

update public.shco_full_oes set achieve_tips = '["Develop an SOP for transfusion services that covers blood ordering, compatibility testing, storage, issue, administration, and reaction management, and ensure it references all applicable regulations (Drugs and Cosmetics Act, NBTC guidelines).","Create a pre-transfusion checklist embedded in the patient record that includes blood group verification, crossmatch result, compatibility label check, and double-nurse identification sign-off before each transfusion unit is hung.","Train all nursing and laboratory staff involved in transfusion services on the SOP at induction and annually; maintain training attendance and competency assessment records in each staff member''s file.","Review transfusion records monthly to verify that pre-transfusion checklists are complete for every unit transfused and that all applicable legal documentation (consent, crossmatch report, transfusion record) is present in the patient file."]'::jsonb where oe_code = 'COP.5.a';

update public.shco_full_oes set achieve_tips = '["Implement a mandatory pre-transfusion double-verification step requiring two nurses to independently confirm the patient''s identity, blood group, and compatibility label before commencing each unit of blood or blood component.","Document the start time, end time, transfusion rate, and patient''s vital signs (before, 15 minutes after starting, and on completion) on a structured transfusion monitoring chart filed in the patient record.","Train all nursing staff in recognition and management of acute transfusion reactions, including when to stop the transfusion, notify the doctor, and preserve the blood bag for investigation; assess their competency annually.","Conduct monthly audits of ten random transfusion records to verify double-verification compliance, complete vital sign monitoring, and reaction-management documentation; report results to the blood transfusion committee."]'::jsonb where oe_code = 'COP.5.b';

update public.shco_full_oes set achieve_tips = '["Establish a blood transfusion committee that reviews all transfusion requests and audits appropriateness based on defined clinical triggers (e.g., Hb thresholds, clinical indication criteria) aligned with national transfusion guidelines.","Require treating doctors to document a clear clinical justification for each transfusion request on the blood request form, including latest relevant investigation values and clinical indication.","Conduct monthly transfusion appropriateness audits using a standardised review tool; report any case where transfusion was given outside defined criteria to the blood transfusion committee for peer review and feedback.","Track the number of units transfused per patient per month and benchmark against clinical outcome data to identify opportunities to reduce unnecessary transfusions, documenting results in quarterly committee minutes."]'::jsonb where oe_code = 'COP.5.c';

update public.shco_full_oes set achieve_tips = '["Design a transfusion-specific informed consent form in the patient''s preferred language that explains the procedure, alternatives, risks (including transfusion reactions), and the right to refuse; obtain and file this form before every transfusion.","Train all doctors to discuss transfusion risks and benefits with the patient or guardian before obtaining consent, and document the discussion in the clinical notes along with the signed consent form reference.","Establish a consent audit process: review ten random transfusion files each month to confirm that a completed, signed consent form is present before the transfusion start time recorded in the nursing chart.","Prepare a consent register for transfusion procedures that logs consent form number, patient name, date, and obtaining doctor; present this register to assessors as evidence of systematic consent management."]'::jsonb where oe_code = 'COP.5.d';

update public.shco_full_oes set achieve_tips = '["Define in writing the maximum acceptable time from blood requisition to issue for emergency situations (e.g., within 15 minutes for massive haemorrhage) and communicate this standard to the blood bank and all clinical departments.","Maintain a small emergency stock (O-negative units or group-specific blood) in the blood bank at all times and log daily stock levels; define the minimum stock level and escalation process when stock falls below the threshold.","Conduct quarterly timed drills simulating an emergency blood request, measuring the time from doctor''s order to blood reaching the ward; document results and act on any breach of the defined time standard.","Review emergency blood request records monthly to calculate actual average turnaround times, compare against the defined standard, and present trend data to the blood transfusion committee with corrective actions where targets are not met."]'::jsonb where oe_code = 'COP.5.e';

update public.shco_full_oes set achieve_tips = '["Introduce a standardised post-transfusion monitoring form that is sent back to the blood bank within 24 hours of transfusion completion, capturing the patient''s clinical response and any reaction observed during or after transfusion.","Create a transfusion reaction register in the blood bank to record all reported reactions with details of reaction type, severity, investigation findings, and outcome; review this register at every blood transfusion committee meeting.","Investigate every reported transfusion reaction using a root cause analysis template, identify contributing factors, and implement corrective actions (e.g., staff retraining, revised checklists) within 30 days.","Calculate monthly transfusion reaction rates, display them on the blood bank quality dashboard, and compare rates over time to demonstrate a downward trend as evidence of an effective quality improvement programme."]'::jsonb where oe_code = 'COP.5.f';

update public.shco_full_oes set achieve_tips = '["Develop written ICU/HDU admission and discharge criteria based on recognised scoring systems (e.g., APACHE II, SOFA) and document them in an SOP accessible to all ICU staff; include a specific plan for managing bed shortages (e.g., step-down protocols, transfer criteria).","Record the clinical justification for every ICU/HDU admission and discharge in the patient record, including the relevant severity score and the name of the authorising intensivist or designated doctor.","Conduct monthly bed management audits that review ICU occupancy rates, bed shortage episodes, and how the shortage protocol was implemented; present findings at the ICU quality meeting with corrective actions documented.","Train all ICU and ward staff on admission and discharge criteria through quarterly in-service sessions; retain training records and demonstrate to assessors that staff can correctly apply the criteria when interviewed."]'::jsonb where oe_code = 'COP.6.a';

update public.shco_full_oes set achieve_tips = '["Prepare a written ICU/HDU operational policy specifying nurse-to-patient ratios, minimum equipment requirements (ventilator, infusion pump, cardiac monitor, defibrillator), and prescribing authority for the unit.","Conduct daily equipment rounds in the ICU/HDU, verify functionality of all life-support and monitoring devices, and record findings on a signed equipment check log filed in the unit.","Maintain ICU staffing rosters for the past 12 months to demonstrate that recommended nurse-to-patient ratios were maintained on all shifts; flag and document any shortfall and the immediate compensatory measures taken.","Allow assessors to observe ICU nursing rounds and interview ICU staff regarding their care protocols; ensure all written guidance documents are current, signed by the medical director, and available at the nursing station."]'::jsonb where oe_code = 'COP.6.b';

update public.shco_full_oes set achieve_tips = '["Develop and display ICU-specific infection control SOPs covering hand hygiene compliance, central line bundle care, ventilator-associated pneumonia (VAP) prevention, and catheter-associated urinary tract infection (CAUTI) prevention.","Track ICU-specific infection rates (CLABSI, VAP, CAUTI) monthly, display trend graphs in the ICU, and review them at multidisciplinary infection control meetings with documented corrective actions.","Conduct weekly hand hygiene and bundle compliance audits in the ICU using a structured observation checklist; share results with ICU staff at morning meetings and post corrective-action notices where compliance falls below 90%.","Prepare an infection control audit portfolio for the ICU covering the past 12 months of compliance data, infection rates, and corrective actions taken, to present to assessors as documented evidence of ongoing infection prevention practice."]'::jsonb where oe_code = 'COP.6.c';

update public.shco_full_oes set achieve_tips = '["Define at least six measurable ICU quality indicators (e.g., ventilator days, length of stay, unexpected ICU readmission rate, unplanned extubation rate, mortality rate) and begin data collection immediately.","Review ICU quality indicator data monthly in a multidisciplinary ICU committee meeting, document discussions and action points in meeting minutes, and assign owners with deadlines for each improvement activity.","Set improvement targets for each indicator, implement changes (protocol revisions, equipment upgrades, staffing adjustments), and track whether the target is met over three consecutive months.","Compile an ICU quality report covering 12 months of indicator data with trend analysis and before-and-after outcome comparisons; present this to assessors as evidence of a sustained quality assurance programme."]'::jsonb where oe_code = 'COP.6.d';

update public.shco_full_oes set achieve_tips = '["Establish a written family communication policy for the ICU/HDU that specifies the frequency of physician-family meetings (e.g., daily or every 48 hours), who conducts them, and what information is covered.","Create a family counselling record form that captures the date, time, topics discussed, family members present, and doctor''s signature; file this in the patient record after every counselling session.","Designate a quiet counselling room adjacent to or near the ICU and ensure doctors and nurses use it for all family discussions to maintain privacy and improve the quality of communication.","During assessments, produce a sample of ICU patient files showing completed counselling records at defined intervals and allow assessors to interview nursing staff about the counselling process to verify consistent implementation."]'::jsonb where oe_code = 'COP.6.e';

update public.shco_full_oes set achieve_tips = '["Develop a written end-of-life care policy that addresses withholding or withdrawing life-sustaining treatment, palliative comfort measures, do-not-resuscitate (DNR) orders, and documentation requirements, in accordance with Indian law.","Create a standardised DNR order form and palliative care plan template; require that any end-of-life decision is documented by the treating physician and co-signed by a second senior doctor, with family consent noted.","Train all ICU and ward doctors and nurses in end-of-life communication skills and legal obligations through an annual workshop; retain attendance records and circulate a written summary of key legal requirements.","Audit ten end-of-life patient records quarterly to verify that care plans, family counselling notes, and DNR orders (where applicable) are properly documented; report audit findings to the ethics committee with any corrective actions required."]'::jsonb where oe_code = 'COP.6.f';

update public.shco_full_oes set achieve_tips = '["Develop an obstetric services SOP covering antenatal registration, risk stratification, intrapartum monitoring, labour management, and postpartum care, aligning it with national safe motherhood guidelines and LaQshya standards where applicable.","Maintain a labour room register that records each delivery with time of admission, gravida/para status, mode of delivery, attendant''s name, baby outcome, and maternal outcome; review the register at monthly obstetric review meetings.","Conduct quarterly skills drills for obstetric emergencies (postpartum haemorrhage, eclampsia, shoulder dystocia) in the labour room; document scenario details, staff participation, and corrective actions identified from the drill debrief.","Ensure obstetric patients'' case records contain completed partographs, intrapartum monitoring sheets, and delivery notes; audit ten random delivery records each month for completeness and present findings to the obstetrics department head."]'::jsonb where oe_code = 'COP.7.a';

update public.shco_full_oes set achieve_tips = '["Create a high-risk obstetric identification checklist (covering conditions such as severe anaemia, pre-eclampsia, diabetes, malpresentation, and previous caesarean section) and ensure it is completed for every antenatal patient at registration.","Maintain a high-risk obstetric register, review it at every antenatal visit, and ensure care is assigned to a qualified obstetrician and trained nurse with documented evidence of their credentials.","Develop written referral criteria and a referral pathway for high-risk cases requiring tertiary care; keep MoUs with referral centres current and document all referrals with the reason, patient condition at transfer, and receiving centre''s acknowledgement.","Audit high-risk obstetric case records monthly to confirm that risk identification, specialist involvement, management plans, and referral documentation are complete and timely; report audit results to the medical committee."]'::jsonb where oe_code = 'COP.7.b';

update public.shco_full_oes set achieve_tips = '["Incorporate a structured maternal nutrition assessment tool into the standard antenatal booking form, capturing body mass index, dietary history, haemoglobin level, and micronutrient supplementation status at every antenatal visit.","Train antenatal nurses and doctors to counsel all pregnant women on nutrition requirements and document the counselling in a nutrition counselling record retained in the antenatal case file.","Refer antenatal patients identified as nutritionally at-risk (low BMI, anaemia, poor dietary intake) to a dietitian or nutrition counsellor; document the referral and the follow-up nutritional assessment in the patient record.","Conduct a quarterly audit of antenatal case files to verify that a nutrition assessment is documented for every patient; calculate the completion rate and use it as a quality indicator reviewed by the obstetrics team."]'::jsonb where oe_code = 'COP.7.c';

update public.shco_full_oes set achieve_tips = '["Develop a peri-natal and post-natal monitoring SOP specifying minimum vital sign and foetal heart rate (FHR) monitoring frequencies for each stage of labour and for the 48-hour post-natal period, aligned with national clinical guidelines.","Use a standardised partograph for every woman in active labour, completing all sections including FHR, uterine contractions, cervical dilatation, and maternal vitals at the required intervals; file the completed partograph in the patient record.","Implement post-natal check rounds at defined intervals (e.g., every 4 hours in the first 24 hours post-delivery) for both mother and neonate, documenting each round''s findings on a structured post-natal monitoring chart.","Audit fifteen random delivery records per month to verify that partographs are fully completed and post-natal monitoring charts are present with all entries; share compliance rates with the obstetrics team and track improvement."]'::jsonb where oe_code = 'COP.7.d';

update public.shco_full_oes set achieve_tips = '["Ensure that any facility managing high-risk obstetric cases has a functional neonatal resuscitation area in or immediately adjacent to the delivery room, equipped with a radiant warmer, bag-mask device, suction, and oxygen.","Maintain a roster of at least one staff trained in Neonatal Resuscitation Programme (NRP) available in the labour room on every shift; keep NRP certificates in personnel files with renewal tracking.","Develop a written neonatal care SOP for high-risk deliveries covering immediate newborn assessment, Apgar scoring, resuscitation steps, and criteria for transfer to the NICU or special newborn care unit.","Audit all high-risk delivery records quarterly to confirm that a trained neonatal care provider was present, Apgar scores are documented at 1 and 5 minutes, and any neonatal intervention is fully recorded in the baby''s case file."]'::jsonb where oe_code = 'COP.7.e';

update public.shco_full_oes set achieve_tips = '["Develop a paediatric services SOP covering patient assessment, age-appropriate monitoring parameters, weight-based medication calculation, and specific safety requirements for children, referenced to IAP or WHO paediatric guidelines.","Maintain a paediatric ward safety checklist (cot-side rails, secured IV lines, age-appropriate equipment sizes, no sharps within child reach) completed by the nursing in-charge at the start of every shift and filed in the unit log.","Conduct quarterly paediatric emergency drills (e.g., neonatal resuscitation, febrile seizure management) in the paediatric ward; document staff participation, time taken, and any process improvements identified.","Audit ten random paediatric patient records each month to verify that age-specific vital sign ranges were used, weight-based drug calculations are documented, and nursing assessments are completed at required intervals."]'::jsonb where oe_code = 'COP.8.a';

update public.shco_full_oes set achieve_tips = '["Display current national (NNF) or WHO neonatal care guidelines in the nursery and SNCU, and develop unit-specific SOPs for temperature maintenance, feeding support, infection prevention, and oxygen therapy for neonates.","Maintain a neonatal temperature log, feeding record, and daily weight chart for every admitted neonate; ensure nursing staff complete these records at every care contact and sign each entry.","Conduct monthly neonatal outcome audits (hypothermia rate, hypoglycaemia rate, infection rate, breastfeeding initiation rate) and review results at neonatal unit meetings with documented corrective actions.","Train all neonatal unit staff in neonatal resuscitation and kangaroo mother care annually; keep training records and present them alongside outcome data to assessors as evidence that guidelines are translated into measurable improvements."]'::jsonb where oe_code = 'COP.8.b';

update public.shco_full_oes set achieve_tips = '["Develop an age-specific competency framework for staff working in the paediatric unit, covering normal developmental milestones, age-appropriate vital sign ranges, pain assessment tools (FLACC, Wong-Baker), and paediatric drug safety.","Assess each paediatric nurse and doctor against the competency framework at induction and annually thereafter using a written and practical evaluation; retain completed competency assessment forms in staff files.","Conduct quarterly peer skill-checks in the paediatric ward where senior staff observe and document whether junior staff correctly use age-appropriate assessment tools and equipment during routine care.","During assessor visits, allow assessors to interview paediatric nurses and doctors on age-specific assessment techniques; ensure staff can name the age-appropriate tools used in the unit and demonstrate correct pain scoring on a paediatric patient."]'::jsonb where oe_code = 'COP.8.c';

update public.shco_full_oes set achieve_tips = '["Create an SOP for special paediatric care needs, covering care for premature neonates, children with disabilities, child protection concerns, and children requiring isolation, and make it accessible to all paediatric unit staff.","Equip the paediatric unit with child-friendly furniture (cots with secured rails, size-appropriate equipment), age-appropriate distraction materials, and a parent sleeping provision; document these provisions in the ward inspection register.","Establish a referral pathway to paediatric sub-specialists (paediatric surgery, paediatric neurology, etc.) for children with complex needs; document all referrals with clinical justification and receiving specialist''s response in the patient record.","Conduct a biannual paediatric unit environment audit to verify that special care provisions are in place and functional; record findings and corrective actions in the quality management system."]'::jsonb where oe_code = 'COP.8.d';

update public.shco_full_oes set achieve_tips = '["Incorporate a structured paediatric assessment template into the admission form that includes sections for nutritional status (weight-for-age, height-for-age), developmental milestones, growth chart plotting, and immunisation history.","Train all paediatric nursing staff to use standardised growth charts (IAP or WHO), record immunisation status, and identify developmental red flags at every patient contact; assess their competency annually.","Refer any child identified as malnourished, developmentally delayed, or with incomplete immunisation to the appropriate specialist or immunisation clinic; document the referral and follow-up in the patient record.","Audit ten random paediatric admission records each month to verify that all four assessment domains (nutrition, growth, development, immunisation) are documented; report completion rates to the paediatric department head."]'::jsonb where oe_code = 'COP.8.e';

update public.shco_full_oes set achieve_tips = '["Develop a child/neonate security policy that includes parent/guardian identification band matching (baby band linked to mother band), visitor pass controls, CCTV coverage of the paediatric and neonatal units, and a defined alarm response protocol for missing child.","Implement a daily security round of the paediatric and neonatal units conducted by nursing supervisor and security staff; document findings and any security concerns in a unit security log.","Train all paediatric and neonatal unit staff in child abduction and abuse prevention protocols at induction and annually; include recognising signs of abuse and the mandatory reporting pathway to the child welfare committee.","Conduct a quarterly security drill simulating a missing child scenario in the paediatric unit; time the response to activation of the search protocol and document results, identifying gaps and implementing corrective measures."]'::jsonb where oe_code = 'COP.8.f';

update public.shco_full_oes set achieve_tips = '["Develop a procedural sedation SOP specifying eligible procedures, patient selection criteria, pre-sedation assessment requirements, drug choices, dosing guidelines, and monitoring parameters for each level of sedation.","Train all doctors who administer procedural sedation in the SOP and assess their competency through a structured practical evaluation; maintain training and assessment records and restrict sedation privileges to credentialled staff only.","Create a structured pre-sedation assessment form that documents patient ASA classification, airway assessment, allergies, last oral intake, and planned sedation agent, and file this form in the patient record before every procedure.","Audit ten random procedural sedation records monthly to verify SOP adherence, documentation completeness, and that only credentialled staff administered sedation; report compliance rates to the quality committee."]'::jsonb where oe_code = 'COP.9.a';

update public.shco_full_oes set achieve_tips = '["Design a procedural sedation consent form that explains the purpose, process, risks (over-sedation, respiratory depression, aspiration), and alternatives; make it available in the patient''s preferred language.","Train all doctors to discuss sedation risks with the patient or guardian before obtaining consent, and ensure this discussion and the signed consent form are documented in the patient record before the procedure begins.","Conduct a monthly consent audit for procedural sedation cases, checking that signed consent forms are present, pre-date the procedure, and contain the patient''s or guardian''s signature; report compliance percentages to the quality committee.","Prepare a consent register for all procedural sedation cases that logs the date, consent form number, obtaining doctor, and patient or guardian name; present this register to assessors as evidence of a systematic consent process."]'::jsonb where oe_code = 'COP.9.b';

update public.shco_full_oes set achieve_tips = '["Define and document the minimum qualifications and training required for staff who administer and monitor procedural sedation; maintain a credentialling register listing all authorised staff with their qualification proof and last competency assessment date.","Ensure that the staff member monitoring the patient during sedation has no other duties during the procedure; document their name and role in the sedation record for every case.","Conduct annual competency re-assessments for all sedation providers covering drug knowledge, monitoring techniques, and management of sedation complications; remove privileges for staff who do not meet competency standards until remedial training is completed.","During assessor visits, present the credentialling register and allow assessors to interview the sedation monitoring nurse about monitoring parameters and emergency response steps to verify practical competency."]'::jsonb where oe_code = 'COP.9.c';

update public.shco_full_oes set achieve_tips = '["Create a mandatory intra-procedure monitoring chart for procedural sedation that has pre-printed fields for heart rate, cardiac rhythm, respiratory rate, blood pressure, oxygen saturation, and sedation depth score (e.g., Ramsay Scale) to be completed at minimum every 5 minutes.","Ensure that monitoring equipment (pulse oximeter, NIBP, ECG monitor) is connected and functional before administering any sedation agent, and document equipment verification on the pre-sedation checklist.","Train nursing staff to immediately alert the doctor if any monitored parameter deviates from the defined acceptable range, and ensure the emergency response (reversal agent, airway support) is rehearsed quarterly.","Audit ten random sedation monitoring charts monthly to verify that all six parameters are documented at appropriate intervals and that the monitoring nurse''s name is recorded; report compliance rates to the quality committee."]'::jsonb where oe_code = 'COP.9.d';

update public.shco_full_oes set achieve_tips = '["Design a post-sedation recovery chart with objective discharge criteria (e.g., modified Aldrete score ≥9, or equivalent validated scale) that must be met and documented before any patient is transferred from the recovery area.","Train recovery nurses to perform and record objective assessments at defined intervals (e.g., every 15 minutes) until discharge criteria are met, and to document the time of discharge from recovery along with the achieved score.","Ensure that a doctor reviews and countersigns the recovery chart before the patient is transferred out of the recovery area, and that verbal and written post-procedure instructions are given to the patient or escort and documented.","Audit ten random post-sedation recovery records each month to verify that objective discharge criteria scores are recorded, criteria were met before transfer, and post-procedure instructions are documented; report findings to the quality committee."]'::jsonb where oe_code = 'COP.9.e';

update public.shco_full_oes set achieve_tips = '["Develop an anaesthesia services SOP covering pre-anaesthesia assessment, pre-induction check, intraoperative monitoring standards, post-anaesthesia care, and emergency protocols, and ensure it is signed off by the department head and available in the OT.","Train all anaesthesiologists on the SOP at induction and during annual updates; maintain training attendance records and document any SOP revisions with version number and effective date.","Implement a pre-operative anaesthesia check using a standardised machine checklist (covering equipment, gas supply, emergency drugs) completed by the anaesthesiologist before every list; file the signed checklist in the OT register.","Conduct monthly anaesthesia record audits selecting ten random cases to verify SOP adherence, completeness of documentation, and consistent monitoring; present findings with compliance rates at the anaesthesia department meeting."]'::jsonb where oe_code = 'COP.10.a';

update public.shco_full_oes set achieve_tips = '["Design a pre-anaesthesia assessment form that captures patient history, physical examination findings, relevant investigations, ASA classification, airway assessment (Mallampati score), planned anaesthesia technique, and anticipated risks, and require completion for every elective and emergency case.","Ensure the anaesthesiologist completes and signs the pre-anaesthesia assessment at least 6 hours before elective surgery (or as soon as possible for emergencies) and files it in the patient''s operative record.","Train all anaesthesiologists to document the anaesthesia plan explicitly, including type of anaesthesia, induction agents, maintenance agents, airway management plan, and anticipated post-operative pain management in the pre-anaesthesia form.","Audit ten random surgical patient records each month to confirm pre-anaesthesia assessment forms are complete, signed, and include a clearly documented anaesthesia plan; report the compliance rate at the anaesthesia departmental meeting."]'::jsonb where oe_code = 'COP.10.b';

update public.shco_full_oes set achieve_tips = '["Develop a structured pre-induction checklist (covering patient identity verification, consent confirmation, NPO status, IV access, pre-medication given, allergy alert, and anaesthesia machine check) that the anaesthesiologist completes and signs immediately before induction.","Make the pre-induction checklist a mandatory component of the anaesthesia record; do not allow induction to proceed unless the checklist is completed and any identified concern is resolved and documented.","Train all anaesthesiologists and OT nurses in the pre-induction checklist procedure during OT orientation; conduct a quarterly OT drill where the checklist completion is timed and observed by the quality team.","Audit ten random anaesthesia records monthly to verify that pre-induction checklists are signed, completed, and precede the induction time on the anaesthesia chart; report non-compliance immediately to the anaesthesia department head."]'::jsonb where oe_code = 'COP.10.c';

update public.shco_full_oes set achieve_tips = '["Design an anaesthesia-specific informed consent form that explains the planned anaesthesia technique, alternatives (e.g., regional vs. general), common and serious risks, and the post-anaesthesia recovery process in simple language.","Require the anaesthesiologist to obtain and document anaesthesia consent separately from the surgical consent during the pre-anaesthesia visit, filing the signed form in the patient record before the patient enters the OT.","Conduct a monthly consent audit for all surgical cases, checking that a signed anaesthesia consent form is present and pre-dates the OT admission time; calculate and report compliance rates to the quality committee.","Train all anaesthesiologists on informed consent principles and patient rights during annual training; retain attendance records and address any consent compliance gaps identified in audits through targeted retraining."]'::jsonb where oe_code = 'COP.10.d';

update public.shco_full_oes set achieve_tips = '["Ensure every anaesthesia record contains a standardised intraoperative monitoring section with fields for ECG, heart rate, NIBP, SpO2, EtCO2, temperature, and fluid balance to be recorded at minimum every 5 minutes, as per ASA monitoring standards.","Connect all monitoring devices to the patient before induction and verify their functionality; document the pre-use check on the anaesthesia checklist; do not proceed with induction if any mandatory monitor is non-functional.","Train OT nurses and anaesthesia technicians to assist with monitoring setup, identify alarm conditions, and immediately alert the anaesthesiologist of any parameter outside defined safe ranges; assess their competency annually.","Audit ten random anaesthesia charts each month to verify that intraoperative monitoring parameters are recorded at required intervals throughout the procedure and that the anaesthesiologist''s signature is present; report compliance to the department head."]'::jsonb where oe_code = 'COP.10.e';

update public.shco_full_oes set achieve_tips = '["Implement a post-anaesthesia care unit (PACU) monitoring chart with objective discharge criteria (modified Aldrete or White-Song score) that must be documented and met before any patient is transferred from the recovery area.","Require PACU nurses to record vital signs, pain score, sedation level, airway status, and nausea/vomiting score at minimum every 15 minutes until discharge criteria are met; ensure the anaesthesiologist signs off on discharge.","Train all PACU nursing staff in post-anaesthesia monitoring, management of common complications (hypoxia, hypotension, shivering, PONV), and reversal agent administration protocols; assess competency annually.","Audit ten random PACU records monthly to verify that objective discharge criteria scores are documented, discharge criteria were met before ward transfer, and the time of PACU discharge is recorded; report compliance rates at the anaesthesia meeting."]'::jsonb where oe_code = 'COP.10.f';

update public.shco_full_oes set achieve_tips = '["Create a mandatory anaesthesia drug and technique documentation section on the anaesthesia record form with pre-printed fields for induction agent, dose, route, maintenance agents, regional anaesthetic agents (if used), reversal agents, and emergency drugs administered.","Require the anaesthesiologist to complete drug documentation in real time during the procedure and countersign the completed anaesthesia record before handing over the patient to the PACU nurse.","Conduct a quarterly random sample audit of ten anaesthesia records to verify that all drug names, doses, times, and routes are legibly documented for every medication given; report any missing entries as non-compliances to the anaesthesia department head.","During assessor visits, present anaesthesia records alongside the PACU chart to demonstrate a continuous and complete drug and monitoring record for each patient; train anaesthesiologists to articulate the documentation workflow to assessors during interviews."]'::jsonb where oe_code = 'COP.10.g';

update public.shco_full_oes set achieve_tips = '["Define a list of reportable intraoperative adverse events (e.g., unexpected difficult airway, anaphylaxis, intraoperative awareness, cardiac arrest, unplanned conversion to general anaesthesia) and require the anaesthesiologist to flag and document each occurrence on the anaesthesia record.","Maintain an adverse anaesthesia event register that captures date, case, type of event, severity, immediate action taken, and outcome for every reported event; review this register at the monthly anaesthesia committee meeting.","Conduct a root cause analysis for every adverse anaesthesia event, identify contributing factors, and implement corrective actions within 30 days; document the analysis and corrective actions in the event register.","Calculate monthly adverse event rates per 1000 anaesthetics, track trend data over 12 months, and present before-and-after outcome comparisons to assessors as evidence of a functional monitoring and improvement programme."]'::jsonb where oe_code = 'COP.10.h';

update public.shco_full_oes set achieve_tips = '["Develop SOPs for all major clinical procedures performed in the hospital (e.g., IV cannulation, lumbar puncture, central line insertion, wound suturing) and for all OT procedures; display quick-reference guides in procedure rooms and the OT.","Train all clinical and OT nursing staff on each procedure SOP at induction; conduct annual SOP refresher sessions and retain attendance and competency assessment records for every staff member.","Implement a pre-procedure time-out immediately before every invasive procedure: confirm patient identity, procedure, site, and consent aloud with the entire team; document the time-out in the procedure record.","Audit ten random procedural records each month to verify SOP adherence, time-out documentation, and complete procedural notes; present compliance rates at the quality committee meeting."]'::jsonb where oe_code = 'COP.11.a';

update public.shco_full_oes set achieve_tips = '["Implement a mandatory pre-operative assessment form that captures history, physical examination, ASA status, pre-operative investigations, pre-operative diagnosis, and pre-operative instructions given to the patient; require the surgeon to complete it before any elective surgery.","Document patient-specific pre-operative instructions (NPO duration, bowel preparation, pre-operative medications to hold or continue, skin preparation) in the patient record and verify they were communicated to and understood by the patient.","Develop a pre-operative checklist completed by the ward nurse on the day of surgery confirming that all pre-operative requirements have been met; attach the signed checklist to the patient''s file before OT transfer.","Audit ten random surgical case files monthly to verify that pre-operative assessments, diagnoses, and documented patient instructions are present and complete before the OT admission time; report compliance rates to the surgical department head."]'::jsonb where oe_code = 'COP.11.b';

update public.shco_full_oes set achieve_tips = '["Design a procedure-specific informed consent form for every major surgical and invasive procedure, written in simple language and the patient''s preferred language, covering the procedure, alternatives, benefits, risks, and the right to withdraw consent.","Require the operating surgeon to personally obtain and document informed consent during the pre-operative visit, at least 24 hours before elective surgery; do not allow OT admission without a signed consent form in the patient file.","Conduct a monthly surgical consent audit reviewing ten random case files to confirm that signed, completed consent forms are present, pre-date the OT admission time, and bear the operating surgeon''s signature.","Train all surgical and procedure-performing staff on the ethical and legal requirements for informed consent during annual medical-legal training; maintain attendance records and display a summary of consent requirements in all procedure rooms."]'::jsonb where oe_code = 'COP.11.c';

update public.shco_full_oes set achieve_tips = '["Adopt the WHO Surgical Safety Checklist (sign-in, time-out, sign-out) for every surgical and invasive procedure; post the checklist prominently in every OT and procedure room and make its completion mandatory before incision.","Designate a team member (typically the circulating nurse) as the checklist coordinator for each case; train all OT staff in their checklist roles and conduct quarterly observed drills to verify correct checklist execution.","Implement a site-marking policy requiring the operating surgeon to mark the operative site with an indelible marker before the patient enters the OT, and verify the mark during the surgical time-out; document this verification in the operative checklist.","Audit the completed WHO checklist forms from every OT case monthly; calculate the percentage of cases where all three checklist phases (sign-in, time-out, sign-out) were completed, and report non-compliance directly to the OT medical in-charge."]'::jsonb where oe_code = 'COP.11.d';

update public.shco_full_oes set achieve_tips = '["Develop and display a standard precautions SOP for OT and procedure rooms covering hand hygiene, PPE selection (sterile gown, gloves, mask, eye protection), sharps handling, and instrument decontamination; make compliance mandatory for all OT staff.","Conduct monthly observed audits of OT standard precautions adherence using a structured checklist, noting compliance with each precaution for all team members; share results with the OT nursing in-charge for immediate corrective action.","Ensure a complete set of correctly sized PPE is available at every OT table and procedure trolley before the start of each case; assign the circulating nurse to verify and document PPE availability on the pre-case checklist.","Train all OT and procedure room staff in standard precautions at induction and annually; include a practical skills station in training sessions and retain competency assessment records for each staff member."]'::jsonb where oe_code = 'COP.11.e';

update public.shco_full_oes set achieve_tips = '["Develop a structured operative note template that includes pre-operative diagnosis, post-operative diagnosis, procedure performed, findings, complications, estimated blood loss, specimens sent, and post-operative care plan; require the surgeon to complete it before leaving the OT.","Train all surgeons to dictate or write operative notes immediately after each procedure; have a nursing supervisor verify that the operative note is present in the patient file before the patient is transferred to the recovery room.","Design a post-operative monitoring chart for the ward specifying minimum vital sign frequencies, wound check intervals, drain output recording, and pain scores; require nursing staff to complete and sign the chart at each observation.","Audit ten random surgical patient files monthly to verify that operative notes, post-operative monitoring charts, and post-operative care plans are all present and complete; report compliance rates to the surgical department head and quality committee."]'::jsonb where oe_code = 'COP.11.f';

update public.shco_full_oes set achieve_tips = '["Conduct a biannual OT equipment and facility audit using a standardised checklist that covers anaesthesia machine, OT table, surgical lighting, suction, diathermy, sterilised instrument sets, implant inventory, and emergency equipment availability.","Implement a daily OT readiness checklist completed by the OT nursing in-charge before the first case, confirming that equipment is functional, instruments are sterilised, consumables are stocked, and emergency drugs are available.","Establish a preventive maintenance schedule for all major OT equipment and document each service in an equipment maintenance register; ensure critical equipment has a defined backup plan if it fails during a case.","During assessor visits, present the OT equipment audit register and daily readiness checklists; walk assessors through the OT and demonstrate the location and availability of emergency equipment and instrument sterilisation records."]'::jsonb where oe_code = 'COP.11.g';

update public.shco_full_oes set achieve_tips = '["Define OT quality indicators (e.g., surgical site infection rate, OT cancellation rate, case-cart accuracy rate, instrument count discrepancy rate, returnto-OT rate) and collect baseline data for the first three months.","Review OT quality indicator data monthly in an OT committee meeting; document discussion points, improvement targets, and assigned action owners with completion deadlines in the meeting minutes.","Implement at least one targeted improvement project per quarter based on quality indicator findings (e.g., reducing OT cancellations by improving pre-operative preparation); track progress and document outcomes.","Compile a 12-month OT quality report with indicator trend graphs and before-and-after outcome data to present to assessors as evidence of a functioning, data-driven quality assurance programme."]'::jsonb where oe_code = 'COP.11.h';

update public.shco_full_oes set achieve_tips = '["Develop a written organ transplant policy covering legal authorisation requirements under the Transplantation of Human Organs and Tissues Act (THOTA), ethics committee approval, donor and recipient eligibility criteria, and documentation requirements.","Constitute a hospital transplant ethics committee with the composition and functions mandated by THOTA; hold documented meetings before every transplant case, retain minutes, and file committee approval letters in the patient record.","Train all transplant team members in THOTA legal requirements, including mandatory reporting, donor evaluation protocols, and consent documentation; maintain training records and display a THOTA compliance flowchart in the transplant unit.","Conduct an annual internal THOTA compliance audit covering documentation, committee approvals, and registry reporting; present audit findings and corrective actions to hospital management and retain records for regulatory inspections."]'::jsonb where oe_code = 'COP.11.i';

update public.shco_full_oes set achieve_tips = '["Display organ donation awareness materials (posters, brochures, pledging cards) in high-footfall areas such as OPD, reception, and waiting areas, and update them whenever national campaign materials are refreshed.","Train all OPD and ward staff to proactively discuss organ donation with patients and families during appropriate clinical encounters, and document awareness sessions conducted in a hospital awareness activity register.","Organise at least two organ donation awareness events per year (e.g., during National Organ Donation Day on 27 November), open to staff, patients, families, and the community; document attendance and activities conducted.","Track the number of organ donation pledges and family awareness sessions conducted each quarter, and report these figures to hospital management as a quality indicator demonstrating commitment to the national organ donation cause."]'::jsonb where oe_code = 'COP.11.j';

update public.shco_full_oes set achieve_tips = '["Develop a written vulnerable patient identification policy listing categories of vulnerable patients (elderly, paediatric, cognitively impaired, physically challenged, victims of abuse, patients at end of life) and specify the assessment tool and additional care measures for each category.","Use a vulnerability screening checklist at patient admission to identify and flag vulnerable patients; indicate vulnerability status on the patient wristband or bed-head ticket using a designated colour code or symbol.","Train all clinical and nursing staff to recognise and respond to the needs of vulnerable patients, including mandatory reporting of suspected abuse to the patient welfare committee; retain training attendance records.","Conduct monthly audits of vulnerable patient case files to confirm that vulnerability was identified at admission, additional care measures are documented and implemented, and patient safety checks are completed at required intervals."]'::jsonb where oe_code = 'COP.12.a';

update public.shco_full_oes set achieve_tips = '["Conduct a physical environment safety assessment for each area housing vulnerable patients, checking for secured call bells, absence of sharp edges, non-slip flooring, adequate lighting, and controlled visitor access; document findings and rectify hazards within defined timelines.","Assign a dedicated named nurse responsible for each vulnerable patient''s safety checks on every shift, documenting the check time and findings on a structured patient safety observation form.","Install visible monitoring aids (e.g., bed exit alarms for fall-risk patients, identification wristbands for cognitively impaired patients) and document their use in the patient record.","Review any incident involving a vulnerable patient using a root cause analysis framework within 48 hours of the event; document findings, corrective actions, and preventive measures taken, and present the case at the next quality meeting."]'::jsonb where oe_code = 'COP.12.b';

update public.shco_full_oes set achieve_tips = '["Implement a validated fall risk assessment tool (e.g., Morse Fall Scale) for every patient at admission, after any fall, after a change in clinical condition, and at every shift handover; document scores and risk category in the patient record.","Implement fall prevention interventions tailored to each patient''s risk level (e.g., non-slip footwear, bed alarms, low-bed positioning, regular toileting schedule for high-risk patients) and document each intervention in the care plan.","Conduct nursing staff training on fall risk assessment and prevention protocols at induction and annually; include a practical session on using the chosen assessment tool and demonstrate correct documentation.","Track the number of falls per 1000 patient days monthly, classify each fall by severity, and conduct a root cause analysis for every fall; present trend data to the quality committee and document corrective actions implemented to reduce recurrence."]'::jsonb where oe_code = 'COP.12.c';

update public.shco_full_oes set achieve_tips = '["Use a validated pressure ulcer risk assessment tool (e.g., Braden Scale or Waterlow Scale) for every admitted patient within 4 hours of admission, at every shift change, and after any change in mobility or nutritional status; document scores and stage in the patient record.","Implement a structured pressure ulcer prevention bundle for all at-risk patients, including repositioning every 2 hours, use of pressure-relieving mattresses, moisture management, and nutritional supplementation, and document each intervention on the nursing care plan.","Train all nursing staff in pressure ulcer risk assessment, staging (Stages I–IV plus unstageable), and prevention interventions at induction and annually; retain competency assessment records and verify practical skills through observation.","Track pressure ulcer incidence rates monthly (hospital-acquired ulcers per 1000 patient days), conduct root cause analysis for every stage II or higher hospital-acquired ulcer, and present trend data with corrective actions to the quality committee."]'::jsonb where oe_code = 'COP.12.d';

update public.shco_full_oes set achieve_tips = '["Implement a standardised DVT risk assessment tool (e.g., Caprini or Padua score) for every surgical and high-risk medical patient at admission and after surgery; document the score and prescribed thromboprophylaxis plan in the patient record.","Develop and display a DVT prophylaxis protocol in surgical wards and ICUs specifying pharmacological (LMWH dose and timing) and mechanical (compression stockings, pneumatic compression devices) prophylaxis options based on risk score.","Train all surgical, ICU, and general medicine nursing staff to apply compression stockings correctly, administer LMWH as prescribed, and recognise signs of DVT and pulmonary embolism; assess competency annually and retain records.","Audit ten random surgical patient records monthly to verify that DVT risk scores are documented, appropriate prophylaxis was initiated within the prescribed timeframe, and there is evidence of daily monitoring; report compliance rates to the surgical department head."]'::jsonb where oe_code = 'COP.12.e';

update public.shco_full_oes set achieve_tips = '["Develop a restraint policy covering indications for use, types of permissible restraints, duration limits, consent requirements, monitoring frequency, and documentation requirements; align the policy with patient rights and applicable legal standards.","Require a doctor''s written order specifying the type, duration, and reason for restraint before any restraint is applied; document the order in the patient record and obtain consent from the patient or legal guardian.","Train all nursing staff in safe restraint application, monitoring (circulation, skin integrity, psychological status), and de-escalation alternatives; assess competency at induction and annually; retain training and assessment records.","Conduct a daily nursing audit of every restrained patient to verify that the restraint order is current, monitoring documentation is complete, and the least restrictive option is being used; report any non-compliances to the nursing head immediately."]'::jsonb where oe_code = 'COP.12.f';

update public.shco_full_oes set achieve_tips = '["Adopt a validated pain assessment tool appropriate for different patient populations (Numeric Rating Scale for adults, FLACC for paediatric patients, Abbey Pain Scale for non-verbal patients) and make its use mandatory at every nursing assessment and after any pain-related intervention.","Develop a pain management protocol specifying escalation steps from non-pharmacological measures through analgesic ladders; include reassessment timelines after each intervention and document compliance in the patient record.","Train all nursing and clinical staff in pain assessment and management protocols at induction and annually, including use of each pain scale and documentation requirements; retain training attendance and competency assessment records.","Conduct monthly audits of ten random patient records to verify that pain scores are documented at admission, at defined intervals, and after every pain intervention; calculate compliance rates and report findings to the quality committee with corrective actions."]'::jsonb where oe_code = 'COP.13.a';

update public.shco_full_oes set achieve_tips = '["Implement a pain re-assessment policy requiring nursing staff to reassess pain within 30 minutes of administering any analgesic or initiating a non-pharmacological pain measure; document the re-assessment score alongside the intervention in the patient record.","Develop a nurse-initiated analgesic protocol (within defined prescribing authority) for common pain situations, allowing nursing staff to give first-line analgesics without delay; document every administration with dose, route, time, and post-administration pain score.","Train all clinical and nursing staff in titration principles — starting low, reassessing frequently, and escalating doses based on patient response — and document their competency assessment in their personnel files.","Audit ten random inpatient records monthly to verify that post-intervention pain reassessment scores are present and show a downward trend; calculate the percentage of patients achieving a pain score below the target threshold and report this as a quality indicator."]'::jsonb where oe_code = 'COP.13.b';

update public.shco_full_oes set achieve_tips = '["Map the rehabilitation services required to support the organisation''s clinical scope (e.g., physiotherapy for surgical and orthopaedic patients, speech therapy for stroke patients, occupational therapy for paediatric patients) and confirm that each service is either available in-house or accessible through a documented referral arrangement.","Develop written rehabilitation SOPs for each major patient category (post-surgical, neurological, paediatric) specifying assessment methods, goal-setting frameworks, frequency of sessions, and discharge criteria.","Train clinical and nursing staff to refer patients for rehabilitation assessment within a defined timeframe (e.g., within 24 hours of admission for stroke patients) and document the referral and response in the patient record.","Audit ten random rehabilitation patient records monthly to verify that rehabilitation assessments were initiated within the defined timeframe, goals are documented, and patient progress is measured against the goals; report compliance rates to the quality committee."]'::jsonb where oe_code = 'COP.13.c';

update public.shco_full_oes set achieve_tips = '["Establish a formal rehabilitation team structure (physician, physiotherapist, occupational therapist, nurse, speech therapist as applicable) with written terms of reference for multidisciplinary collaboration on rehabilitation care planning.","Implement a unified rehabilitation care plan document in the patient record that is co-authored and co-signed by each team member, specifying individual roles, therapy goals, and planned session frequency.","Hold a weekly rehabilitation team meeting for complex rehabilitation patients to review progress, adjust goals, and update the care plan; retain meeting notes in the patient record as evidence of collaborative planning.","Audit ten random rehabilitation patient records monthly to verify that a multidisciplinary care plan is present and has contributions documented from each relevant discipline; report cases where collaboration is missing to the department head for corrective action."]'::jsonb where oe_code = 'COP.13.d';

update public.shco_full_oes set achieve_tips = '["Implement a standardised nutritional screening tool (e.g., Malnutrition Universal Screening Tool — MUST, or NRS-2002) for every patient within 24 hours of admission; document the screening score and nutritional risk category in the patient record.","Develop a written protocol specifying that any patient identified as nutritionally at-risk receives a full nutritional assessment by a registered dietitian within 48 hours of screening; document the assessment findings and dietary recommendations in the patient file.","Train all ward nursing staff to administer the nutritional screening tool accurately at induction and annually; conduct quarterly observed assessments to verify correct tool usage and retain competency records.","Track the percentage of admitted patients screened for nutritional risk within 24 hours as a monthly quality indicator; report compliance rates to the quality committee and document corrective actions taken when the target is not achieved."]'::jsonb where oe_code = 'COP.13.e';

update public.shco_full_oes set achieve_tips = '["Establish a multidisciplinary nutrition care team (treating physician, dietitian, nurse, and pharmacologist for parenteral nutrition cases) and develop a written policy requiring collaborative development of the therapeutic diet for every at-risk patient.","Create a standardised therapeutic diet prescription form co-signed by the treating doctor and dietitian, specifying caloric targets, macronutrient ratios, consistency modifications, and any therapeutic restrictions; file it in the patient record.","Set up a daily dietitian round for patients on therapeutic diets; document the dietitian''s assessment, dietary tolerance, and any plan modifications in the patient record; communicate updates to the nursing staff at each meal service.","Audit ten random patient records of nutritionally at-risk patients each month to verify that a collaborative therapeutic diet plan is documented, dietary intake is monitored, and plan revisions are made in response to the patient''s intake and clinical progress; report compliance rates to the quality committee."]'::jsonb where oe_code = 'COP.13.f';
