-- MOM Chapter: Management of Medication
-- 52 OEs x 4 tips each

update public.shco_full_oes set achieve_tips = '["Develop and maintain an approved formulary list tailored to your patient case mix and available clinical services, with a formal review at least annually by the pharmacy and therapeutics committee.","Create an SOP for adding new drugs to the formulary, including the approval workflow, and train all prescribers on how to access and use the updated formulary.","Maintain a signed and dated formulary document that is version-controlled and accessible at all prescription points; assessors will verify both the document and staff awareness.","During staff interviews, nurses and doctors should be able to name the process for requesting a non-formulary drug — rehearse this scenario in monthly team briefings."]'::jsonb where oe_code = 'MOM.1.a';

update public.shco_full_oes set achieve_tips = '["Constitute a formal multidisciplinary pharmacy and therapeutics committee with defined membership (physician, pharmacist, nurse, administrator) and document its terms of reference.","Hold committee meetings at a minimum quarterly frequency; maintain signed minutes recording decisions on formulary changes, medication policies, and incident reviews.","Display the committee''s approved written policies at the pharmacy and nursing stations so staff can reference them during daily operations.","Be prepared for assessors to observe whether staff follow committee-approved guidance — conduct mock drills and confirm all nursing and pharmacy staff can cite the relevant SOP."]'::jsonb where oe_code = 'MOM.1.b';

update public.shco_full_oes set achieve_tips = '["Draft a written procedure that clearly differentiates the procurement pathway for formulary medications versus non-formulary medications, including required approvals and documentation.","Train the purchase and pharmacy teams on the non-formulary requisition process and keep requisition forms on file as evidence of compliance.","Maintain a procurement register that logs every non-formulary drug request with date, requestor, clinical justification, approval status, and quantity purchased.","Conduct a quarterly internal audit of procurement records to confirm all purchases follow the approved procedure; file audit reports as audit-ready evidence for assessors."]'::jsonb where oe_code = 'MOM.1.c';

update public.shco_full_oes set achieve_tips = '["Create a written SOP detailing how medications can be obtained when the pharmacy is closed, including the name and contact details of the on-call pharmacist or designated responsible person.","Identify a secure after-hours drug cabinet or satellite stock and document the list of medications kept there, with clear access control and a log for after-hours dispensing.","Train all night and weekend nursing staff on the after-hours medication access procedure; document training attendance and conduct at least one simulation drill every six months.","Keep a logbook of every after-hours medication access event with the time, drug name, quantity taken, staff name, and next-day pharmacy reconciliation signature."]'::jsonb where oe_code = 'MOM.1.d';

update public.shco_full_oes set achieve_tips = '["Document a policy specifying the clinical criteria for selecting and using implantable prostheses and medical devices, including brand equivalence and surgeon qualification requirements.","Maintain a vendor-approved list and ensure purchase orders for implants are matched against this list before procurement.","Create an implant requisition and consent workflow that requires surgeon sign-off on the clinical indication before procurement is initiated, and file all completed forms.","Train operating room and purchase staff on the criteria for implant selection; assessors may ask staff to explain how a specific implant type gets approved for use."]'::jsonb where oe_code = 'MOM.1.e';

update public.shco_full_oes set achieve_tips = '["Run a monthly report of all medications prescribed and cross-reference against the approved formulary to identify off-formulary prescribing patterns.","Share formulary adherence data at the pharmacy and therapeutics committee meeting, naming the top non-formulary drugs and discussing clinical justification or formulary update.","Place the current formulary in a prominent, easily searchable format (printed binder or digital portal) at every doctor''s workstation to remove barriers to adherence.","When non-formulary drugs are unavoidably prescribed, document the clinical justification in the medical record — this demonstrates good practice even where adherence is imperfect."]'::jsonb where oe_code = 'MOM.1.f';

update public.shco_full_oes set achieve_tips = '["Designate clean, lockable storage areas for medications in every care area; label shelves clearly and ensure temperature, humidity, and light conditions match manufacturer specifications.","Conduct daily temperature logs for refrigerated medications and room-temperature medication stores; assign a responsible staff member per shift and file completed logs monthly.","Perform a weekly physical inspection of all medication storage areas covering cleanliness, lock status, expired stock, and labelling; document results in an inspection register.","During assessments, staff should be able to walk assessors through storage conditions and explain the manufacturer-specified requirements for at least two common refrigerated drugs."]'::jsonb where oe_code = 'MOM.2.a';

update public.shco_full_oes set achieve_tips = '["Implement a First Expiry First Out (FEFO) stocking system for all medication storage areas and train pharmacy and ward staff on correct rotation practice.","Set a minimum and maximum stock level for each medication and create a reorder trigger system so stock-outs and overstocking are both prevented.","Conduct a bi-monthly physical stock count and reconcile against the pharmacy dispensing records; retain count sheets as inventory control evidence.","Create an SOP for handling damaged, contaminated, or mislabelled stock, including quarantine procedures, and train all pharmacy staff; assessors will look for a functioning quarantine area."]'::jsonb where oe_code = 'MOM.2.b';

update public.shco_full_oes set achieve_tips = '["Publish a formally approved list of all high-risk and Look-Alike Sound-Alike (LASA) medications specific to your hospital and post it at the pharmacy dispensing counter and all nursing stations.","Apply clear, standardised visual alerts — tall-man lettering labels, red stickers, or physical segregation — to all LASA medications in storage to prevent pick errors.","Store high-alert drugs such as concentrated electrolytes and anticoagulants in a clearly marked, segregated section; never store them with routine medications.","Train all pharmacy and nursing staff on the high-alert and LASA drug list; assessors will observe storage areas and conduct staff interviews to verify recognition of these drugs."]'::jsonb where oe_code = 'MOM.2.c';

update public.shco_full_oes set achieve_tips = '["Identify every clinical area where high-risk medications are clinically necessary (e.g., ICU, OT, emergency) and formally authorise those as the only permitted storage locations.","Restrict access to high-risk medication storage to authorised clinical staff only; use locks, key registers, or access codes and maintain an access log.","Conduct monthly unannounced checks to confirm high-risk drugs have not migrated to non-authorised areas; document findings and corrective actions taken.","Collect and present data on the number of high-risk medication access events per month and confirm all occurred in authorised areas — this serves as measurable outcome evidence for assessors."]'::jsonb where oe_code = 'MOM.2.d';

update public.shco_full_oes set achieve_tips = '["Define the list of emergency medications for each crash cart or emergency tray and document this list in a laminated card affixed to each cart.","Standardise the layout of all emergency medication trays across wards so nursing staff can locate any drug within seconds, regardless of which unit they are working in.","Create an SOP for emergency medication storage, including shelf-life requirements, temperature storage, and the process for replacing used or expired items.","Conduct a monthly emergency tray inspection and seal verification; retain completed checklists as evidence that the defined list is consistently maintained."]'::jsonb where oe_code = 'MOM.2.e';

update public.shco_full_oes set achieve_tips = '["Establish a daily emergency medication availability checklist for each ward and assign a named nurse each shift to verify and sign off that all items are present and in-date.","Create a same-shift replenishment protocol: any emergency medication used must be replaced before the end of the shift, with the pharmacist counter-signing the replenishment record.","Keep a log of every instance where an emergency drug was used and record the time from use to replenishment; track this metric monthly and present at committee meetings.","During assessments, staff should demonstrate they know what to do if an emergency medication is missing — practise this scenario in quarterly in-service sessions."]'::jsonb where oe_code = 'MOM.2.f';

update public.shco_full_oes set achieve_tips = '["Adopt and display the hospital''s rational prescribing guidelines at every doctor''s workstation, referencing national formulary guidance or relevant clinical protocols.","Develop an SOP that defines when polypharmacy review is triggered and train doctors and clinical pharmacists on how to conduct a medication appropriateness review.","Include rational prescribing as a standing agenda item in monthly clinical department meetings, sharing data on antibiotic use, polypharmacy, and high-cost medication trends.","Document prescribing training sessions for new medical staff at induction, covering rational use principles; maintain attendance registers for assessor review."]'::jsonb where oe_code = 'MOM.3.a';

update public.shco_full_oes set achieve_tips = '["Define the minimum required elements of a valid prescription in a written policy (patient name, ID, date, drug, dose, route, frequency, prescriber name, and signature) and circulate to all prescribers.","Attach a quick-reference prescription requirements card to every prescription pad or electronic order screen as a point-of-care reminder for clinical staff.","Train pharmacy staff to reject incomplete prescriptions and document rejections in a daily rejection log, which is reviewed weekly by the pharmacy in-charge.","Assessors will review a sample of medical records for prescription completeness — conduct an internal monthly audit of 20 prescriptions per ward and correct gaps immediately."]'::jsonb where oe_code = 'MOM.3.b';

update public.shco_full_oes set achieve_tips = '["Add a mandatory allergy and adverse drug reaction (ADR) field to every patient admission form, ensuring it is completed before any medication is prescribed.","Introduce a red allergy alert sticker system on the patient''s medical record cover, medication administration record (MAR), and wristband to flag known allergies at a glance.","Create an SOP requiring doctors to verbally confirm allergy status with the patient or their attendant before every new prescription, and document this confirmation in the notes.","During nursing staff interviews, assessors often ask how allergy information is communicated across shifts — ensure allergy status is a mandatory item in every handover checklist."]'::jsonb where oe_code = 'MOM.3.c';

update public.shco_full_oes set achieve_tips = '["Deploy drug interaction checking software or maintain a printed reference (e.g., drug interaction tables) at the pharmacy counter to flag potentially harmful combinations before dispensing.","Train clinical pharmacists to provide bedside or telephone support to prescribers for complex cases, and document all clinical pharmacy interventions in the patient file.","Set up a visual alert system in your electronic or paper-based prescribing system that prompts clinicians when a prescribed drug falls outside recommended dosage ranges for the patient''s age or weight.","Hold monthly case reviews of near-miss events related to prescribing errors and share learnings at clinical meetings — this demonstrates a functional prescribing support mechanism to assessors."]'::jsonb where oe_code = 'MOM.3.d';

update public.shco_full_oes set achieve_tips = '["Develop a written policy on verbal orders specifying that they are permitted only in emergencies, must be repeated back by the receiving nurse, and must be countersigned by the prescriber within a defined timeframe (e.g., 24 hours).","Train all nursing and medical staff on the read-back and countersignature requirement through a dedicated in-service session; document attendance and test comprehension.","Create a verbal order section in the patient''s medication administration record and ensure nurses document verbal orders in real-time, noting the prescribing doctor''s name and the repeat-back confirmation.","Assessors will check that verbal orders in medical records carry timely countersignatures — audit a sample of records monthly and flag any that exceed the defined countersignature deadline."]'::jsonb where oe_code = 'MOM.3.e';

update public.shco_full_oes set achieve_tips = '["Establish a monthly medication order audit programme using a standardised checklist covering rationality, completeness, legibility, allergy check, and dosage appropriateness across a random sample of patient records.","Assign the clinical pharmacist or a senior physician to lead the audit and compile findings into a structured report shared with department heads within five days of the audit.","Track key audit metrics over time — percentage of complete prescriptions, incidence of unsafe prescribing indicators — and display trend charts at pharmacy and clinical governance meetings.","Maintain all audit reports in a dedicated file; assessors want to see evidence that audits are systematic, periodic, and acted upon — not just a one-time exercise before the assessment."]'::jsonb where oe_code = 'MOM.3.f';

update public.shco_full_oes set achieve_tips = '["Document every corrective or preventive action arising from a prescription audit in a CAPA (Corrective and Preventive Action) register, including the responsible person and target closure date.","After implementing a corrective action, re-audit the same area after 30–60 days to verify effectiveness and record re-audit results as before-and-after comparison evidence.","Share CAPA outcomes at the pharmacy and therapeutics committee meeting and record decisions in the minutes; this demonstrates a closed-loop improvement process to assessors.","Present trend data showing reduction in audit deficiencies over consecutive audit cycles — measurable improvement in prescribing quality is the strongest evidence for this achievement OE."]'::jsonb where oe_code = 'MOM.3.g';

update public.shco_full_oes set achieve_tips = '["Implement a structured medication reconciliation form that is completed at every transition point: admission, transfer between units, and discharge; file the completed form in the medical record.","Train all admitting nurses and doctors to conduct medication reconciliation within two hours of a patient''s arrival in a new care area, and document the date and time of reconciliation.","Include a medication reconciliation step in the discharge summary template so that the patient''s home medications are reviewed against hospital-prescribed drugs before they leave.","During assessments, staff will be asked how medication changes are communicated at handover — ensure medication reconciliation is a standing item on every shift handover checklist."]'::jsonb where oe_code = 'MOM.3.h';

update public.shco_full_oes set achieve_tips = '["Maintain a current list of authorised prescribers (doctors with valid registration and hospital credentials) and share it with the pharmacy so only prescriptions from authorised individuals are dispensed.","Create an SOP stating that pharmacy staff must verify the prescriber''s designation on any unfamiliar prescription and document the verification check in the dispensing record.","Train ward clerks and nursing staff that only credentialed doctors and authorised nurse practitioners (where applicable) may enter medication orders, and immediately escalate any unauthorised order.","Assessors may ask staff who is permitted to write medication orders — ensure all nursing and pharmacy staff can correctly name authorised categories without hesitation."]'::jsonb where oe_code = 'MOM.4.a';

update public.shco_full_oes set achieve_tips = '["Designate a specific, consistent section in every patient''s medical record for all medication orders (e.g., a dedicated medication order sheet or electronic order module) and train all staff to write orders only there.","Ensure every medication order sheet is pre-printed with the patient''s name and unique hospital ID number so there is no risk of orders being filed in the wrong patient record.","Conduct a monthly random review of 15–20 medical records to verify that all medication orders are in the designated location and correctly identify the patient; document results.","If assessors find orders written on loose notes or in non-standard locations, it is an immediate deficiency — reinforce through nurse briefings that ad hoc ordering locations are not acceptable."]'::jsonb where oe_code = 'MOM.4.b';

update public.shco_full_oes set achieve_tips = '["Post a sample of a correctly completed medication order at every doctor''s writing station as a visual standard, showing required legibility, date/time format, and signature placement.","Train pharmacists and ward nurses to return any illegible, undated, untimed, or unsigned medication order to the prescriber immediately for correction before it is dispensed.","Maintain a record of returned or rejected medication orders; analyse patterns monthly to identify which prescribers or units most frequently produce non-compliant orders, then address with targeted training.","In monthly chart audits, specifically score each order for legibility, date, time, and signature — track the compliance rate and demonstrate improvement over audit cycles."]'::jsonb where oe_code = 'MOM.4.c';

update public.shco_full_oes set achieve_tips = '["Design or update the medication order form to include mandatory fields for drug name, route, strength, and frequency/time so incomplete orders cannot be inadvertently accepted.","Train pharmacy staff to use a four-point verification checklist (name, route, strength, frequency) before accepting any order for dispensing and to return orders missing any element.","Conduct a monthly audit of dispensed orders to confirm all four required elements are present in 100% of orders; report the compliance rate to the pharmacy committee.","Assessors may pick a random medication order from the file and ask the nurse to verify its completeness — practise this scenario in ward training so staff can confidently walk through all four elements."]'::jsonb where oe_code = 'MOM.4.d';

update public.shco_full_oes set achieve_tips = '["Develop a detailed dispensing SOP covering the five rights of dispensing (right patient, drug, dose, route, time), double-check procedures for high-risk drugs, and documentation requirements.","Implement a mandatory second-pharmacist or senior technician check before dispensing any high-risk, controlled, or high-dose medication, and record the checker''s initials on the dispensing label.","Conduct monthly dispensing accuracy checks by auditing a sample of dispensed medications against original orders; track the error rate and present findings at pharmacy meetings.","Train all dispensing staff on the SOP at induction and through bi-annual refresher sessions; maintain training records with assessment scores as evidence of competency."]'::jsonb where oe_code = 'MOM.5.a';

update public.shco_full_oes set achieve_tips = '["Subscribe to drug regulatory authority recall alerts and designate a pharmacist as the recall focal point who receives notifications and initiates the recall response within 24 hours.","Develop and practise a medication recall SOP covering immediate quarantine of affected batches, patient exposure assessment, prescriber notification, and return to supplier documentation.","Maintain a recall register recording every recall event: drug name, batch number, quantity affected, date of quarantine, disposal or return date, and whether any patients were exposed.","After each recall event, brief the pharmacy team on what happened and what was learned; file the debrief record as evidence that recalls are handled as safety incidents, not routine returns."]'::jsonb where oe_code = 'MOM.5.b';

update public.shco_full_oes set achieve_tips = '["Set a near-expiry trigger date — typically three to six months before expiry — and create a near-expiry monitoring register listing all affected stock with expiry dates and responsible action owner.","Apply yellow ''near-expiry'' stickers to flagged medications and move them to the front of shelves (FEFO) so they are used before newer stock, reducing waste.","Establish a process to return near-expiry medications to suppliers or transfer to higher-consumption facilities before they expire; document all transfers with date, quantity, and destination.","Conduct a monthly near-expiry review and report the quantity of medications that expired and had to be discarded; use this data as a performance indicator to improve forecasting and ordering."]'::jsonb where oe_code = 'MOM.5.c';

update public.shco_full_oes set achieve_tips = '["Create a labelling SOP specifying that every dispensed medication must carry a label showing patient name, hospital ID, drug name, strength, dose, route, frequency, and dispensing date.","Print pre-formatted dispensing labels from the pharmacy management system and verify the label against the original prescription before attaching it to the medication package.","Conduct random daily checks of five to ten dispensed medications to confirm all required label elements are present; document checks in a dispensing quality register.","Train nurses to refuse any unlabelled medication received from the pharmacy and return it immediately for proper labelling — assessors will verify labelled medications at ward level during site visits."]'::jsonb where oe_code = 'MOM.5.d';

update public.shco_full_oes set achieve_tips = '["Implement a mandatory independent double-check system for all high-risk medication orders where a second pharmacist verifies the drug, dose, patient, and route before the order is dispensed.","Create a high-risk medication verification checklist form and attach a completed copy to each dispensed high-risk drug package; file a duplicate in the pharmacy dispensing record.","Train all pharmacy staff on which drugs trigger the double-check requirement by maintaining a posted high-risk drug list at the dispensing counter and testing staff awareness quarterly.","Assessors will observe the dispensing process and interview pharmacy staff — ensure every staff member can correctly identify the high-risk drug list and demonstrate the double-check procedure."]'::jsonb where oe_code = 'MOM.5.e';

update public.shco_full_oes set achieve_tips = '["Develop a written SOP for medication returns covering eligibility criteria (e.g., sealed, within expiry, correct temperature storage), documentation requirements, and restock or disposal pathways.","Provide nursing staff with a standardised medication return form that records patient name, drug, quantity, reason for return, condition of the medication, and accepting pharmacist signature.","Maintain a returns register in the pharmacy and cross-reference with ward records monthly to verify that all returned medications are accounted for and correctly processed.","Train both ward nurses and pharmacy staff on return procedures at induction; during assessments staff should be able to describe what happens to a partially used medication pack that is no longer needed."]'::jsonb where oe_code = 'MOM.5.f';

update public.shco_full_oes set achieve_tips = '["Establish and train all nursing staff on the five rights of medication administration (right patient, drug, dose, route, time) and add a sixth right — right documentation — to the hospital''s standard protocol.","Create an SOP for high-alert medication administration that mandates a two-nurse independent check before administration, with both nurses signing the medication administration record (MAR).","Conduct monthly observation rounds where a senior nurse observes a junior nurse administering medications and documents compliance with the administration protocol.","Assessors will directly observe medication administration and interview nurses about the procedure — practise the full administration sequence in monthly ward-based simulations."]'::jsonb where oe_code = 'MOM.6.a';

update public.shco_full_oes set achieve_tips = '["Develop an SOP that requires any prepared medication to be immediately labelled with drug name, strength, and preparation time before a second medication is drawn up or prepared.","Place a permanent visual prompt at every medication preparation area reminding staff: ''Label before you prepare the next drug'' — laminate and affix this to the preparation tray or counter.","Train all nursing and pharmacy staff on the one-at-a-time preparation and labelling rule during induction and repeat in bi-annual refreshers; keep training attendance records.","During assessor observation, staff will be watched preparing medications — conduct regular supervisory spot-checks to confirm no nurse leaves a prepared, unlabelled syringe or bag unattended."]'::jsonb where oe_code = 'MOM.6.b';

update public.shco_full_oes set achieve_tips = '["Implement a two-identifier patient identification policy (full name plus hospital ID or date of birth) that must be verified verbally and against the wristband before every medication administration.","Train all nursing staff on the wristband check protocol and ensure wristbands are applied to every patient at admission; missing wristbands must be replaced immediately and documented.","Add patient identification confirmation as a mandatory step in the medication administration record (MAR) — nurses sign or initial the MAR only after completing the identity check.","Assessors will ask nurses to demonstrate the patient identification process at the bedside — practise this during monthly ward simulation drills to ensure it is second-nature to all staff."]'::jsonb where oe_code = 'MOM.6.c';

update public.shco_full_oes set achieve_tips = '["Train all medication-administering nurses and doctors to read the medication order, then physically inspect the drug (label, expiry, appearance, packaging integrity) before administration — and never skip either step.","Create a bedside administration checklist that prompts staff to confirm the drug against the order and inspect its physical condition; attach the checklist to the MAR folder.","Document any physical inspection failure (e.g., discoloured injection, broken seal) in the incident reporting system and return the drug to the pharmacy; analyse these events monthly.","During assessments, staff will be asked to walk through the pre-administration verification process — ensure every nurse can describe both order verification and physical inspection steps without prompting."]'::jsonb where oe_code = 'MOM.6.d';

update public.shco_full_oes set achieve_tips = '["Incorporate a mandatory three-point verification step in the MAR: before picking the drug, before preparing it, and before administering it — each step requiring the nurse to check strength, route, and time against the order.","Post the administration verification checklist at every medication trolley and require nurses to initial each verification step in the MAR for every medication given.","Conduct monthly audits of MARs to confirm the three verification steps are consistently documented; report compliance rates to the nursing department head.","During training sessions, role-play common errors — such as administering a drug via the wrong route — so staff internalise the importance of re-reading the order at each verification step."]'::jsonb where oe_code = 'MOM.6.e';

update public.shco_full_oes set achieve_tips = '["Procure and deploy colour-coded, non-interchangeable connectors for IV, enteral, and epidural lines in all clinical areas where multiple infusions are used simultaneously.","Create a visual guide showing correct tubing connections for the most common medication delivery routes used in your facility and laminate it for display in the ICU, OT, and all inpatient wards.","Train all nursing staff on catheter and tubing mis-connection risks and prevention during induction and at bi-annual competency refreshers; document attendance and competency sign-off.","Investigate and formally report any tubing mis-connection near-miss or error as a critical incident; present the investigation findings at a clinical safety meeting and implement corrective actions."]'::jsonb where oe_code = 'MOM.6.f';

update public.shco_full_oes set achieve_tips = '["Use a standardised medication administration record (MAR) for every patient and ensure nurses sign immediately after administering each drug, including the exact time of administration.","Define the documentation requirements in an SOP: drug name, dose given, route, time, administering nurse''s signature, and any patient response or refusal must all be recorded.","Conduct weekly spot audits of MARs across wards to verify timely and complete documentation; share results with ward sisters and set a target of 100% MAR completion.","Train nursing staff that retrospective or pre-emptive entries in the MAR are not acceptable — assessors will check timestamps and may ask nurses about their documentation practice."]'::jsonb where oe_code = 'MOM.6.g';

update public.shco_full_oes set achieve_tips = '["Develop a written policy governing patient self-administration, specifying which medications may be self-administered (e.g., insulin by diabetic patients), the patient competency assessment process, and documentation requirements.","Before allowing self-administration, assess and document the patient''s competency through a structured checklist covering knowledge of the drug, correct technique, and ability to recognise adverse effects.","Educate patients on correct self-administration technique and have them demonstrate it back to the nurse; document the teach-back session and the patient''s demonstrated competency in the medical record.","Store self-administered medications securely at the bedside in a locked personal medication box and conduct daily nursing checks to ensure only approved medications are being self-administered."]'::jsonb where oe_code = 'MOM.6.h';

update public.shco_full_oes set achieve_tips = '["Establish a policy requiring that any medication a patient brings from home is identified, assessed for compatibility with hospital treatment, and either stored securely by the pharmacy or documented as approved for continued use.","Create a patient-brought medication assessment form where the admitting nurse lists each home medication, the prescribing doctor reviews it, and the disposition (continue, hold, or discontinue) is clearly recorded.","Measure and report the percentage of patients with home medications who received a formal pharmacist or physician review within 24 hours of admission as a monthly compliance metric.","Provide brief patient education at admission on the hospital''s home medication policy so patients understand they must disclose all drugs including supplements and over-the-counter medications; document this counselling."]'::jsonb where oe_code = 'MOM.6.i';

update public.shco_full_oes set achieve_tips = '["Define in a written SOP which medications require post-administration monitoring, specify the type of monitoring (vital signs, blood glucose, pain score, lab values), the frequency, and the minimum observation window.","Create a post-administration monitoring section in the nursing care record or MAR where nurses document patient response after each high-risk or new medication is given.","Train nursing staff to recognise common adverse reactions for the top 20 medications used in each ward and document any observed reactions immediately in the medical record and incident system.","Assessors will review medical records for evidence of post-administration monitoring entries — conduct monthly chart audits and provide targeted feedback to nurses who do not consistently document patient responses."]'::jsonb where oe_code = 'MOM.7.a';

update public.shco_full_oes set achieve_tips = '["Create a medication review workflow where the prescribing doctor is notified of any abnormal patient response to a medication within a defined timeframe (e.g., one hour for acute reactions) and a review is documented in the notes.","Document every medication change in the patient''s medical record with a clear clinical rationale, including what monitoring finding prompted the change and the new therapy decision.","Train nurses to proactively communicate monitoring findings to doctors using a structured SBAR (Situation, Background, Assessment, Recommendation) communication tool; document the communication and response.","Conduct case reviews of patients whose medications were changed during admission and use these as teaching cases in ward rounds to reinforce the monitoring-to-adjustment cycle for all staff."]'::jsonb where oe_code = 'MOM.7.b';

update public.shco_full_oes set achieve_tips = '["Implement a simple, non-punitive reporting form for near-miss events, medication errors, and adverse drug reactions (ADRs) and place copies at every nursing station and in the pharmacy.","Train all clinical staff that reporting near-misses is a safety duty, not an admission of fault, and demonstrate that reports lead to system improvements rather than individual blame.","Ensure the pharmacovigilance officer or designate reviews every ADR report within 48 hours and enters it into the national ADR reporting system (e.g., Vigiflow) where required.","Assessors will check both the number and quality of incident reports — a zero-report rate signals under-reporting, not a safe environment; aim for a steady stream of near-miss reports as a sign of a healthy safety culture."]'::jsonb where oe_code = 'MOM.7.c';

update public.shco_full_oes set achieve_tips = '["Set a defined reporting timeframe in your SOP — for example, all medication errors must be reported to the pharmacy or patient safety officer within 24 hours and analysed within 72 hours.","Assign a pharmacovigilance or medication safety officer responsible for collating all near-miss, error, and ADR reports, conducting root cause analysis, and escalating serious events to management.","Use a standardised analysis template (e.g., fishbone or 5-Why analysis) for every reported event; retain completed analysis forms in a dedicated safety file accessible for assessment.","Report summary data — number of events, categories, severity, and trend — at the pharmacy and therapeutics committee meeting each quarter and record in the minutes."]'::jsonb where oe_code = 'MOM.7.d';

update public.shco_full_oes set achieve_tips = '["Log every corrective or preventive action arising from a medication safety event in a CAPA register with a named owner, implementation date, and verification method.","After implementing a corrective action, re-measure the specific safety metric that triggered the event (e.g., wrong-drug incident rate) to demonstrate measurable improvement.","Share closed CAPA outcomes with frontline nursing and pharmacy staff through a monthly ''lessons learned'' bulletin so the whole team benefits from individual event analyses.","Assessors will look for evidence that actions are implemented, not just planned — ensure every CAPA entry in the register has a completed and verified closure section before the assessment date."]'::jsonb where oe_code = 'MOM.7.e';

update public.shco_full_oes set achieve_tips = '["Develop a comprehensive SOP for the handling of narcotics, psychotropics, chemotherapy, and radioactive agents covering procurement, receipt, storage, dispensing, administration, and disposal in compliance with applicable laws.","Train all staff who handle these agents on the specific legal and safety requirements for each category; document training with competency sign-off and retain for assessor review.","Establish strict access controls for narcotic and psychotropic storage: double-locked cabinets, dual-key access for nurses and pharmacists, and a real-time usage log maintained at the storage point.","Conduct a monthly audit of narcotic and psychotropic records comparing quantities received, dispensed, and remaining against physical counts; investigate and report any discrepancy immediately."]'::jsonb where oe_code = 'MOM.8.a';

update public.shco_full_oes set achieve_tips = '["Maintain an updated register of physicians authorised to prescribe narcotics and psychotropics, specifying their Narcotics User Certificate (or applicable credential) number, validity, and care area.","Create a prescriber authorisation checklist that pharmacy staff use to verify credentials before accepting any narcotic or psychotropic prescription from a new or infrequent prescriber.","For chemotherapy, document the oncologist''s qualification and specific chemotherapy prescribing approval in the medical staff credentials file, and cross-reference before dispensing any regimen.","Assessors may ask the pharmacist to demonstrate how prescriber authorisation is verified for a narcotic order — practise this scenario with pharmacy staff to ensure a confident, documented response."]'::jsonb where oe_code = 'MOM.8.b';

update public.shco_full_oes set achieve_tips = '["Store narcotics and psychotropics in a double-locked, wall-fixed metal cabinet with a dual-key system; one key held by the shift nurse and the other by the on-duty pharmacist or in-charge.","Maintain a running narcotic stock register at the storage point with entries for every receipt and issue, countersigned by two staff members for each transaction.","Chemotherapy drugs must be stored in a dedicated, labelled, locked refrigerator or cabinet separate from other medications, with a daily temperature log maintained by pharmacy staff.","Radioactive material storage must comply with radiation safety regulations; the storage area must be clearly labelled with radiation warning signs, and only trained and authorised staff may access it."]'::jsonb where oe_code = 'MOM.8.c';

update public.shco_full_oes set achieve_tips = '["Designate a dedicated, ventilated chemotherapy preparation area (biological safety cabinet) and ensure only trained and certified pharmacy staff or nurses prepare chemotherapy agents.","Create a chemotherapy preparation and administration SOP that specifies PPE requirements, spill management, and patient verification steps; train all involved staff and certify them annually.","Verify that staff administering chemotherapy have documented competency in cytotoxic handling, including IV access assessment and extravasation management; file competency certificates.","Establish a radioactive material handling protocol in compliance with the Atomic Energy Regulatory Board requirements; document every administration event with staff credentials, dose delivered, and waste disposal."]'::jsonb where oe_code = 'MOM.8.d';

update public.shco_full_oes set achieve_tips = '["Maintain a double-entry narcotic register that records every vial received, every dose dispensed to a patient, the patient name and MRD number, the administering nurse, and the witness; reconcile daily.","For psychotropics, maintain a separate register with the same detail level and submit monthly reports to the designated regulatory authority as required by the Narcotic Drugs and Psychotropic Substances Act.","Document chemotherapy administration in the patient''s medical record with the drug name, dose, batch number, route, date, and administering clinician''s signature; retain records for the legally required period.","Record radioactive agent usage in a radiation logbook maintained by the licensed radiation safety officer; all disposal must follow regulatory disposal protocols and be documented with disposal certificates."]'::jsonb where oe_code = 'MOM.8.e';

update public.shco_full_oes set achieve_tips = '["Develop a written policy and SOP for implantable prosthesis procurement that specifies vendor qualification criteria, prior approval requirements, CDSCO registration verification, and pricing caps or committee approval thresholds.","Create an implant request form that requires the surgeon to specify the clinical indication, product name, size, and preferred vendor before procurement is initiated, with HOD countersignature for high-value items.","Maintain an approved vendor register for implant suppliers and verify their CDSCO licence, post-market surveillance registration, and biocompatibility certification before placing orders.","Train the surgical team and purchase department on the written procurement guidance; assessors will verify that actual implant purchase orders follow the approved SOP and are supported by the required forms."]'::jsonb where oe_code = 'MOM.9.a';

update public.shco_full_oes set achieve_tips = '["Develop a structured patient and family counselling protocol for each category of implantable prosthesis, covering what the device is, why it is needed, expected outcomes, and any specific precautions or restrictions post-implantation.","Obtain and file a separate implant-specific informed consent that details the type of prosthesis, brand, potential complications, and alternatives discussed — distinct from the general surgical consent.","Document counselling sessions in the medical record and have the patient or family member sign an acknowledgement confirming they understood the information and had their questions answered.","Create patient education leaflets in the local language for the most commonly implanted devices (e.g., joint replacements, pacemakers, mesh) and provide a copy to the patient at discharge for reference."]'::jsonb where oe_code = 'MOM.9.b';

update public.shco_full_oes set achieve_tips = '["Design a standardised implant sticker or label — printed with the batch number, serial number, product name, and manufacturer — and attach it to three locations: the patient''s medical record, the implant master logbook, and the discharge summary.","Maintain a centralised implant master logbook in the OT or medical records department with one entry per implantation, cross-referenced to the patient''s hospital number.","Train scrub nurses and OT coordinators to capture and record implant details immediately after implantation while the packaging is still available, preventing data loss after the procedure.","Conduct a quarterly audit of a sample of implant cases to verify that all three records (medical record, logbook, discharge summary) consistently carry the correct batch and serial number; document audit findings."]'::jsonb where oe_code = 'MOM.9.c';
