-- HRM Chapter: Human Resource Management
-- 45 OEs × 4 tips each

update public.shco_full_oes set achieve_tips = '["Conduct an annual workforce gap analysis comparing current staff numbers and skill mix against patient load projections, and document findings with a signed review date.","During assessor visits, be ready to walk through your HR planning register and explain how staffing ratios are determined for each shift and department.","Maintain a rolling 12-month workforce plan updated quarterly; assessors will interview department heads to verify that staffing decisions align with patient care needs.","Keep records of all manpower requisitions linked back to the workforce plan so staff can demonstrate the chain of decision-making from plan to hire."]'::jsonb where oe_code = 'HRM.1.a';

update public.shco_full_oes set achieve_tips = '["Draft and approve a Recruitment SOP that specifies every step from vacancy identification to offer letter issuance, including timelines and approval authorities.","Maintain a recruitment register with entries for each vacancy showing date advertised, candidates shortlisted, interview panel members, and final selection rationale.","Assessors will review recruitment files and may ask staff about how the process works — ensure HR staff can explain each step without referring to notes.","Display the recruitment policy in HR office and include it in the HR induction pack so all panel members follow the same documented process."]'::jsonb where oe_code = 'HRM.1.b';

update public.shco_full_oes set achieve_tips = '["Post a department-wise sanctioned versus actual staff strength chart in each nursing station and department, updated monthly and signed by the department head.","Assessors will observe shift handovers and may count on-duty staff against the posted roster — ensure real-time staffing matches approved norms at all times.","Maintain duty rosters for at least the past 6 months, showing staff names, designations, and shift timings so records substantiate observed staffing levels.","Conduct a monthly HR compliance review where shortfalls in any department are escalated to administration with a corrective action plan on record."]'::jsonb where oe_code = 'HRM.1.c';

update public.shco_full_oes set achieve_tips = '["Document a formal contingency staffing plan covering scenarios such as mass leave, epidemic absences, and sudden surge in patient admissions, with activation triggers clearly stated.","Maintain a pre-approved on-call staff list per department that can be activated within 2 hours, and test this list during mock drills at least twice a year.","Track and report monthly metrics on unplanned absenteeism rate and time-to-fill temporary gaps; present trend data at HR committee meetings to show the plan is working.","Record each instance of an unplanned staffing shortage, the contingency measure used, and resolution time so assessors can see measurable outcomes of the plan."]'::jsonb where oe_code = 'HRM.1.d';

update public.shco_full_oes set achieve_tips = '["Create a Job Description (JD) template that includes reporting relationships, key responsibilities, qualifications required, and KPIs for every staff category, reviewed annually.","Ensure each employee''s personnel file contains a signed copy of their current JD and org chart position so credential verification and role clarity are immediately demonstrable.","During induction, have new hires sign that they have received and understood their JD and reporting structure; file this acknowledgement in their personal record.","Assessors will interview staff at all levels to confirm they know their supervisor and job scope — hold quarterly team briefings reinforcing reporting lines."]'::jsonb where oe_code = 'HRM.1.e';

update public.shco_full_oes set achieve_tips = '["Implement a pre-employment background verification checklist covering identity, previous employment, criminal record, and credential authenticity, completed before the joining date.","Maintain a background check register logging each new hire, the verification agency or method used, date completed, and outcome — this record must be audit-ready at all times.","File verification certificates and police clearance letters (where applicable) in personnel files so assessors can cross-check during a document review without additional retrieval.","Establish a policy that no staff member handles patients until background verification is cleared, and document any interim arrangements with a risk approval signature."]'::jsonb where oe_code = 'HRM.1.f';

update public.shco_full_oes set achieve_tips = '["Draft a Code of Conduct document covering patient interaction, confidentiality, dress code, social media use, and professional behaviour, and have all staff sign it at induction.","Display summarised conduct norms in staff areas and patient care zones; assessors will observe whether staff behaviour is consistent with the documented code.","Conduct at least one annual refresher session on the Code of Conduct and record attendance; keep sign-in sheets in personnel files as evidence of compliance.","Assessors may ask staff to explain what the code of conduct requires — ensure all team leads can articulate the key provisions without prompting."]'::jsonb where oe_code = 'HRM.1.g';

update public.shco_full_oes set achieve_tips = '["Use a standardised exit interview form covering reasons for leaving, workplace concerns, and suggestions for improvement; have HR conduct the interview on the last working day.","Compile exit interview data quarterly into a trend report showing top reasons for attrition by department, and present this at the HR committee meeting with proposed actions.","Document corrective actions taken in response to exit feedback — e.g., policy changes or facility improvements — and track whether attrition rates improve over the next quarter.","Keep exit interview records confidential and numbered sequentially so assessors can verify that interviews are being conducted consistently across all departing staff."]'::jsonb where oe_code = 'HRM.1.h';

update public.shco_full_oes set achieve_tips = '["Develop a Disciplinary and Grievance Handling SOP that defines types of misconduct, escalation steps, timelines for resolution, and the appeal process — approved by management.","Maintain a grievance register with a unique case number for each complaint, recording date received, nature of grievance, actions taken, and closure date.","Ensure all staff are informed of the grievance mechanism at induction and that the process is posted on the staff notice board so assessors can confirm visibility.","File all disciplinary proceedings and their outcomes in a secure, confidential register; assessors may request to see anonymised records to verify the process is followed consistently."]'::jsonb where oe_code = 'HRM.1.i';

update public.shco_full_oes set achieve_tips = '["Design a structured induction checklist covering hospital policies, safety procedures, department tour, role-specific orientation, and NABH standards, completed within the first week of joining.","Obtain a signed induction completion form from every new hire and file it in their personnel record so assessors can verify induction was provided systematically.","Assessors will interview recently joined staff to confirm they received induction — ensure that all new employees can name key policies and safety procedures they were trained on.","Observe new staff during their initial weeks and document a supervisor''s feedback form on induction effectiveness, linking observations to the induction checklist topics."]'::jsonb where oe_code = 'HRM.2.a';

update public.shco_full_oes set achieve_tips = '["Write and approve a Training and Development Policy that covers mandatory training frequencies, nomination processes, budget provisions, and documentation requirements for all staff categories.","Maintain an annual training calendar shared with all departments, specifying topics, target groups, trainers, and scheduled dates so staff can plan attendance in advance.","Assessors will review the training policy document and may ask department heads how training needs are identified — ensure HODs can explain the Training Needs Assessment (TNA) process.","Verify that the policy is accessible to all staff digitally or in a printed form in each department; collect acknowledgement signatures that staff have read and understood it."]'::jsonb where oe_code = 'HRM.2.b';

update public.shco_full_oes set achieve_tips = '["Map each staff role''s JD to a training matrix that lists mandatory competencies and the corresponding training programmes; update this matrix whenever job descriptions change.","Before each training cycle, HR must cross-check completed training against the role-specific training matrix and ensure gaps are scheduled before the next assessment window.","File training completion certificates in each staff member''s personnel file so that credential verification during an assessment can confirm training aligns with the job description.","Conduct quarterly compliance reviews showing percentage of staff per department who have completed all role-specific training, with a corrective action plan for any below 90%."]'::jsonb where oe_code = 'HRM.2.c';

update public.shco_full_oes set achieve_tips = '["Schedule BLS/CPR training for all direct patient care staff during induction week and maintain a refresher schedule every 12 months, with dates and participant lists on record.","Keep original CPR certification cards or in-house training completion records in personnel files and a master CPR competency register updated after each session.","Assessors may observe a mock CPR scenario or interview staff — ensure all patient care staff can demonstrate correct chest compression technique and AED use without hesitation.","Track CPR certification expiry dates in a master register and send automated reminders 30 days before expiry so no staff member lapses into an uncertified status."]'::jsonb where oe_code = 'HRM.2.d';

update public.shco_full_oes set achieve_tips = '["Use a three-level training evaluation model: collect participant feedback immediately post-training, assess knowledge retention via a post-test, and observe on-the-job behaviour change after 30–60 days.","Maintain training effectiveness records showing pre- and post-assessment scores for each programme, and calculate a departmental training effectiveness rate to present at HR committee meetings.","If a training programme scores below an effectiveness threshold, document a revised training approach and re-evaluate within 60 days to demonstrate continuous improvement.","Assessors will look for evidence that training results in practice change — pair training records with quality indicator data (e.g., infection rates, incident reports) to show impact."]'::jsonb where oe_code = 'HRM.2.e';

update public.shco_full_oes set achieve_tips = '["Develop a Safety Training SOP that lists all mandatory safety topics, target staff groups, delivery frequency, and the responsible trainer for each topic area.","Conduct safety programme induction for every new hire within the first 3 days and document completion with a signed acknowledgement form filed in their personnel record.","Assessors will interview staff to check whether they can describe the hospital''s safety programme elements — hold monthly 10-minute safety stand-up reminders to reinforce knowledge.","Maintain a safety training compliance dashboard showing completion percentages by department, updated monthly so management can intervene when any area falls behind."]'::jsonb where oe_code = 'HRM.3.a';

update public.shco_full_oes set achieve_tips = '["Conduct a formal risk identification exercise for each department and build a risk-specific training module for the hazards identified (e.g., chemical exposure in labs, needle-stick in OT).","Train all relevant staff on handling, minimising, and reporting each identified risk; maintain attendance records and post-training competency assessments per risk category.","Post risk management quick-reference cards in relevant work areas so staff have immediate guidance; assessors will check whether displayed information matches formal training content.","Review risk training records annually against the facility''s current risk register to ensure training remains relevant as new risks emerge or existing ones are mitigated."]'::jsonb where oe_code = 'HRM.3.b';

update public.shco_full_oes set achieve_tips = '["Create and display a laminated incident reporting flowchart at each nursing station and department showing the exact steps staff must follow within the first 30 minutes of an incident.","Train all staff during induction on incident reporting procedures including near-miss reporting, and verify understanding through a short written test with results filed in personnel records.","Conduct a quarterly incident reporting drill by simulating a scenario and timing how quickly and accurately staff respond — document drill results and debrief actions.","Assessors may ask frontline staff what they would do if they discovered a medication error — ensure every staff member can name the immediate steps without looking at a poster."]'::jsonb where oe_code = 'HRM.3.c';

update public.shco_full_oes set achieve_tips = '["Develop an Occupational Safety Training SOP covering topics such as manual handling, ergonomics, PPE usage, sharps disposal, and chemical handling relevant to each department.","Schedule occupational safety training at least once per year for all staff and maintain attendance registers cross-referenced with department risk profiles.","Issue and document PPE provision to every relevant staff member; keep a PPE issue register showing item type, staff name, date issued, and acknowledgement signature.","Assessors will observe PPE compliance during the site visit — conduct unannounced spot checks each month to ensure staff are wearing PPE correctly and document results."]'::jsonb where oe_code = 'HRM.3.d';

update public.shco_full_oes set achieve_tips = '["Incorporate disaster management plan training into annual mandatory training for all staff, covering roles during internal and external disasters with clear department-wise assignments.","Maintain signed attendance records for every disaster preparedness session and store them with the Disaster Management Plan so assessors can cross-reference training with the plan.","Assessors will observe mock disaster drills and may question staff on their assigned roles — conduct at least two drills per year and debrief outcomes in writing.","Post department-specific disaster response cards outlining staff roles, evacuation routes, and escalation contacts in visible locations so staff can act without delay during a real event."]'::jsonb where oe_code = 'HRM.3.e';

update public.shco_full_oes set achieve_tips = '["Schedule fire safety and non-fire emergency (e.g., gas leak, electrical failure, bomb threat) training for all staff twice a year, with separate sessions for day and night shifts.","Conduct fire evacuation drills at least twice annually, document participant numbers, evacuation time achieved, and corrective actions for any procedural gaps observed.","Assessors will question staff on their designated assembly point and the first step when a fire alarm sounds — hold monthly reminders so all shifts retain this knowledge.","Maintain a fire drill register and training attendance log; ensure records reflect participation from all departments including housekeeping, kitchen, and security, not just clinical staff."]'::jsonb where oe_code = 'HRM.3.f';

update public.shco_full_oes set achieve_tips = '["Develop a Quality Improvement (QI) training module explaining the hospital''s QI framework, quality indicators, and how staff contribute to improvements at the departmental level.","Include QI orientation in the induction programme and conduct annual refresher training; maintain attendance records linking each staff member to the QI training they attended.","Display the current quality indicators and their performance trend on a department quality board so staff see real data and connect their daily work to quality outcomes.","Assessors will check whether frontline staff can describe at least one quality indicator relevant to their department — quiz staff regularly during team meetings to reinforce this awareness."]'::jsonb where oe_code = 'HRM.3.g';

update public.shco_full_oes set achieve_tips = '["Develop a formal Performance Appraisal SOP that describes the appraisal format, rating scale, reviewer qualifications, and the timeline for conducting reviews for each staff category.","Include performance appraisal process information in the induction programme and have new hires sign an acknowledgement confirming they understand how and when they will be evaluated.","Maintain appraisal schedules in HR and send department heads a reminder 4 weeks before appraisal due dates so no staff member''s appraisal is overdue during an assessment visit.","Assessors will ask staff if they are aware of the appraisal system — hold brief departmental briefings after each appraisal cycle summarising outcomes and next steps for the team."]'::jsonb where oe_code = 'HRM.4.a';

update public.shco_full_oes set achieve_tips = '["Define measurable performance criteria for each job category in the appraisal form, including clinical quality metrics, attendance, teamwork, and compliance with hospital protocols.","Share the appraisal criteria document with each staff member at induction and annually before the appraisal cycle begins so there are no surprises during the evaluation.","Ensure appraisal forms are standardised across the organisation, with role-specific sections, and retain completed forms in personnel files for at least 3 years for audit readiness.","Assessors may ask staff how their performance is measured — ensure department heads can name specific criteria used and explain how they link to organisational quality goals."]'::jsonb where oe_code = 'HRM.4.b';

update public.shco_full_oes set achieve_tips = '["Following each appraisal cycle, document an Individual Development Plan (IDP) for every staff member identifying training needs, career goals, and actions agreed between the employee and supervisor.","Track IDP completion rates as an HR metric presented quarterly — measure the percentage of staff with an active development plan and the percentage who completed planned development activities.","Link training nominations to appraisal outcomes so staff with identified skill gaps are automatically enrolled in relevant programmes before the next performance cycle.","Assessors will look for evidence that appraisals lead to action — prepare a summary report showing how many staff improved on development goals from the prior year''s appraisal."]'::jsonb where oe_code = 'HRM.4.c';

update public.shco_full_oes set achieve_tips = '["Define in the appraisal policy the exact frequency of reviews (e.g., probationary at 3 months, annual thereafter) and document each review date in both the personnel file and a central HR tracker.","Ensure every completed appraisal form is signed by both the appraiser and the appraisee, dated, and filed in the personnel record within 7 days of the appraisal meeting.","Generate a monthly HR dashboard report showing percentage of appraisals completed on time versus overdue; escalate overdue cases to department heads for immediate resolution.","Assessors will request appraisal records during document review — organise personnel files so that the most recent appraisal is the first document visible for each staff member."]'::jsonb where oe_code = 'HRM.4.d';

update public.shco_full_oes set achieve_tips = '["Establish an Occupational Health SOP that defines how staff health hazards are identified, how at-risk employees are flagged, and what wellness interventions are available, approved by the Medical Director.","Maintain an occupational health register listing staff who have been assessed for health hazards, the hazard type, assessment date, and any preventive or corrective action taken.","Conduct annual health awareness sessions on common occupational risks (e.g., musculoskeletal disorders, burnout, bloodborne pathogen exposure) and document attendance in personnel files.","Assessors will check whether health hazard data is being used to inform workplace changes — present examples where staff health findings led to procedural or ergonomic improvements."]'::jsonb where oe_code = 'HRM.5.a';

update public.shco_full_oes set achieve_tips = '["Schedule annual health check-ups for all staff by category (clinical, administrative, housekeeping) and maintain a master health check register with staff name, designation, date, and outcome.","File individual health check reports in each staff member''s personnel file under a dedicated health section; ensure results are treated as confidential and accessible only to authorised HR personnel.","Assessors will verify health check records and may ask staff when their last check-up was — send reminders 30 days before each staff member''s annual check-up anniversary.","Act on health check findings by referring staff with identified conditions to appropriate care, documenting the referral and follow-up in the occupational health register."]'::jsonb where oe_code = 'HRM.5.b';

update public.shco_full_oes set achieve_tips = '["Develop a Workplace Injury Management SOP covering immediate first aid, incident reporting, treatment access, and return-to-work planning for staff injured during duty hours.","Maintain a workplace injury register with entries for each incident including date, nature of injury, treatment provided, days lost, and corrective action taken to prevent recurrence.","Ensure all injured staff receive treatment promptly without financial barrier, and document that treatment was provided free of cost as a matter of policy accessible in the SOP.","Assessors may ask staff what would happen if they got a needle-stick injury — conduct quarterly drills covering the exact steps from exposure to post-exposure prophylaxis documentation."]'::jsonb where oe_code = 'HRM.5.c';

update public.shco_full_oes set achieve_tips = '["Develop and approve a Workplace Violence Prevention Policy covering definitions of violence, reporting mechanisms, immediate support for affected staff, and zero-tolerance disciplinary consequences.","Install CCTV in high-risk areas such as emergency, psychiatry, and cash counters; display signage that workplace violence will not be tolerated and that surveillance is active.","Train all staff, especially frontline and emergency personnel, in de-escalation techniques and the immediate steps to take if threatened or assaulted; maintain training attendance records.","Assessors will observe whether violence prevention measures are visible and operational — hold quarterly reviews of all reported incidents and demonstrate trends and corrective actions to the assessment team."]'::jsonb where oe_code = 'HRM.5.d';

update public.shco_full_oes set achieve_tips = '["Assign every staff member a unique personnel file ID and maintain files in a locked cabinet or secured HR system accessible only to authorised personnel, with an access log.","Create a personnel file checklist that lists every mandatory document (appointment letter, ID proof, qualifications, signed JD, appraisals, training records) and verify completeness for every file quarterly.","Implement a file confidentiality policy signed by all HR staff handling personal records, and include this as part of HR induction so assessors see a culture of data privacy.","Assessors will request personnel files during document review — ensure files are organised with a standard section order so any document can be retrieved within 2 minutes."]'::jsonb where oe_code = 'HRM.6.a';

update public.shco_full_oes set achieve_tips = '["Use a personnel file index that mandates inclusion of: photo ID, educational certificates, registration proof, appointment letter, signed JD, credential verification report, and latest health check result.","Verify all credentials — degrees, registration numbers, and previous employment — at the time of joining and file the verification evidence alongside the original copies in the personnel file.","Assessors will cross-check qualifications listed in the file against primary source verifications — ensure every credential has an accompanying verified confirmation (letter, online printout, or third-party certificate).","Conduct a semi-annual personnel file audit using the mandatory document checklist; document the audit findings and close any gaps within 30 days with HR sign-off."]'::jsonb where oe_code = 'HRM.6.b';

update public.shco_full_oes set achieve_tips = '["Create a Training Record Sheet for each staff member that logs every in-service training attended, with date, topic, trainer, duration, and a copy of the attendance register or certificate.","File training records in a dedicated training section within each personnel file so assessors can see at a glance the complete training history of any staff member.","Maintain a centralised HR training register that mirrors individual file records and allows HR to run reports on any staff member''s training history within minutes.","Cross-reference training records against mandatory training requirements annually to identify gaps and generate a catch-up training plan before any NABH assessment visit."]'::jsonb where oe_code = 'HRM.6.c';

update public.shco_full_oes set achieve_tips = '["File every completed appraisal form, performance improvement plan, commendation letter, and disciplinary warning in a chronological evaluation section within each staff member''s personnel file.","Ensure all evaluation documents are signed by the appraiser, countersigned by the department head, and dated before filing so records are legally defensible and audit-ready.","Conduct an annual file review to verify that appraisal records are complete and that evaluations have been carried out at the correct frequency for every staff member.","Assessors will check whether evaluation records reflect continuity — prepare a summary sheet at the front of each file showing the dates and outcomes of all appraisals to date."]'::jsonb where oe_code = 'HRM.6.d';

update public.shco_full_oes set achieve_tips = '["Develop a Credentialing and Privileging SOP that defines which medical professional categories are permitted to practice independently, based on applicable law and regulatory requirements.","Maintain a Privileging Register listing every independently practising medical professional with their registration number, qualification, and the specific privileges granted by the competent authority.","Assessors will verify that every doctor providing unsupervised care is listed in the privileging register — audit the register quarterly and remove or update listings when scope of practice changes.","Display the list of credentialed medical professionals in relevant departments so nursing and support staff know who is authorised to issue orders without supervision."]'::jsonb where oe_code = 'HRM.7.a';

update public.shco_full_oes set achieve_tips = '["Collect certified copies of degrees, registration certificates, training completion records, and experience letters for every medical professional at joining, and verify them with the issuing body before granting privileges.","Set up calendar reminders for registration renewal dates of all medical professionals and initiate re-verification 60 days before expiry, documenting the outcome in the personnel file.","Maintain a credential verification log showing each verification action taken, the source contacted, date of verification, and the officer who completed it so the process is traceable.","Assessors will cross-check credentials with the registration council database during the visit — ensure all registration numbers are current and the most recent renewal certificates are filed."]'::jsonb where oe_code = 'HRM.7.b';

update public.shco_full_oes set achieve_tips = '["Define clinical privilege categories (e.g., surgical procedures, prescription authority, diagnostic interpretation) and formally document which privileges are granted to each medical professional based on their verified credentials.","Issue each medical professional a signed Privilege Letter specifying exactly what they are authorised to do within the organisation, filed in both the personnel file and the privilege register.","Assessors will test whether privileges match actual practice by reviewing patient records against the treating doctor''s privilege list — audit a sample of patient files quarterly.","Review and revalidate privileges at least annually or after any significant event (e.g., complaint, long absence, scope change) and document the revalidation outcome formally."]'::jsonb where oe_code = 'HRM.7.c';

update public.shco_full_oes set achieve_tips = '["Distribute a current and signed scope-of-services document to each medical professional on joining and share the same document with department heads and nursing in-charges of all relevant units.","Conduct a brief orientation for all departments when a new medical professional joins, covering the services that person is authorised to provide so referrals and orders are appropriate.","Maintain signed acknowledgement from both the medical professional and relevant department heads confirming they have received and understood the scope-of-services document.","Assessors may ask nursing staff what services a particular doctor is authorised to provide — hold quarterly clinical team briefings reviewing any changes to medical professional scopes."]'::jsonb where oe_code = 'HRM.7.d';

update public.shco_full_oes set achieve_tips = '["Maintain a Nursing Privileging Register listing all nurses authorised to provide unsupervised patient care, with their registration council number, qualification level, and date of privilege grant.","Review the nursing privilege register whenever a nurse is promoted, changes unit, or completes additional qualification training, and update privileges in writing within 7 days.","Assessors will observe nursing staff performing care activities and cross-check against the privilege register — ensure every nurse on the floor is listed and that their listed privileges cover their observed duties.","Post a current list of independently practising nurses in each ward so charge nurses and doctors can quickly verify who is authorised to carry out specific care tasks unsupervised."]'::jsonb where oe_code = 'HRM.8.a';

update public.shco_full_oes set achieve_tips = '["At the time of joining, collect and verify educational certificates, nursing council registration, and prior employment letters for every nurse, and file original verification evidence in their personnel file.","Set up a registration renewal tracker for all nursing staff; initiate re-verification 60 days before a registration expires and document the updated certificate in the file immediately on receipt.","Maintain a nursing credential summary sheet in each file listing qualification, registration number, registration validity, and date last verified so assessors can confirm status at a glance.","Conduct a bi-annual credential audit for all nursing staff, comparing file records against the State Nursing Council database and correcting any discrepancies within 15 days."]'::jsonb where oe_code = 'HRM.8.b';

update public.shco_full_oes set achieve_tips = '["Define nursing privilege tiers (e.g., basic care, IV administration, triage assessment) and document in writing which tier each nurse is assigned based on their verified qualifications and experience.","Issue a signed Nursing Privilege Certificate to each nurse specifying authorised activities; retain a copy in the personnel file and the nursing privilege register.","Review nursing privileges whenever a nurse attends additional training or a new competency is assessed; update the privilege document within 7 days and obtain a new signature from the authorising authority.","Assessors will ask nurses what procedures they are and are not authorised to perform — conduct quarterly privilege awareness sessions so nurses can articulate their scope confidently."]'::jsonb where oe_code = 'HRM.8.c';

update public.shco_full_oes set achieve_tips = '["Issue each nurse a written scope-of-services document at joining detailing their authorised nursing activities, and share a department-level summary with the in-charge of every unit the nurse is deployed to.","Conduct a ward-level orientation whenever a nurse is transferred to a new department, briefing both the nurse and the receiving team on the nurse''s authorised services and any limitations.","Maintain signed acknowledgement records from both the nurse and the receiving department in-charge confirming that scope-of-services information has been communicated and understood.","Assessors will interview ward in-charges to verify they know which nurses under their supervision are authorised for specific tasks — hold monthly team briefings reviewing scope boundaries."]'::jsonb where oe_code = 'HRM.8.d';

update public.shco_full_oes set achieve_tips = '["Map all para-clinical roles (e.g., physiotherapists, radiographers, lab technicians, dietitians) against the applicable regulatory requirements to determine who may practice independently, and document this formally.","Maintain a Para-Clinical Privileging Register listing each authorised professional with their regulatory body registration number, qualification, scope of practice, and date of privilege grant.","Assessors will verify that para-clinical staff performing unsupervised procedures are listed in the privilege register — audit the register quarterly and remove anyone whose registration has lapsed.","Communicate the privileging process to all para-clinical department heads and ensure that only registered, credentialed staff are assigned to perform procedures that require independent authorisation."]'::jsonb where oe_code = 'HRM.9.a';

update public.shco_full_oes set achieve_tips = '["Collect degree certificates, regulatory registration documents, training records, and experience letters for every para-clinical professional at joining and verify authenticity with the issuing institution or council.","Create a Para-Clinical Credential Tracker spreadsheet with columns for staff name, qualification, registration number, validity date, verification date, and re-verification due date; update it continuously.","File all verification evidence in each professional''s personnel file with a cover sheet summarising credential status so assessors can complete a document review of any file within 5 minutes.","Conduct annual re-verification of all para-clinical registrations and document outcomes; treat lapsed registrations as a critical non-conformity requiring immediate suspension of independent practice."]'::jsonb where oe_code = 'HRM.9.b';

update public.shco_full_oes set achieve_tips = '["Define specific clinical privileges for each para-clinical category based on verified qualifications and regulatory scope (e.g., a physiotherapist may perform mobilisation but not prescribe medication), and document formally.","Issue a signed Privilege Letter to every para-clinical professional listing their authorised activities; retain copies in both the personnel file and a central para-clinical privilege register.","Assessors will check patient care records against assigned privileges — perform quarterly audits of para-clinical documentation to confirm that procedures recorded match the privileges granted.","Reassess privileges whenever a para-clinical professional completes additional specialisation or changes role, updating the Privilege Letter and register within 7 days of the change."]'::jsonb where oe_code = 'HRM.9.c';

update public.shco_full_oes set achieve_tips = '["Distribute a written scope-of-services summary to each para-clinical professional on joining and share the same document with the head of every department that interacts with or requests their services.","Conduct a brief orientation for referring departments each time a new para-clinical professional joins, clearly communicating what services that person is authorised to provide.","Maintain signed acknowledgement records from the para-clinical professional and all relevant department heads confirming receipt and understanding of the scope-of-services document.","Assessors will ask clinical staff whether they know what services a para-clinical colleague is authorised to deliver — hold cross-departmental briefings at least annually to refresh this knowledge."]'::jsonb where oe_code = 'HRM.9.d';
