-- HIC Chapter: Hospital Infection Control
-- 36 OEs x 4 tips each

update public.shco_full_oes set achieve_tips = '["Maintain a written Hospital Infection Prevention and Control (HIC) programme document that clearly outlines goals, scope, and responsibilities; review it at least annually and update it whenever new risks emerge.","Ensure assessors can immediately access the HIC programme document during visits — file it in a dedicated infection control binder kept at the nursing station or quality office.","Conduct quarterly internal audits against the HIC programme objectives and record findings in a logbook so staff can demonstrate ongoing programme implementation to assessors.","Brief all clinical and support staff during induction on the HIC programme goals so they can accurately describe programme aims and their own role when interviewed by assessors."]'::jsonb where oe_code = 'HIC.1.a';

update public.shco_full_oes set achieve_tips = '["Use the NABH Infection Control Assessment Tool checklist to formally score your programme every six months; document the scores, identify gaps, and record the improvement actions taken.","Assign the Infection Control Nurse to lead each assessment tool review cycle and file completed tool forms with dates and signatures so trend improvement is visible over time.","After each assessment tool review, prepare a one-page gap-closure summary and present it to the Infection Control Committee; retain minutes of this discussion as evidence.","Track your assessment tool scores on a wall-mounted dashboard in the infection control office so staff and assessors can see whether ratings are improving cycle over cycle."]'::jsonb where oe_code = 'HIC.1.b';

update public.shco_full_oes set achieve_tips = '["Constitute a multidisciplinary Infection Control Committee with members from medicine, nursing, microbiology, housekeeping, and administration; publish the committee''s terms of reference and meeting schedule on the hospital notice board.","Hold Infection Control Committee meetings at least quarterly; prepare formal agenda and minutes, file them chronologically, and ensure they are readily available for assessor review.","Designate a trained Infection Control Nurse or Officer to the Infection Control Team with clearly defined daily responsibilities; display their name and contact on every ward.","Maintain an attendance register for every committee meeting and cross-reference action items with responsible persons and deadlines so the team can demonstrate coordinated follow-up."]'::jsonb where oe_code = 'HIC.1.c';

update public.shco_full_oes set achieve_tips = '["Develop and implement an IEC (Information, Education, Communication) calendar for patients, visitors, and community members covering topics such as hand hygiene, respiratory etiquette, and safe disposal of waste.","Display visual IEC materials — posters, pamphlets, and digital displays — in OPD waiting areas, casualty, and patient wards in the local language to maximise community reach.","Document community outreach activities, including health camps and school visits on infection prevention, with attendance records and photographs filed in the IEC register.","Establish a written pandemic/outbreak response protocol that specifies activation triggers, communication channels, and coordination with local health authorities; train staff annually and record participation."]'::jsonb where oe_code = 'HIC.1.d';

update public.shco_full_oes set achieve_tips = '["Prepare an annual infection control budget proposal listing required PPE, disinfectants, surveillance tools, and training costs; obtain management approval in writing and retain the signed document.","Maintain a stock register for infection control consumables (gloves, masks, hand rub, colour-coded bags) with minimum stock levels defined; replenish before stocks fall below threshold.","Ensure assessors can observe functional hand hygiene stations — running water, soap, and alcohol-based hand rub — at every point of care; log any deficiency and corrective action taken.","Document management review of infection control resource requests in committee minutes so staff can demonstrate that leadership actively supports the programme."]'::jsonb where oe_code = 'HIC.1.e';

update public.shco_full_oes set achieve_tips = '["Designate at least one room with negative pressure or physical separation capability for isolation; label it clearly and maintain an up-to-date inventory of isolation equipment (gowns, masks, dedicated equipment).","Post a standard isolation protocol on the door of every isolation room so nursing staff can implement barrier nursing without referencing a separate manual.","Record each patient placed in isolation — date, indication, precaution type, and duration — in a dedicated isolation register; make this register available for assessor review.","Conduct monthly mock drills for barrier nursing procedures and document observations and corrective actions to show assessors that staff competency in isolation is actively maintained."]'::jsonb where oe_code = 'HIC.1.f';

update public.shco_full_oes set achieve_tips = '["Display the standard precautions bundle (gloves, mask, gown, eye protection, safe sharps disposal) as a laminated quick-reference card at every nursing station and procedure room.","Conduct unannounced spot checks by the Infection Control Nurse at least weekly to observe whether staff are using PPE correctly; record findings and share feedback with department heads.","Ensure a signed standard precautions compliance checklist is completed for each clinical area every week; file these checklists so assessors can trace compliance trends over time.","Include standard precautions adherence as a standing agenda item in ward staff meetings, and document any deviations along with corrective steps taken."]'::jsonb where oe_code = 'HIC.2.a';

update public.shco_full_oes set achieve_tips = '["Install alcohol-based hand rub dispensers at every bed entry point, procedure trolley, and exit from each ward; check and refill them daily and log refill dates.","Train all clinical staff, housekeeping, and dietary personnel in the WHO 5 Moments for Hand Hygiene; maintain training attendance records that assessors can review.","Conduct monthly hand hygiene compliance audits using the WHO observation tool; post the results on the ward notice board and set a minimum 80% compliance target.","Ensure assessors can observe and interview staff on the correct hand hygiene technique — post step-by-step visual guides above every sink and hand rub dispenser throughout the facility."]'::jsonb where oe_code = 'HIC.2.b';

update public.shco_full_oes set achieve_tips = '["Draft a written Transmission-Based Precautions SOP covering contact, droplet, and airborne categories with clear activation criteria; obtain infection control committee approval and circulate to all wards.","Train nursing and housekeeping staff on donning and doffing sequences for each precaution category; conduct return-demonstration sessions and record staff names, dates, and competency scores.","Maintain a precaution-type assignment register linking each patient to the appropriate precaution level; update it within two hours of a new order and verify it during nursing handover.","During assessments, staff should be able to describe from memory which PPE is required for each transmission category — reinforce this through monthly awareness sessions and post visual cues in isolation areas."]'::jsonb where oe_code = 'HIC.2.c';

update public.shco_full_oes set achieve_tips = '["Standardise a one-drug, one-patient, one-syringe policy through a written SOP and display it at every medication preparation area; include a prohibition on multi-dose vial sharing where feasible.","Audit IV line insertion and maintenance bundles (aseptic technique, dressing changes, access frequency) weekly using a structured checklist; document findings and corrective actions.","Ensure all clinical staff can demonstrate safe needle recapping-free technique and proper sharps disposal during assessor observation — conduct competency checks at least twice a year.","Record all needlestick and sharps injuries in an incident register and review them monthly in the ICC to identify systemic gaps in safe injection practice."]'::jsonb where oe_code = 'HIC.2.d';

update public.shco_full_oes set achieve_tips = '["Draft an Antimicrobial Usage Policy defining approved empirical regimens, restricted antibiotics requiring approval, and de-escalation criteria; have it ratified by the medical committee and pharmacy.","Ensure the policy is accessible at every ward as a printed formulary guide or electronic quick-reference; orient all prescribers during induction and document their acknowledgement.","Maintain a restricted antibiotic approval register recording prescriber name, patient ID, indication, approving authority, and date for every restricted drug issued.","Review the antimicrobial usage policy annually using local antibiogram data; document the review meeting with signatures and update the policy version number and effective date."]'::jsonb where oe_code = 'HIC.2.e';

update public.shco_full_oes set achieve_tips = '["Generate a monthly antibiotic consumption report from pharmacy records, categorised by ward and drug class; present it to the ICC with comments on deviations from the approved policy.","Conduct quarterly prescription audits on a random sample of 10 inpatient files per ward; record findings in an audit register and give prescribers individual feedback within one week.","Ensure assessors can observe the process by which a restricted antibiotic prescription is reviewed and approved — walk them through a live or recent example using the approval register.","Post the list of restricted antibiotics requiring senior approval on every ward and in the pharmacy; train ward pharmacists to flag non-compliant prescriptions before dispensing."]'::jsonb where oe_code = 'HIC.2.f';

update public.shco_full_oes set achieve_tips = '["Establish a formal Antibiotic Stewardship Programme (ASP) with a written charter, designated ASP team (physician, microbiologist, pharmacist), and clear goals such as reducing days of antibiotic therapy.","Implement prospective audit and feedback: the ASP team reviews all patients on antibiotics beyond 72 hours each week and provides written recommendations to prescribers; file all recommendations.","Use local antibiogram data updated at least annually to guide empirical prescribing guidelines; display the antibiogram summary in the ward and ICU for quick prescriber reference.","Track monthly ASP outcome metrics — antibiotic defined daily doses per 100 bed-days, restricted drug usage, and culture positivity rates — and present trend data to hospital leadership quarterly."]'::jsonb where oe_code = 'HIC.2.g';

update public.shco_full_oes set achieve_tips = '["Document all engineering infection control measures (HVAC maintenance schedules, air exchange rates for OT and ICU, water system flushing logs) in a dedicated preventive maintenance register.","Ensure HVAC filters in OT, ICU, and isolation rooms are cleaned or replaced per manufacturer schedule; maintain a filter change log with dates and technician signatures as evidence.","Conduct quarterly water quality testing for Legionella and coliforms in plumbing systems serving patient care areas; file test reports and any remediation steps taken.","During assessor walk-throughs, staff should be able to locate and describe engineering controls in their area — brief housekeeping and facility managers monthly on their specific responsibilities."]'::jsonb where oe_code = 'HIC.3.a';

update public.shco_full_oes set achieve_tips = '["Before any construction or renovation, prepare a written Infection Control Risk Assessment (ICRA) classifying the project type and patient risk level; get ICC sign-off before work begins.","Implement physical containment barriers (sealed plastic sheeting, dedicated construction-area entry points) during any renovation near patient care areas and inspect them daily; log inspection results.","Restrict construction worker movement to approved pathways and ensure they wear masks and shoe covers in transition zones; maintain a sign-in register showing compliance with these controls.","Conduct post-construction environmental cleaning with surface and air monitoring before reopening renovated areas to patients; document clearance inspection results and the date of patient area reactivation."]'::jsonb where oe_code = 'HIC.3.b';

update public.shco_full_oes set achieve_tips = '["Develop written housekeeping SOPs specifying cleaning frequency, detergent-to-water ratios, colour-coded mop and cloth allocations by zone (OT, ward, toilet), and correct disinfectant contact times.","Train all housekeeping staff on the SOPs before deployment; maintain a training register with staff names, trainer name, date, and competency assessment score so assessors can verify training.","Conduct daily supervisor sign-off on cleaning checklists for each area; file completed checklists weekly so a six-month trail of housekeeping compliance is available for review.","Perform random environmental surface swab cultures in high-risk areas (OT, ICU, procedure rooms) monthly; record results and take corrective action within 24 hours if counts exceed limits."]'::jsonb where oe_code = 'HIC.3.c';

update public.shco_full_oes set achieve_tips = '["Ensure all clinical and housekeeping staff are trained in BMW segregation using the colour-coded bag/container system (yellow, red, white/blue, black) per national BMW rules; maintain training records.","Place labelled, foot-operated BMW bins at every point of generation; inspect all bins daily and record inspection findings in a BMW monitoring checklist signed by the floor supervisor.","Maintain a BMW logbook recording daily waste weight by category, transporter details, and manifest numbers; file manifests so assessors can trace the complete chain of custody for one year.","Ensure staff can correctly demonstrate waste segregation and explain safe sharps disposal during assessor observation — conduct quarterly re-training drills and record attendance and observations."]'::jsonb where oe_code = 'HIC.3.d';

update public.shco_full_oes set achieve_tips = '["Draft a linen management SOP covering collection in leakproof bags at point of use, transport routes separated from clean linen, washing temperature standards, and inspection before re-issue.","Train housekeeping and nursing staff on linen handling procedures; verify competency through direct observation of bag labelling and transport practices and record findings in a supervision log.","Conduct weekly audits of the linen flow — from soiled collection to clean storage — using a structured checklist; file completed checklists and escalate any hygiene lapses to the laundry supervisor.","Maintain clean linen storage in a dedicated, ventilated area off the floor on shelving; inspect storage conditions weekly and record in the linen audit register."]'::jsonb where oe_code = 'HIC.3.e';

update public.shco_full_oes set achieve_tips = '["Develop a written kitchen sanitation SOP covering surface cleaning schedules, equipment sanitisation frequencies, food storage temperatures, and personal hygiene requirements for kitchen staff.","Conduct daily temperature checks on refrigerators, hot-holding equipment, and cooked food; record readings in a food safety logbook and take immediate corrective action if temperatures deviate.","Arrange annual food handler medical examinations and hygiene training; maintain certificates and training records for each kitchen staff member in a personnel file accessible to assessors.","Perform quarterly kitchen hygiene audits using a structured checklist covering pest control, waste disposal, hand washing facilities, and food cross-contamination risks; document findings and corrective actions."]'::jsonb where oe_code = 'HIC.3.f';

update public.shco_full_oes set achieve_tips = '["Implement the CAUTI prevention bundle as a written SOP: sterile insertion technique, closed drainage system, daily catheter necessity review, and prompt removal documentation; train all nursing staff.","Maintain a catheter insertion and removal register for every indwelling urinary catheter patient, recording insertion date, indication, daily review decision, and removal date.","Track monthly CAUTI rates per 1,000 catheter-days by ward; display trending data on the infection control dashboard and present to the ICC with analysis of contributing factors.","Ensure assessors can observe nurses performing catheter care correctly during ward rounds and verify that catheter necessity is reviewed and documented in the patient record every 24 hours."]'::jsonb where oe_code = 'HIC.4.a';

update public.shco_full_oes set achieve_tips = '["Implement the VAP/VAC prevention bundle SOP covering head-of-bed elevation at 30–45 degrees, oral care every four hours, cuff pressure checks, and subglottic secretion drainage where applicable.","Maintain a VAP bundle compliance checklist in every ventilated patient''s chart; the nurse on each shift must complete and sign the checklist before handover.","Calculate and record monthly VAP/VAC rates per 1,000 ventilator-days in the ICU; share trend data with ICU nursing and physician leads and document discussions in ICC minutes.","Train all ICU nursing staff on VAP bundle elements annually and conduct unannounced competency observations; record observation findings and any corrective training provided."]'::jsonb where oe_code = 'HIC.4.b';

update public.shco_full_oes set achieve_tips = '["Document the CLABSI prevention bundle SOP covering maximal barrier precautions at insertion, chlorhexidine skin antisepsis, optimal catheter site selection, and daily removal-necessity assessment.","Maintain a central line insertion checklist in every patient file where a central venous catheter is placed; the inserting clinician and supervising nurse must both sign the completed checklist.","Record monthly CLABSI rates per 1,000 central line-days broken down by ICU and non-ICU areas; review data at ICC meetings and implement targeted corrective actions when rates rise.","Conduct at least biannual simulation-based training on central line insertion and maintenance for all ICU medical and nursing staff; retain attendance records and competency assessment results."]'::jsonb where oe_code = 'HIC.4.c';

update public.shco_full_oes set achieve_tips = '["Implement the SSI prevention bundle as a written SOP: preoperative skin preparation, timely antibiotic prophylaxis (within 60 minutes of incision), normothermia, and glucose control; ensure surgical team sign-off on each element.","Use a pre-operative safety checklist (or integrate SSI bundle compliance into the surgical safety checklist) and file completed checklists in the patient''s operative record.","Conduct 30-day post-discharge SSI surveillance for all elective surgical procedures; record SSI cases, wound classification, and outcomes in a surgical site infection register.","Calculate and trend monthly SSI rates by procedure category; present data to the surgical team and ICC, and document any targeted improvement actions such as antibiotic protocol revisions."]'::jsonb where oe_code = 'HIC.4.d';

update public.shco_full_oes set achieve_tips = '["Develop a written Occupational Health SOP covering pre-employment screening, annual health checks, hepatitis B vaccination, and respiratory fit-testing for staff working in high-risk areas.","Maintain a staff immunisation register recording vaccine name, dose, date, and batch number for each employee; update it whenever new staff join and make it available for assessor review.","Conduct annual occupational health training sessions covering transmission prevention, correct PPE use, and early symptom reporting; document attendance and content covered.","Establish a confidential mechanism for staff to report health concerns or potential occupational exposures; log all reports and ensure a designated occupational health officer reviews each case within 24 hours."]'::jsonb where oe_code = 'HIC.4.e';

update public.shco_full_oes set achieve_tips = '["Display a laminated Post-Exposure Prophylaxis (PEP) protocol at every nursing station and in the emergency department specifying steps to take within 2 hours of a blood-body fluid exposure.","Maintain a PEP register recording every exposure incident: date, staff member, nature of exposure, source patient details (if known), PEP drugs administered, and follow-up serology dates.","Ensure a stock of first-line PEP medications is available 24/7 in the pharmacy or emergency department; document a monthly stock check so availability is never a barrier to timely treatment.","Brief all new staff on PEP protocol during induction and reinforce annually; ensure staff can accurately describe the protocol steps when interviewed by assessors."]'::jsonb where oe_code = 'HIC.4.f';

update public.shco_full_oes set achieve_tips = '["Establish a formal HAI surveillance programme with a written scope document identifying target infections (CAUTI, CLABSI, VAP, SSI), definitions used, data sources, and collection frequency.","Assign the Infection Control Nurse responsibility for weekly active surveillance rounds across all wards; record all potential HAI cases in a surveillance register with patient ID, ward, infection type, and onset date.","Generate monthly infection rate reports per 1,000 device-days or patient-days by ward; trend data over at least six months should be available in graphical form for assessors to review.","Ensure ward staff can describe the HAI surveillance process and know how to report a suspected infection to the infection control team when interviewed during assessments."]'::jsonb where oe_code = 'HIC.5.a';

update public.shco_full_oes set achieve_tips = '["Use the WHO hand hygiene observation tool to conduct structured audits in each ward at least monthly; record individual observations, calculate compliance percentages, and file results by ward and date.","Post ward-level hand hygiene compliance rates on a visual board updated monthly so staff, patients, and assessors can immediately see current performance and improvement trends.","Set a minimum compliance target (e.g., 80%) and trigger an automatic retraining session for any ward falling below target; document the retraining and re-audit within four weeks.","Ensure assessors can observe the audit process live or review completed observation forms covering at least the past three months across all clinical areas."]'::jsonb where oe_code = 'HIC.5.b';

update public.shco_full_oes set achieve_tips = '["Set up an MDRO and highly virulent organism surveillance protocol that links microbiology laboratory reports to the infection control team within 24 hours of a positive culture result.","Maintain a dedicated MDRO register recording organism type, patient ID, ward, isolation date, and decolonisation or contact precaution measures initiated for each confirmed case.","Calculate monthly MDRO incidence rates (new cases per 1,000 patient-days) and track trends on the infection control dashboard; present data with analysis to the ICC each quarter.","Ensure the microbiology lab flags all MDRO isolates on the report with a standardised alert sticker or electronic alert code so clinical staff and the infection control team are notified simultaneously."]'::jsonb where oe_code = 'HIC.5.c';

update public.shco_full_oes set achieve_tips = '["Define outbreak thresholds in writing (e.g., two or more linked cases of the same organism within 72 hours) and activate a documented outbreak response protocol whenever the threshold is crossed.","Maintain an outbreak investigation file for each event, including line listing of cases, environmental investigation results, control measures implemented, and date of outbreak resolution.","Establish a communication tree so that the Medical Superintendent, ICC chair, and relevant ward heads are notified within four hours of a declared outbreak; document all notifications and responses.","Conduct a post-outbreak debrief meeting within two weeks of resolution; prepare a written lessons-learned report and implement at least one systemic corrective action to prevent recurrence."]'::jsonb where oe_code = 'HIC.5.d';

update public.shco_full_oes set achieve_tips = '["Develop a housekeeping surveillance checklist that covers surface cleanliness, colour-coded equipment use, clean-to-dirty workflow, and disinfectant preparation; complete it daily per ward with supervisor signature.","Perform environmental cultures (surface swabs and air settle plates) in the OT, ICU, and procedure rooms monthly; record results and initiate corrective cleaning if colony counts exceed defined limits.","Compile a monthly housekeeping surveillance summary comparing findings across wards; present to the ICC and share feedback with the housekeeping team lead within 48 hours.","Ensure assessors can observe a supervisor conducting a housekeeping audit in real time or review at least three months of completed audit checklists filed in the infection control office."]'::jsonb where oe_code = 'HIC.5.e';

update public.shco_full_oes set achieve_tips = '["Prepare a monthly infection surveillance data analysis report that calculates rates, identifies trends, and highlights outliers; circulate the report to department heads and ICC members within the first week of the following month.","Document all corrective and preventive actions (CAPAs) arising from surveillance data in a CAPA register with responsible person, deadline, and status; review open CAPAs at every ICC meeting.","Provide formal written feedback on surveillance findings to ward nursing-in-charges each month; maintain copies of all feedback communications so assessors can trace the feedback loop.","Present surveillance trend graphs at the quarterly medical staff meeting and record attendance and discussion in the minutes; this demonstrates that data drives clinical decision-making at all levels."]'::jsonb where oe_code = 'HIC.5.f';

update public.shco_full_oes set achieve_tips = '["Ensure the CSSD has clearly demarcated dirty, clean, packing, and sterile storage zones with physical barriers or spatial separation; label each zone with a permanent sign.","Document the zone layout in a floor plan filed in the CSSD SOP manual; during assessor visits, the CSSD in-charge should be able to walk assessors through the workflow from soiled receipt to sterile dispatch.","Verify that the CSSD ventilation provides positive pressure in clean/sterile areas and negative pressure or neutral in the dirty area; maintain HVAC maintenance records confirming this configuration.","Conduct a quarterly CSSD space and workflow audit using a structured checklist; document any congestion, cross-contamination risk, or workflow deviation and implement corrective measures within 30 days."]'::jsonb where oe_code = 'HIC.6.a';

update public.shco_full_oes set achieve_tips = '["Develop written SOPs for each stage of instrument processing — decontamination, inspection, packing, sterilisation cycle selection, cool-down, and sterile storage — with step-by-step instructions and staff sign-off requirements.","Train all CSSD staff on the SOPs before they work independently; conduct competency assessments with return demonstrations and record each staff member''s name, assessment date, and result.","Maintain a sterilisation load log for every cycle run, recording load number, contents, cycle parameters, indicator results, and staff initials; this log must be available for at least two years.","Ensure assessors can observe CSSD staff correctly labelling sterile packs with load number, sterilisation date, expiry date, and autoclave number, and verify this against the load log entries."]'::jsonb where oe_code = 'HIC.6.b';

update public.shco_full_oes set achieve_tips = '["Identify all single-use items currently being reprocessed and validate each against a written reprocessing SOP that meets manufacturer guidance and regulatory requirements; list approved items in a policy document.","Maintain a reprocessing register recording item name, number of reprocessing cycles completed, visual inspection results, sterilisation parameters, and the authorising supervisor''s signature for every batch.","Set a clear maximum reprocessing cycle limit for each approved single-use item and retire items that reach this limit immediately; document retirement and disposal in the register.","Train CSSD staff on how to inspect items for integrity loss (cracks, discolouration, deformation) before reprocessing; conduct six-monthly competency checks and file observation records."]'::jsonb where oe_code = 'HIC.6.c';

update public.shco_full_oes set achieve_tips = '["Conduct and document Bowie-Dick tests daily for pre-vacuum autoclaves and biological indicator tests weekly for all sterilisers; file the results in a validation logbook with dates and pass/fail outcomes.","Perform quarterly physical parametric monitoring (temperature, pressure, time) calibration checks on all sterilisers using calibrated measuring instruments; document calibration reports and retain them.","Record chemical indicator (Class 5 or 6 integrator) results for every sterilisation pack and mark the pack as released only when the indicator confirms adequate process exposure; file batch records accordingly.","Present the sterilisation validation logbook for assessor review showing at least six months of continuous daily and weekly test results; highlight any failed tests and the corrective actions taken."]'::jsonb where oe_code = 'HIC.6.d';

update public.shco_full_oes set achieve_tips = '["Document a written recall SOP specifying the trigger criteria for recall (e.g., failed biological indicator, steriliser malfunction), the tracing method using load logs, and the quarantine procedure for suspect items.","When a sterilisation failure is detected, immediately quarantine all items from the affected load, trace them to patient use using the load log, and document every step in a recall incident report.","Notify the clinical departments that received potentially non-sterile items within two hours of a confirmed failure; file all communication records as part of the recall incident file.","Conduct a root cause analysis after every recall event and implement a documented corrective action; review recall incident reports at the next ICC meeting to verify effectiveness of the corrective measures."]'::jsonb where oe_code = 'HIC.6.e';
